---
title: Mouse.click()
---




= Mouse.click()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wysyła do komputera krótkie kliknięcie w miejscu, w którym znajduje się kursor. Działa to tak samo, jak naciśnięcie i natychmiastowe zwolnienie przycisku myszy.

`Mouse.click()` domyślnie lewy przycisk myszy.
[%hardbreaks]


[float]
=== Składnia
`Mouse.click()` +
`Mouse.click(przycisk)`


[float]
=== Parametry
`przycisk`: który przycisk myszy nacisnąć. Dozwolone typy danych: `char`.

* `MOUSE_LEFT` (domyślnie)
* `MOUSE_RIGHT`
* `MOUSE_MIDDLE`


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  pinMode(2, INPUT);
  // zainicjuj bibliotekę myszy
  Mouse.begin();
}

void loop() {
  // jeśli przycisk jest wciśnięty, kliknij lewym przyciskiem myszy
  if (digitalRead(2) == HIGH) {
    Mouse.click();
  }
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Kiedy używasz polecenia `Mouse.click()`, Arduino przejmuje kontrolę nad myszą! Upewnij się, że masz nad tym kontrolę, zanim użyjesz tego polecenia. Może być przydatny klawisz przełączający kontrolę nad myszą.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../mouseend[Mouse.end()]
* #JĘZYK# link:../mousemove[Mouse.move()]
* #JĘZYK# link:../mousepress[Mouse.press()]
* #JĘZYK# link:../mouserelease[Mouse.release()]
* #JĘZYK# link:../mouseispressed[Mouse.isPressed()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
