---
title: Mouse.release()
---




= Mouse.release()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wysyła wiadomość, że poprzednio wciśnięty przycisk (wywołany poleceniem link: ../mousepress[Mouse.press()]) został zwolniony. `Mouse.release()` domyślnie zwalnia lewy przycisk.
[%hardbreaks]


[float]
=== Składnia
`Mouse.release()` +
`Mouse.release(przycisk)`


[float]
=== Parametry
`przycisk`: który przycisk myszy zwolnić. Dozwolone typy danych: `char`.

* `MOUSE_LEFT` (domyślnie)
* `MOUSE_RIGHT`
* `MOUSE_MIDDLE`


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  // przełącznik, który zainicjuje naciśnięcie klawisza myszy
  pinMode(2, INPUT);
  // przełącznik, który zakończy naciśnięcie klawisza myszy
  pinMode(3, INPUT);
  // zainicjuj bibliotekę Mouse
  Mouse.begin();
}

void loop() {
  // jeśli przełącznik dołączony do styku 2 jest zamknięty, naciśnij i przytrzymaj lewy przycisk myszy
  if (digitalRead(2) == HIGH) {
    Mouse.press();
  }
  // jeśli przełącznik dołączony do styku 3 jest zamknięty, zwolnij lewy przycisk myszy
  if (digitalRead(3) == HIGH) {
    Mouse.release();
  }
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Kiedy używasz polecenia `Mouse.release()`, Arduino przejmuje twoją mysz! Upewnij się, że masz nad tym kontrolę, zanim użyjesz tego polecenia. Może być przydatny klawisz przełączający kontrolę nad myszą.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../mouseclick[Mouse.click()]
* #JĘZYK# link:../mouseend[Mouse.end()]
* #JĘZYK# link:../mousemove[Mouse.move()]
* #JĘZYK# link:../mousepress[Mouse.press()]
* #JĘZYK# link:../mouseispressed[Mouse.isPressed()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
