---
title: Mouse.isPressed()
---




= Mouse.isPressed()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Sprawdza aktualny stan wszystkich przycisków myszy i informuje, czy któryś z nich jest naciśnięty, czy nie.
[%hardbreaks]


[float]
=== Składnia
`Mouse.isPressed();` +
`Mouse.isPressed(przycisk);`

[float]
=== Parametry
Gdy nie ma przekazanej wartości, sprawdza stan lewego przycisku myszy.

`przycisk`: który przycisk myszy sprawdzić. Dozwolone typy danych: `char`.

* `MOUSE_LEFT (domyślnie)`
* `MOUSE_RIGHT`
* `MOUSE_MIDDLE`


[float]
=== Wartości zwracane
Informuje, czy przycisk jest naciśnięty, czy nie. Typ danych: `bool`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  // Przełącznik, który zainicjuje naciśnięcie przycisku myszy
  pinMode(2, INPUT);
  // Przełącznik, który zakończy naciśnięcie przycisku myszy
  pinMode(3, INPUT);
  // Uruchom komunikację szeregową z komputerem
  Serial.begin(9600);
  // zainicjuj bibliotekę myszy
  Mouse.begin();
}

void loop() {
  // zmienna do sprawdzania stanu przycisku
  int stanMyszy = 0;
  // jeśli przełącznik dołączony do styku 2 jest zamknięty, naciśnij i przytrzymaj lewy przycisk myszy i zapisz stan w zmiennej
  if (digitalRead(2) == HIGH) {
    Mouse.press();
    stanMyszy = Mouse.isPressed();
  }
  // jeśli przełącznik dołączony do styku 3 jest zamknięty, zwolnij lewy przycisk myszy i zapisz stan w zmiennej
  if (digitalRead(3) == HIGH) {
    Mouse.release();
    stanMyszy = Mouse.isPressed();
  }
  // wydrukować aktualny stan przycisku myszy
  Serial.println(stanMyszy);
  delay(10);
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../mouseclick[Mouse.click()]
* #JĘZYK# link:../mouseend[Mouse.end()]
* #JĘZYK# link:../mousemove[Mouse.move()]
* #JĘZYK# link:../mousepress[Mouse.press()]
* #JĘZYK# link:../mouserelease[Mouse.release()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
