---
title: sizeof()
categories: [ "Zmienne" ]
subCategories: [ "Narzędzia" ]
---

= sizeof

Zmienne
[#overview]
--

[float]
=== Opis
Operator `sizeof` zwraca liczbę bajtów w określonym typie zmiennej lub liczbę bajtów zajmowanych przez tablicę.
[%hardbreaks]


[float]
=== Składnia
`sizeof(zmienna)`


[float]
=== Parametry
`zmienna`: Rzecz, której chcesz poznać rozmiar. Dozwolone typy danych: dowolnego typu zmienne lub tablice (np. `int`, `float`, `byte`).


[float]
=== Wartości zwracane
Liczba bajtów w zmiennej lub bajtów zajmowanych przez tablicy. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ

// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Operator `sizeof` jest przydatny do pracy z tablicami (łańcuchami), gdzie wygodnie jest móc zmienić rozmiar tablicy bez przerywania innych części programu.

Ten program drukuje ciąg tekstowy znak po znaku. Spróbuj zmienić frazę tekstową.

[source,arduino]
----
char napis[] = "to jest test";

void setup() {
  Serial.begin(9600);
}

void loop() {
  for (byte i = 0; i < sizeof(napis) - 1; i++) {
    Serial.print(i, DEC);
    Serial.print(" = ");
    Serial.write(napis[i]);
    Serial.println();
  }
  delay(5000);  // spowalniamy program
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Zauważ, że `sizeof` zwraca całkowitą liczbę bajtów. Tak więc w przypadku tablic większych typów zmiennych, takich jak int, pętla for wyglądałaby mniej więcej tak.

[source,arduino]
----
int wartosci[] = {123, 456, 789};

// pętla for działa poprawnie z tablicą dowolnego typu i rozmiaru
for (byte i = 0; i < (sizeof(wartosci) / sizeof(wartosci[0])); i++) {
  // wykorzystaj do czegoś wartosci[i]
}
----

Zauważ, że poprawnie sformatowany ciąg znaków kończy się znakiem NULL, który ma wartość ASCII 0.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
