---
title: tablica
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= Tablice

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Tablica to zbiór zmiennych dostępnych za pomocą numeru elementu (tzw. indeksu). Tablice w języku programowania C++ umieszczane w szkicach Arduino, mogą być skomplikowane, ale użycie prostych tablic jest stosunkowo proste.
[float]
=== Tworzenie (deklarowanie) tablicy

Wszystkie poniższe metody są prawidłowymi sposobami tworzenia (deklarowania) tablicy.
[source,arduino]
----
  int mojeLiczby[6];
  int mojeStyki[] = {2, 4, 8, 3, 6};
  int mojeCzujniki[6] = {2, 4, -8, 3, 2};
  char komunikat[6] = "witaj";
----
Możesz zadeklarować tablicę bez inicjowania jej (czyli bez przypisywania jej jakichkolwiek wartości) jak w mojeLiczby.
{empty} +
W mojeStyki deklarujemy tablicę bez jawnego podawania jej rozmiaru. Kompilator zlicza elementy i tworzy tablicę o odpowiednim rozmiarze.
{empty} +
Wreszcie możesz zarówno zainicjować, jak i podać rozmiar tablicy, tak jak w mojeCzujniki. Pamiętaj, że deklarując tablicę typu char, wymagany jest o jeden element więcej niż inicjowanie by wymagało, aby pomieścić wymagany znak null na końcu.
[%hardbreaks]

[float]
=== Dostęp do tablicy
Tablice są indeksowane od zera, to znaczy, odnosząc się do deklaracji tablicy powyżej, pierwszy element tablicy ma indeks 0, stąd

`mojeStyki[0] == 2, mojeCzujniki[1] == 4,` i tak dalej.

Oznacza to również, że w tablicy z dziesięcioma elementami ostatnim elementem jest element numer dziwięć. W związku z tym:

[source,arduino]
----
int mojaTablica[10]={9, 3, 2, 4, 3, 2, 7, 8, 9, 11};
// mojaTablica[9]    zawiera 11
// mojaTablica[10]   jest nieprawidłowy i zawiera losowe informacje (inny adres pamięci)
----
Z tego powodu należy zachować ostrożność podczas dostępu do tablic. Dostęp poza koniec tablicy (przy użyciu numeru elementu większego niż zadeklarowany rozmiar tablicy-1) oznacza odczyt z pamięci używanej do innych celów. Odczyt z takiej lokalizacji prawdopodobnie nie przyniesie wiele, poza uzyskaniem nieprawidłowych danych. Zapisywanie w losowych lokalizacjach pamięci jest zdecydowanie złym pomysłem i często może prowadzić do niepomyślnych sytuacji, takich jak awarie lub nieprawidłowe działanie programu. Tego typu błąd może być również trudny do wyśledzenia.
[%hardbreaks]

W przeciwieństwie do języków BASIC lub JAVA, kompilator C++ nie sprawdza, czy dostęp do tablicy mieści się w prawidłowych granicach zadeklarowanego rozmiaru tablicy.
[%hardbreaks]

[float]
=== Przypisanie wartości do tablicy:
`mojeCzujniki[0] = 10;`
[%hardbreaks]

[float]
=== Pobranie wartości z tablicy:
`x = mojeCzujniki[4];`
[%hardbreaks]

[float]
=== Tablice i pętle FOR
Operacje na tablicach często wykonuje się w pętlach, gdzie licznik pętli jest używany jako numer dla każdego elementu tablicy. Na przykład, aby wydrukować elementy tablicy na porcie szeregowym, możesz zrobić coś takiego:

[source,arduino]
----
for (byte i = 0; i < 5; i = i + 1) {
  Serial.println(mojeStyki[i]);
}
----
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Kompletny program demonstrujący użycie tablic pokazuje (http://www.arduino.cc/en/Tutorial/KnightRider[przykład Knight Rider]) ze strony: (http://www.arduino.cc/en/Main/LearnArduino[Przewodniki]).

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../utilities/progmem[PROGMEM]


--
// KONIEC SEKCJI ZOBACZ TAKŻE
