---
title: char
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= char

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Typ danych używany do przechowywania wartości znaku. Literały znakowe są pisane w apostrofach, jak np.: 'A' (w przypadku wielu znaków - czyli ciągów - użyj cudzysłowów: "ABC").

Znaki są jednak przechowywane jako liczby. Możesz zobaczyć poszczególne kody znaków na stronie link:https://www.arduino.cc/en/Reference/ASCIIchart[tabela ASCII]. Oznacza to, że możliwe jest wykonywanie obliczeń na znakach, w których używana jest wartość ASCII znaku (np. 'A' + 1 da wartość 66, ponieważ wartość ASCII wielkiej litery A wynosi 65). Więcej informacji na temat tłumaczenia znaków na liczby można znaleźć w dokumentacji link:../../../functions/communication/serial/println[`Serial.println`].

Rozmiar typu danych `char` wynosi co najmniej 8 bitów. Zaleca się używanie `char` tylko do przechowywania znaków. W przypadku liczby jednobajtowej (8-bitowej) bez znaku użyj typu link:../byte[byte].
[%hardbreaks]


[float]
=== Składnia
`char zm = wart;`


[float]
=== Parametry
`zm`: nazwa zmiennej. +
`wart`: wartość przypisana do tej zmiennej.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄

[source,arduino]
----
char mójZnak = 'A';
char mójZnak = 65; // oba zapisy oznaczają to samo
----


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../../functions/communication/serial/println[Serial.println]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
