---
title: double
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= double

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Liczba zmiennoprzecinkowa podwójnej precyzji. Na płytce Uno i innych opartych na ATMEGA zajmuje 4 bajty. Oznacza to, że podwójna implementacja jest dokładnie taka sama jak liczba typu float, bez zmiany precyzji.

W Arduino Due liczby typu double mają 8-bajtową (64-bitową) precyzję.
[%hardbreaks]


[float]
=== Składnia
`double zm = wart;`


[float]
=== Parametry
`zm`: nazwa zmiennej. +
`wart`: wartość przypisana do tej zmiennej.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--


[float]
=== Uwagi i ostrzeżenia
Użytkownicy, którzy biorą kod z innych źródeł, który zawiera zmienne typu double, mogą sprawdzić kod, aby zobaczyć, czy oczekiwana dokładność różni się od tej faktycznie osiągniętej w płytkach Arduino opartych na ATMEGA.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
