---
title: float
categories: [ "Zmienne" ]
subCategories: [ "Typy danych" ]
---





= float


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Typ danych dla liczb zmiennoprzecinkowych, czyli liczb z przecinkiem dziesiętnym. Liczby zmiennoprzecinkowe są często używane do przybliżania wartości analogowych i ciągłych, ponieważ mają większą rozdzielczość niż liczby całkowite. Liczby zmiennoprzecinkowe mogą być w zakresie od -3,4028235E+38 do 3,4028235E+38. Przechowywane są jako liczby 32-bitowe (4-bajtowe).


[%hardbreaks]

[float]
=== Składnia
`float zm = wart;`

[float]
=== Parametry
`zm`: nazwa zmiennej. +
`wart`: wartość przypisana do tej zmiennej.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
float mojazm;
float kalibCzujnika = 1.117;

int x;
int y;
float z;

x = 1;
y = x / 2;          // y zawiera teraz 0 ponieważ zmienne typu int nie mogą przechowywać ułamków
z = (float)x / 2.0; // z zawiera teraz 0,5 (musisz użyć 2.0, zamiast 2)
----


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Uwagi i ostrzeżenia
Jeśli robisz obliczenia z liczbami zmiennoprzecinkowymi, musisz dodać kropkę dziesiętną, w przeciwnym razie liczba będzie traktowana jako całkowita. Aby uzyskać szczegółowe informacje, zobacz stronę link:../../constants/floatingpointconstants[Floating point].

Typ danych zmiennoprzecinkowych ma dokładność tylko do 6-7 cyfr. Oznacza to całkowitą liczbę cyfr, a nie ilość cyfr po prawej stronie przecinka. W przeciwieństwie do innych platform, w których można uzyskać większą dokładność, używając typu double (np. do 15 cyfr), w Arduino double ma taki sam rozmiar jak typ float.

Liczby zmiennoprzecinkowe nie są dokładne i mogą dawać dziwne wyniki przy porównywaniu. Na przykład 6.0/3.0 może nie być równe 2.0. Zamiast tego powinieneś sprawdzić, czy wartość bezwzględna różnicy między liczbami jest mniejsza niż jakaś niewielka liczba.

Konwersja z liczb zmiennoprzecinkowych na całkowite powoduje obcięcie części ułamkowej (a nie zaokrąglanie):
[source,arduino]
----
float x = 2.9; // zmienna typu zmiennoprzecinkowego
int y = x;     // 2
----

Natomiast jeśli podczas procesu konwersji chcesz zaokrąglić wynik musisz dodać `0.5`:
[source,arduino]
----
float x = 2.9;
int y = x + 0.5;  // 3
----
lub użyć funkcji `round()`:
[source,arduino]
----
float x = 2.9;
int y = round(x);  // 3
----

Matematyka zmiennoprzecinkowa jest również znacznie wolniejsza niż matematyka liczb całkowitych podczas wykonywania obliczeń, dlatego należy jej unikać, na przykład jeśli pętla musi działać z najwyższą prędkością, aby uzyskać krytyczną funkcję pomiaru czasu. Programiści często starają się przekształcić obliczenia zmiennoprzecinkowe w całkowitoliczbowe w celu zwiększenia prędkości.

[%hardbreaks]
[float]
=== Zobacz także

[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
