---
title: int
categories: [ "Zmienne" ]
subCategories: [ "Typy danych" ]
---

= int


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Liczby całkowite są podstawowym typem danych do przechowywania liczb.

Na Arduino Uno (i innych płytach opartych na ATmega) typ int przechowuje wartość 16-bitową (2-bajtową). Daje to zakres od -32.768 do 32.767 (minimalna wartość -2^15 i maksymalna wartość (2^15)-1).
Na płytach opartych na Arduino Due i SAMD (takich jak MKR1000 i Zero), typ int przechowuje wartość 32-bitową (4-bajtową). Daje to zakres -2.147.483.648 do 2.147.483.647 (minimalna wartość -2^31 i maksymalna wartość (2^31)-1).

Typ int przechowuje liczby ujemne za pomocą techniki znanej jako (https://pl.wikipedia.org/wiki/Kod_uzupe%C5%82nie%C5%84_do_dw%C3%B3ch[Kod uzupełnień do dwóch]). Ustawiony najbardziej znaczący bit, czasami nazywany bitem "znaku", oznacza liczbę ujemną. Reszta bitów jest odwrócona i dodane jest 1.

Arduino dba o to, aby wykonywanie operacji arytmetycznych na liczbach ujemnych odbywało się w oczekiwany sposób. Niemniej jednak trzeba uważać na możliwe komplikacje przy operacjach gdzie użyty będzie link:../../../structure/bitwise-operators/bitshiftright/[Operator przesunięcia w prawo] (>>).
[%hardbreaks]


[float]
=== Składnia
`int zm = wart;`


[float]
=== Parametry
`zm`: nazwa zmiennej. +
`wart`: wartość przypisana do tej zmiennej.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Ten kod tworzy liczbę całkowitą o nazwie „liczWGore”, która początkowo jest ustawiona na 0 (zero). Wartość zmiennej zwiększana o 1 (jeden) w każdym przebiegu pętli, wyświetlana jest na monitorze szeregowym.

[source,arduino]
----
int liczWGore = 0;           // tworzy zmienną całkowitą o nazwie 'liczWGore'

void setup() {
  Serial.begin(9600);       // użyj monitora szeregowego do drukowania liczb
}

void loop() {
  liczWGore++;                // Dodaj 1 do liczWGore za każdym razem
  Serial.println(liczWGore);  // drukuj aktualny stan zmiennej liczWGore
  delay(1000);
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
W przyadku przekroczenia maksymalnej lub minimalnej wartości zmiennej ze znakiem zmienne te _przepełniają się_. Wynik przepełnienia jest nieprzewidywalny, dlatego należy tego unikać. Typowym objawem przepełnienia jest zmienna "przeskakująca" od maksymalnej swojej wartości do minimalnej lub odwrotnie, ale nie zawsze tak jest. Jeśli celowo chcesz takiego zachowania, zastosuj typ link:../unsignedint/[unsigned int].


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Stałe całkowite]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
