---
title: long
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---





= long


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Zmienne typu long rozszerzają rozmiar przechowywanych liczb do 32 bitów (4 bajtów), w zakresie od -2.147.483.648 do 2.147.483.647.

Jeśli wykonujesz obliczenia z liczbami całkowitymi, po co najmniej jednej z liczb musi znajdować się litera L by wymusić typ danych long. Aby uzyskać szczegółowe informacje zabacz stronę link:../../constants/integerconstants[Stałe całkowite].
[%hardbreaks]

[float]
=== Składnia
`long zm = wart;`


[float]
=== Parametry
`zm`: nazwa zmiennej. +
`wart`: wartość przypisana do tej zmiennej.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
long predkoscSwiatla = 186000L;  // na temat litery 'L' zobacz stronę Stałe Całkowite
----

--
// KONIEC SEKCJI JAK UŻYWAĆ

// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Stałe całkowite]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
