---
title: ciągi znaków
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= ciągi (łańcuchy) znaków

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Ciągi tekstowe mogą być reprezentowane na dwa sposoby: możesz użyć typu danych String, który jest typem wbudowanym od wersji 0019, lub możesz utworzyć ciąg znaków z tablicy typu char i zakończyć go znakiem o kodzie zero (null). Ta strona opisuje drugą metodę. Aby uzyskać więcej informacji na temat obiektu String, który zapewnia większą funkcjonalność kosztem większej ilości pamięci, zajrzyj na stronę link:../stringobject[obiekt String].
[%hardbreaks]

[float]
=== Składnia
Wszystkie poniższe przykłady są poprawnymi deklaracjami ciągów.

`char Str1[15];` +
`char Str2[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o'};` +
`char Str3[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o', '\0'};` +
`char Str4[] = "arduino";` +
`char Str5[8] = "arduino";` +
`char Str6[15] = "arduino";`

*Sposoby deklarowania ciągów*

* Zadeklaruj tablicę znaków bez inicjowania jej jak w Str1
* Zadeklaruj tablicę znaków (o wielkości o jeden większej od ilości znaków), a kompilator doda wymagany znak null, jak w Str2
* Jawnie dodaj znak null, Str3
* Zainicjuj za pomocą stałej znakowej w cudzysłowie; kompilator dopasuje tablicę do rozmiaru ciągu wraz ze znakiem zerowym na końcu, Str4
* Zainicjuj tablicę jawnie podanym rozmiarem i stałą znakową, Str5
* Zainicjuj tablicę, pozostawiając dodatkowe miejsce na większy ciąg, Str6

*Zakończenie zerem*

Ogólnie, ciągi zakończone są znakiem zerowym (kod ASCII 0). Pozwala to funkcjom (takim jak `Serial.print ()`) stwierdzić, gdzie jest koniec ciągu. W przeciwnym razie kontynuowałyby czytanie kolejnych bajtów pamięci, które tak naprawdę nie są częścią ciągu.

Oznacza to, że na końcu ciągu musi znajdować się miejsce na jeden znak więcej niż długość tekstu, który ma zawierać. Właśnie dlatego Str2 i Str5 muszą mieć osiem znaków, mimo że "arduino" ma tylko siedem znaków - ostatnia pozycja jest automatycznie wypełniana znakiem zerowym. Str4 będzie automatycznie powiększony do ośmiu znaków, o jeden więcej dla dodatkowego zera. W Str3 jawnie umieściliśmy znak zerowy (zapisany „\0”).

Zauważ, że możliwe jest posiadanie ciągu bez końcowego znaku zerowego (np. jeśli długość podałeś Str2 jako siedem zamiast osiem). Spowoduje to uszkodzenie działania większości funkcji korzystających z ciągów, więc raczej nie powinieneś robić tego celowo. Jeśli zauważysz, że coś dziwnie się zachowuje (podczas operacji na znakach spoza ciągu), to w tym może być problem.

*Apostrofy czy cudzysłowy?*

Ciągi znaków zawsze definiowane są w cudzysłowach ("Abc"), a znaki zawsze definiowane są w apostrofach ('A').

*Zawijanie długich ciągów*

Możesz zawijać długie łańcuchy w ten sposób:

[source,arduino]
----
char mójŁańcuch[] = "To jest pierwsza linia"
" to jest druga linia"
" i tak dalej";
----

*Tablice ciągów*

Podczas pracy z dużymi ilościami tekstu, na przykład w projekcie z wyświetlaczem LCD, wygodne jest użycie tablicy ciągów. Ponieważ ciągie same są tablicami, jest to w rzeczywistości przykład tablicy dwuwymiarowej.

W poniższym programie gwiazdka po typie danych `char` "`char*`" wskazuje, że jest to tablica "wskaźników". Wszystkie nazwy tablic są w rzeczywistości wskaźnikami, więc jest to wymagane do utworzenia tablicy tablic. Dla początkujących Wskaźniki są jedną z bardziej tajemniczych części C++, ale zrozumienie wskaźników nie jest konieczne, aby skutecznie ich tutaj używać.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
char *mojeNapisy[] = {"To jest napis 1", "To jest napis 2", "To jest napis 3",
                      "To jest napis 4", "To jest napis 5", "To jest napis 6"
                    };

void setup() {
  Serial.begin(9600);
}

void loop() {
  for (int i = 0; i < 6; i++) {
    Serial.println(mojeNapisy[i]);
    delay(500);
  }
}
----


--
// KONIEC SEKCJI JAK UŻYWAĆ

// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../utilities/progmem[PROGMEM]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
