---
title: "String()"
categories: [ "Zmienne" ]
subCategories: [ "Typy danych" ]
---

= String()

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Tworzy instancję klasy String (obiekt tekstowy - napis). Istnieje wiele sposobów konstruowania ciągów z różnych typów danych (tj. przedstawiania ich jako sekwencji znaków), w tym:

* stała znakowa, w cudzysłowach (tablica znaków)
* pojedynczy znak, w apostrofach
* na podstawie innej instancji obiektu String
* stała całkowita lub całkowita długa
* stała całkowita lub całkowita długa, o określonej podstawie (np. dwójkowej, ósemkowej)
* zmienna całkowita lub całkowita długa
* zmienna całkowita lub całkowita długa, o określowej podstawie
* liczba zmiennoprzecinkowa lub podwójna, o określonej liczbie miejsc dziesiętnych

Tworzenie obiektu tekstowego liczby daje ciąg zawierający reprezentację ASCII tej liczby. Domyślną podstawą sytemu liczbowego jest dziesięć, dlatego
[source,arduino]
----
String napis = String(13);
----
daje w wyniku napis "13". Można jednak użyć innych podstaw liczenia. Na przykład,


[source,arduino]
----
String napis = String(13, HEX);
----

daje w wyniku napis "D", który jest szesnastkową reprezentacją dziesiętnej liczby 13. Lub jeśli wolisz system dwójkowy,

[source,arduino]
----
String napis = String(13, BIN);
----

daje w wyniku napis "1101", który jest dwójkową reprezentacją dziesiętnej liczby 13.
[%hardbreaks]


[float]
=== Składnia
`String(wart)` +
`String(wart, pods)` +
`String(wart, poPrzecinku)`


[float]
=== Parametry
`wart`:  zmienna do przedstawienia jako ciąg znaków. Dozwolone typy danych: string, char, byte, int, long, unsigned int, unsigned long, float, double. +
`pods`: (opcjonalnie) podstawa systemu liczbowego, w którym ma być przedstawiona liczba całkowita. +
`poPrzecinku`: *tylko jeśli wart jest zmiennoprzecinkowa lub o podwójej precyzji (float lub double)*. Liczba miejsc po przecinku.


[float]
=== Wartości zwracane
Instancja klasy String - po prostu napis.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Wszystkie poniższe są poprawnymi deklaracjami ciągów.
[source,arduino]
----
String napisJeden = "Napis powitalny";                 // przy użyciu stałej znakowej
String napisJeden = String('a');                       // konwertując pojedynczy znak na obiekt typu String
String napisDwa   = String("To jest napis");           // konwertując stałą znakową na obiekt typu String
String napisJeden = String(napisDwa + " z dodatkiem"); // łącząc dwa ciągi znaków
String napisJeden = String(13);                        // przy użyciu stałej całkowitej
String napisJeden = String(analogRead(0), DEC);        // przy użyciu liczby całkowitej w systemie dziesiętnym
String napisJeden = String(45, HEX);                   // przy użyciu liczby całkowitej w systemie szesnastkowym
String napisJeden = String(255, BIN);                  // przy użyciu liczby całkowitej w systemie dwójkowym
String napisJeden = String(millis(), DEC);             // przy użyciu liczby całkowitej długiej w określonym systemie
String napisJeden = String(5.698, 3);                  // przy użyciu liczby zmiennoprzecinkowej o określonej liczbie miejsc po przecinku
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


[float]
=== Funkcje

[role="language"]
* #LANGUAGE# link:../string/functions/charat[charAt()]
* #LANGUAGE# link:../string/functions/compareto[compareTo()]
* #LANGUAGE# link:../string/functions/concat[concat()]
* #LANGUAGE# link:../string/functions/c_str[c_str()]
* #LANGUAGE# link:../string/functions/endswith[endsWith()]
* #LANGUAGE# link:../string/functions/equals[equals()]
* #LANGUAGE# link:../string/functions/equalsignorecase[equalsIgnoreCase()]
* #LANGUAGE# link:../string/functions/getbytes[getBytes()]
* #LANGUAGE# link:../string/functions/indexof[indexOf()]
* #LANGUAGE# link:../string/functions/lastindexof[lastIndexOf()]
* #LANGUAGE# link:../string/functions/length[length()]
* #LANGUAGE# link:../string/functions/remove[remove()]
* #LANGUAGE# link:../string/functions/replace[replace()]
* #LANGUAGE# link:../string/functions/reserve[reserve()]
* #LANGUAGE# link:../string/functions/setcharat[setCharAt()]
* #LANGUAGE# link:../string/functions/startswith[startsWith()]
* #LANGUAGE# link:../string/functions/substring[substring()]
* #LANGUAGE# link:../string/functions/tochararray[toCharArray()]
* #LANGUAGE# link:../string/functions/todouble[toDouble()]
* #LANGUAGE# link:../string/functions/toint[toInt()]
* #LANGUAGE# link:../string/functions/tofloat[toFloat()]
* #LANGUAGE# link:../string/functions/tolowercase[toLowerCase()]
* #LANGUAGE# link:../string/functions/touppercase[toUpperCase()]
* #LANGUAGE# link:../string/functions/trim[trim()]

[float]
=== Operatory

[role="language"]
* #LANGUAGE# link:../string/operators/elementaccess[[\] (element access)]
* #LANGUAGE# link:../string/operators/concatenation[+ (concatenation)]
* #LANGUAGE# link:../string/operators/append[+= (append)]
* #LANGUAGE# link:../string/operators/comparison[== (równe)]
* #LANGUAGE# link:../string/operators/greaterthan[> (większe niż)]
* #LANGUAGE# link:../string/operators/greaterthanorequalto[>= (większe bądź równe)]
* #LANGUAGE# link:../string/operators/lessthan[< (mniejsze niż)]
* #LANGUAGE# link:../string/operators/lessthanorequalto[\<= (mniejsze bądź równe)]
* #LANGUAGE# link:../string/operators/differentfrom[!= (różne od)]

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
