---
title: unsigned int
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= unsigned int

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Na płytkach Uno i innych opartych na ATMEGA typy unsigned int (liczby całkowite bez znaku) są takie same jak zwykłe liczby całkowite, ponieważ przechowują wartość 2-bajtową. Zamiast przechowywać również liczby ujemne, przechowują one jedynie wartości dodatnie, dając użyteczny zakres od 0 do 65535 ((2^16)-1).

Due przechowuje wartość 4-bajtową (32-bitową), w zakresie od 0 do 4.294.967.295 (2^32-1).

Różnica między typami całkowitymi bez znaku i całkowitymi ze znakiem polega na sposobie interpretacji najbardziej znaczącego bitu, czasem nazywanego bitem "znaku". W typie całkowitym ze znakiem, jeśli najbardziej znaczący bit jest "1", liczba jest interpretowana jako ujemna, a do pozostałych 15 bitów stosowany jest (https://pl.wikipedia.org/wiki/Kod_uzupe%C5%82nie%C5%84_do_dw%C3%B3ch[kod uzupełnień do dwóch]).
[%hardbreaks]


[float]
=== Składnia
`unsigned int zm = wart;`


[float]
=== Parametry
`zm`: nazwa zmiennej. +
`wart`: wartość przypisana do tej zmiennej.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
unsigned int stykDiody = 13;
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Kiedy zmienne bez znaku przekraczają maksymalną wartość, "przeskakują" z powrotem do 0, działa to także w drugą stronę:

[source,arduino]
----
unsigned int x;
x = 0;
x = x - 1;  // x zawiera teraz 65535 - przeskok w tył
x = x + 1;  // x zawiera teraz 0 - przeskok w przód
----

Obliczenia ze zmiennymi bez znaku mogą dawać nieoczekiwane wyniki, nawet jeśli twoja zmienna bez znaku nigdy się nie przepełnia.

Mikrokontroler stosuje następujące zasady:

Obliczenia są wykonywane w zakresie zmiennej docelowej. Np. jeśli zmienna docelowa jest ze znakiem, wykona obliczenia ze znakiem, nawet jeśli obie zmienne wejściowe są bez znaku.

Jednak w przypadku obliczeń, które wymagają wyniku pośredniego, zakres wyniku pośredniego nie będzie określony przez kod. W takim przypadku mikrokontroler wykona obliczenia bez znaku dla wyniku pośredniego, ponieważ oba wejścia są bez znaku!


[source,arduino]
----
unsigned int x = 5;
unsigned int y = 10;
int wynik;

wynik = x - y;          // 5 - 10 = -5, zgodnie z oczekiwaniami
wynik = (x - y) / 2;    // 5 - 10 w obliczeniach bez znaku to 65530!  65530/2 = 32765

// rozwiązanie: użyj zmiennych ze znakiem lub wykonaj obliczenia krok po kroku.
wynik = x - y;          // 5 - 10 = -5, zgodnie z oczekiwaniami
wynik = wynik / 2;      // -5/2 = -2 (tylko obliczenia całkowite, odrzucone miejsca po przecinku)
----
Po co w ogóle używać zmiennych bez znaku?

- Zachowanie związane z przepełnieniem jest pożądane, np. w licznikach
- zmienna ze znakiem jest nieco za mała, ale chcesz uniknąć utraty pamięci i prędkości w przypadku użycia typów long/float.
--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Stałe całkowite]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
