---
title: unsigned long
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= unsigned long

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Zmienne typu długiego bez znaku to zmienne do przechowywania liczb w rozszerzonym zakresie wynoszącym 32 bity (4 bajty). W przeciwieństwie do standardowych liczb typu długiego liczby długie bez znaku nie przechowują liczb ujemnych, dzięki czemu ich zakres wynosi od 0 do 4.294.967.295 (2^32-1).
[%hardbreaks]

[float]
=== Składnia
`unsigned long zm = wart;`


[float]
=== Parametry
`zm`: nazwa zmiennej. +
`wart`: wartość przypisana do tej zmiennej.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
unsigned long czas;

void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.print("Czas: ");
  czas = millis();
                         // drukuje czas od uruchomienia programu
  Serial.println(czas);
                         // czekaj sekundę, aby nie wysyłać ogromnych ilości danych
  delay(1000);
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE STARTS
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Stałe całkowite]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
