---
title: ">"
title_expanded: większy niż
categories: [ "Data Types" ]
subCategories: [ "StringObject Operator" ]
---





= > Większy niż


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Sprawdza, czy ciąg po lewej jest większy niż ciąg po prawej. Ten operator porównuje ciągi (łańcuchy) w kolejności alfabetycznej, aż do pierwszego znaku, którym oba się różnią. Więc, dla przykładu "b" > "a" i "2" > "1", ale "999" > "1000" ponieważ 9 następuje (w układzie alfabetycznym) po 1.

Ostrożnie: operatory porównania ciągów mogą być mylące podczas porównywania ciągów liczbowych, ponieważ liczby są traktowane jako ciągi znaków, a nie jak liczby. Jeśli chcesz porównać liczby jako liczby, porównaj je jako liczby całkowite, zmiennoprzecinkowe lub długie, a nie ciągi znaków.
[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch1 > mójŁańcuch2`


[float]
=== Parametry
`mójŁańcuch1`: zmienna typu String. +
`mójŁańcuch2`: zmienna typu String.


[float]
=== Wartości zwracane
`true`: jeśli mójŁańcuch1 jest większy niż mójŁańcuch2. +
`false`: w przeciwnym wypadku.

--

// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ

// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
