---
title: analogReadResolution()
categories: [ "Functions" ]
subCategories: [ "Zero, Due & MKR Family" ]
---




= analogReadResolution()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
analogReadResolution () to rozszerzenie Analog API dla Arduino Due, Zero i rodziny MKR.

Ustawia rozmiar (w bitach) wartości zwracanej przez `analogRead()`. Domyślnie jest to 10 bitów (zwraca wartości z zakresu 0-1023) w celu zapewnienia zgodności wstecznej z płytami opartymi na AVR.

Płyty *Due, Zero i rodzina MKR* mają 12-bitowe funkcje ADC, z których można skorzystać, zmieniając rozdzielczość na 12.
Wtedy `analogRead()` zwróci wartości z zakresu od 0 do 4095.
[%hardbreaks]


[float]
=== Składnia
`analogReadResolution(bity)`


[float]
=== Parametry
`bity`: określa rozdzielczość (w bitach) wartości zwracanej przez funkcję `analogRead()`. Możesz podać wartości od 1 do 32. Możesz ustawić rozdzielczości wyższe niż 12, ale wartości zwracane przez `analogRead()` będą ulegać przybliżeniu. Szczegółowe informacje zawiera uwaga poniżej.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program pokazuje, jak używać ADC z różnymi rozdzielczościami

[source,arduino]
----
void setup() {
  // otwórz połączenie szeregowe o szybkości 9600 bitów na sekundę
  Serial.begin(9600);
}

void loop() {
  // odczytaj wejście na A0 z domyślną rozdzielczością (10 bitów)
  // i wyślij poprzez połączenie szeregowe
  analogReadResolution(10);
  Serial.print("ADC 10-bitów (domyślnie) : ");
  Serial.print(analogRead(A0));

  // zmień rozdzielczość na 12 bitów i odczytaj A0
  analogReadResolution(12);
  Serial.print(", 12-bitów : ");
  Serial.print(analogRead(A0));

  // zmień rozdzielczość na 16 bitów i odczytaj A0
  analogReadResolution(16);
  Serial.print(", 16-bitów : ");
  Serial.print(analogRead(A0));

  // zmień rozdzielczość na 8 bitów i przeczytaj A0
  analogReadResolution(8);
  Serial.print(", 8-bitów : ");
  Serial.println(analogRead(A0));

  // małe opóźnienie, aby nie zablokować monitora szeregowego
  delay(100);
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Jeśli ustawisz wartość `analogReadResolution()` na wartość wyższą niż możliwości twojej płyty, Arduino będzie raportować tylko w najwyższej rozdzielczości, wypełniając dodatkowe bity zerami

Na przykład: użycie Due z `analogReadResolution(16)` da przybliżoną 16-bitową liczbę z pierwszymi 12 bitami zawierającymi rzeczywisty odczyt ADC i ostatnimi 4 bitami *uzupełnionymi zerami*.

Jeśli ustawisz wartość `analogReadResolution()` na wartość niższą niż możliwości twojej płyty, dodatkowe najmniej znaczące bity odczytane z ADC zostaną *odrzucone*.

Korzystanie z 16-bitowej rozdzielczości (lub dowolnej rozdzielczości *wyższej* niż rzeczywiste możliwości sprzętowe) pozwala na pisanie szkiców, które automatycznie będą obsługiwać urządzenia z przetwornikiem ADC o wyższej rozdzielczości, gdy staną się one dostępne na przyszłych płytach bez zmiany programu.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #PRZYKŁAD# http://arduino.cc/en/Tutorial/AnalogInputPins[Opis styków wejść analogowych^]

[role="language"]
* #JĘZYK# link:../../analog-io/analogread[analogRead()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
