---
title: analogWriteResolution()
categories: [ "Functions" ]
subCategories: [ "Zero, Due & MKR Family" ]
---




= analogWriteResolution()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`analogWriteResolution()` jest rozszerzeniem Analog API dla Arduino Due.

`analogWriteResolution()` ustawia rozdzielczość funkcji `analogWrite()`. Domyślnie jest to 8 bitów (wartości w zakresie 0-255) dla wstecznej zgodności z płytami opartymi na AVR.

*Due* ma następujące możliwości sprzętowe:
* 12 styków, które domyślnie obsługują 8-bitowe PWM, podobnie jak płyty oparte na AVR. Można je zmienić na rozdzielczość 12-bitową 
* 2 styki z 12-bitowym DAC (przetwornikiem cyfrowo-analogowym)

Ustawiając rozdzielczość zapisu na 12, możesz użyć funkcji `analogWrite()` z wartościami od 0 do 4095, aby wykorzystać pełną rozdzielczość DAC lub ustawić sygnał PWM bez przewijania.


*Zero* ma następujące możliwości sprzętowe:

* 10 styków, które domyślnie obsługują 8-bitowe PWM, podobnie jak płyty oparte na AVR. Można je zmienić na rozdzielczość 12-bitową. 
* 1 styk z 10-bitowym DAC (przetwornikiem cyfrowo-analogowym).

Ustawiając rozdzielczość zapisu na 10, możesz użyć funkcji `analogWrite()` z wartościami od 0 do 1023, aby wykorzystać pełną rozdzielczość przetwornika cyfrowo-analogowego.


Płytki z *Rodziny MKR* mają następujące możliwości sprzętowe: 

* 4 styki, które domyślnie obsługują 8-bitowy PWM, podobnie jak płyty oparte na AVR. Można je zmienić z rozdzielczości 8 (domyślnie) na 12 bitów 
* 1 styk z 10-bitowym DAC (przetwornikiem cyfrowo-analogowym)

Ustawiając rozdzielczość zapisu na 12 bitów, możesz użyć funkcji `analogWrite()` z wartościami od 0 do 4095 dla sygnałów PWM; ustaw 10 bitów na styku DAC, aby wykorzystać pełną rozdzielczość DAC - 1024 wartości.
[%hardbreaks]


[float]
=== Składnia
`analogWriteResolution(bity)`


[float]
=== Parametry
`bity`: określa rozdzielczość (w bitach) wartości używanych w funkcji `analogWrite()`. Wartość może wynosić od 1 do 32. Jeśli wybierzesz rozdzielczość wyższą lub niższą niż możliwości sprzętowe twojej płyty, wartość użyta w `analogWrite()` zostanie albo obcięta, jeśli jest za duża, albo uzupełniona zerami, jeśli jest za niska. Szczegółowe informacje zawiera uwaga poniżej.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program wyjaśniający

[source,arduino]
----
void setup() {
  // otwórz połączenie szeregowe o szybkości 9600 bitów na sekundę
  Serial.begin(9600);
  // styki cyfrowe uczyń wyjściami
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
}

void loop() {
  // odczytaj wejście A0 i odwzoruj je na styk PWM
  // z dołączoną diodą świecącą
  int wartCzujnika = analogRead(A0);
  Serial.print("Odczyt Analogowy) : ");
  Serial.print(wartCzujnika);

  // domyślna rozdzielczość PWM
  analogWriteResolution(8);
  analogWrite(11, map(wartCzujnika, 0, 1023, 0, 255));
  Serial.print(" , 8-bitowa wartość PWM : ");
  Serial.print(map(wartCzujnika, 0, 1023, 0, 255));

  // zmień rodzielczość PWM na 12 bitów
  // pełna 12 bitowa rozdzielczość obsługiwana jest tylko
  // przez płytki Due
  analogWriteResolution(12);
  analogWrite(12, map(wartCzujnika, 0, 1023, 0, 4095));
  Serial.print(" , 12-bitowa wartość PWM : ");
  Serial.print(map(wartCzujnika, 0, 1023, 0, 4095));

  // zmień rozdzielczość PWM na 4 bity
  analogWriteResolution(4);
  analogWrite(13, map(wartCzujnika, 0, 1023, 0, 15));
  Serial.print(", 4-bit PWM value : ");
  Serial.println(map(wartCzujnika, 0, 1023, 0, 15));

  delay(5);
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Jeśli ustawisz wartość `analogWriteResolution()` na wartość wyższą niż możliwości twojej płyty, Arduino odrzuci dodatkowe bity. Na przykład: używając Due z `analogWriteResolution(16)` na 12-bitowym styku DAC, tylko pierwszych 12 bitów wartości przekazanych do `analogWrite()` zostanie użytych, a ostatnie 4 bity zostaną odrzucone. 

Jeśli ustawisz wartość `analogWriteResolution()` na wartość niższą niż możliwości twojej płyty, brakujące bity zostaną *uzupełnione zerami*, aby wypełnić wymagany rozmiar. Na przykład: używając na płycie Due funkcji `analogWriteResolution(8)` na 12-bitowym styku DAC, Arduino doda 4 bity zerowe do 8-bitowej wartości używanej w `analogWrite()`, aby uzyskać wymagane 12 bitów. 

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../analog-io/analogwrite[analogWrite()]
* #JĘZYK# link:../../analog-io/analogread[analogRead()]
* #JĘZYK# link:../../math/map[map()]

[role="example"]
* #PRZYKŁAD# http://arduino.cc/en/Tutorial/AnalogInputPins[Opis styków wejść analogowych^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
