---
title: for
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= for loop


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Instrukcja `for` służy do powtarzania bloku instrukcji zawartego w nawiasach klamrowych. Przyrost jest zwykle używany do zwiększania pewnej wartości i do zakończenia pętli. Instrukcja `for` jest przydatna do każdej powtarzalnej operacji i często jest używana w połączeniu z tablicami do operowania na zbiorach danych lub styków.
[%hardbreaks]


[float]
=== Składnia
[source,arduino]
----
for (początek; warunek; przyrost) {
  // instrukcj(a/e);
}
----


[float]
=== Parametry
`początek`: wykonuje się na początku i dokładnie tylko raz +
`warunek`: w każdym przebiegu pętli sprawdzany jest 'warunek'; jeśli jest prawdziwy to wykonywany jest blok instrukcji a następnie *przyrost*, po czym *warunek* sprawdzany jest ponownie. Jeśli *warunek* stanie się fałszywy, kończy się wykonywanie pętli. +
`przyrost`: wykonywane jest za każdym razem gdy `warunek` jest prawdziwy.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
[source,arduino]
----
// Dim an LED using a PWM pin
int stykPWM = 10;             // do styku numer 10 podłączone są szeregowo dioda świecąca i rezystor 470 om

void setup() {
                  // nie jest potrzebna konfiguracja
}

void loop() {
  for (int i = 0; i <= 255; i++) {
    analogWrite(stykPWM, i);
    delay(10);
  }
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Pętla `for` w języku C++ jest znacznie bardziej elastyczna niż pętle `for` występujące w niektórych innych językach komputerowych, w tym w języku BASIC. Dowolny lub wszystkie trzy elementy nagłówka pętli można pominąć, chociaż średniki są wymagane. Również instrukcje początku, warunku i przyrostu mogą być dowolnymi prawidłowymi instrukcjami C++ z dowolnymi zmiennymi i używać dowolnych typów danych C++, w tym liczb zmiennoprzecinkowych. Tegu typu niezwykłe instrukcje `for` mogą pomóc rozwiązać niektóre problemy programistyczne.
[%hardbreaks]

Na przykład użycie mnożenia w miejscu przyrostu wygeneruje postęp logarytmiczny:

[source,arduino]
----
for (int x = 2; x < 100; x = x * 1.5) {
  println(x);
}
----

Wypisze: 2,3,4,6,9,13,19,28,42,63,94
[%hardbreaks]

Innym przykładem jest rozjaśnianie i ściemnianie diody świecącej za pomocą jednej tylko pętli `for`:

[source,arduino]
----
void loop() {
  int x = 1;
  for (int i = 0; i > -1; i = i + x) {
    analogWrite(stykPWM, i);
    if (i == 255) {
      x = -1;             // na końcu przełącz kierunek
    }
    delay(10);
  }
}
----


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
