---
title: goto
categories: [ "Struktura" ]
subCategories: [ "Instrukcje sterujące" ]
---





= goto


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Przenosi wykonywanie programu do oznaczonego miejsca w programie
[%hardbreaks]


[float]
=== Składnia
[source,arduino]
----
label:

goto miejsce;        // wysyła program w inne miejsce
----

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
for (byte r = 0; r < 255; r++) {
  for (byte g = 255; g > 0; g--) {
    for (byte b = 0; b < 255; b++) {
      if (analogRead(0) > 250) {     // przekroczenie dopuszczalnej temperatury
        goto ratunek;
      }
      // więcej instrukcji ...
    }
  }
}

ratunek:
// więcej instrukcji ...
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Używanie `goto` jest odradzane podczas programowaniu w C++, a niektórzy autorzy książek do programowania w C++ twierdzą, że instrukcja` goto` nie jest nigdzie potrzebna, ale używana rozsądnie, może uprościć niektóre programy. Powodem, dla którego wielu programistów nie używa goto, jest to, że przy nieograniczonym użyciu instrukcji `goto` łatwo jest stworzyć program o nieokreślonym przebiegu, z którego nigdy nie można usunąć błędów.

Prawdę powiedziawszy, są przypadki, w których instrukcja `goto` może się przydać i uprościć programowanie. Jedną z takich sytuacji jest wyrwanie się w pewnych sytuacjach z głęboko zagnieżdżonych pętli link:../for[for], lub bloków warunków link:../if[if].
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także
[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
