---
title: switch...case
categories: [ "Struktura" ]
subCategories: [ "Instrukcje sterujące" ]
---





= instrukcja switch...case


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Podobnie jak instrukcje link:../if[if], również link:../switchcase[switch case] steruje przebiegiem programów umożliwiając programistom przełączenie(ang. switch) wykonania do różnych fragmentów kodu dla różnych przypadków (ang. case). W szczególności instrukcja switch porównuje wartość zmiennej z wartościami określonymi w instrukcjach case. Po znalezieniu instrukcji case, której wartość odpowiada wartości zmiennej, uruchamiany jest kod w tej instrukcji case.
[%hardbreaks]

Słowo kluczowe link:../break[break] służy do opuszczenia instrukcji switch i zwykle jest używane na końcu każdego przypadku testowego (case). Bez instrukcji break instrukcja switch będzie kontynuować wykonywanie kolejnych przypadków ("przelatując przez nie"), aż do osiągnięcia break lub do końca instrukcji switch.
[%hardbreaks]


[float]
=== Składnia
[source,arduino]
----
switch (zmienna) {
  case przypadek1:
    // instrukcje
    break;
  case przypadek2:
    // instrukcje
    break;
  default:
    // instrukcje
    break;
}
----


[float]
=== Parametry
`zmienna`: a variable whose value to compare with various cases. Allowed data types: `int`, `char`. +
`przypadek1`, `przypadek2`: stałe. Dozwolone typy danych: `int`, `char`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
switch (zmienna) {
  case 1:
    // zrób coś gdy zmienna równa się 1
    break;
  case 2:
    // zrób coś gdy zmienna równa się 2
    break;
  default:
    // jeśli nic innego nie pasuje, zrób czynności domyślne
    // default nie jest obowiązkowy
    break;
}

----
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także
[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
