---
title: analogReference()
categories: [ "Funkcje" ]
subCategories: [ "Analogowe We/wy" ]
---


//


= analogReference()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Konfiguruje napięcie odniesienia używane dla wejścia analogowego (tj. wartość wykorzystywaną jako górną część zakresu wejściowego). Dostępne są następujące opcje:

Płytki Arduino AVR (Uno, Mega, itp.)

* DOMYŚLNE: domyślne odniesienie analogowe do 5 woltów (na płytkach Arduino 5V) lub 3,3 wolta (na płytkach Arduino 3,3V)
* WEWNĘTRZNE: wbudowane odniesienie, równe 1,1V w ATmega168 lub ATmega328P i 2,56 V w ATmega8 (niedostępne w Arduino Mega)
* INTERNAL1V1: wbudowane napięcie odniesienia 1.1V (tylko Arduino Mega)
* INTERNAL2V56: wbudowane napięcie odniesienia 2,56 V (tylko Arduino Mega)
* ZEWNĘTRZNY: jako odniesienie służy napięcie podane na styk AREF (tylko od 0 do 5V).

Płytki Arduino SAMD (Zero, itp.)

* AR_DEFAULT: domyślne odniesienie analogowe 3,3V.
* AR_INTERNAL: wbudowane napięcie odniesienia 2,23V.
* AR_INTERNAL1V0: wbudowane odniesienie 1,0V.
* AR_INTERNAL1V65: wbudowane odniesienie 1,65V.
* AR_INTERNAL2V23: wbudowane odniesienie 2,23V.
* AR_EXTERNAL: jako odniesienie służy napięcie przyłożone do pinu AREF

Płytki Arduino megaAVR (Uno WiFi Rev2)

* DOMYŚLNE: wbudowane napięcie odniesienia 0,55V.
* WEWNĘTRZNE: wbudowane napięcie odniesienia 0,55V.
* VDD: Vdd ATmega4809. 5V w Uno WiFi Rev2
* INTERNAL0V55: wbudowane napięcie odniesienia 0,55V.
* INTERNAL1V1: wbudowane napięcie odniesienia 1.1V
* INTERNAL1V5: wbudowane napięcie odniesienia 1,5V.
* INTERNAL2V5: wbudowane napięcie odniesienia 2,5V.
* INTERNAL4V3: wbudowane napięcie odniesienia 4,3V.
* ZEWNĘTRZNY: jako odniesienie służy napięcie przyłożone do styku AREF (tylko od 0 do 5V)

Płytki Arduino SAM (Due)

* AR_DEFAULT: domyślne odniesienie analogowe 3,3V. Jest to jedyna opcja obsługiwana przez Due.

[%hardbreaks]


[float]
=== Składnia
`analogReference(typ)`


[float]
=== Parametry
`typ`: jakiego rodzaju odniesienia użyć (patrz lista opcji w opisie).


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i ostrzeżenia
Po zmianie napięcia odniesienia kilka pierwszych odczytów z `analogRead()` może być niedokładnych.

*Dla zewnętrznego napięcia odniesienia na styku AREF nie używaj mniejszych wartości niż 0V lub większych niż 5V! Jeśli używasz zewnętrznego odniesienia na styku AREF, musisz ustawić rodzaj odniesienia na ZEWNĘTRZNE przed wywołaniem `analogRead()`.* W przeciwnym razie zewrzesz razem aktywne napięcie odniesienia (generowane wewnętrznie) i styk AREF, prawdopodobnie uszkadzając mikrokontroler na płycie Arduino.

Alternatywnie można podłączyć zewnętrzne napięcie odniesienia do styku AREF za pomocą rezystora 5K, umożliwiając przełączanie między zewnętrznymi i wewnętrznymi napięciami odniesienia. Zauważ, że rezystor zmieni napięcie, które zostanie użyte jako odniesienie, ponieważ na styku AREF znajduje się wewnętrzny rezystor 32K. Oba działają jak dzielnik napięcia, więc na przykład 2,5V podane przez rezystor da 2,5 * 32 / (32 + 5) = ~ 2,2V na styku AREF.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Opis wejściowych styków analogowych^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
