---
title: analogWrite()
categories: [ "Funkcje" ]
subCategories: [ "Analogowe We/Wy" ]
---





= analogWrite()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wysyła na styk wartość analogową (http://arduino.cc/en/Tutorial/PWM[fala PWM]). Może być stosowany do zapalania diod świecących przy różnych poziomach jasności lub do napędzania silnika z różnymi prędkościami. Po wywołaniu `analogWrite()`, na styku będzie ciągle generowana fala prostokątna o określonym wypełnieniu, aż do następnego wywołania `analogWrite()` (lub wywołania `digitalRead()` lub `digitalWrite()`) na tym samych styku.
[options="header"]
|====================================================================================================
| Płytka               | styki PWM                       | Częstotliwość PWM
| Uno, Nano, Mini      | 3, 5, 6, 9, 10, 11              | 490 Hz (styki 5 i 6: 980 Hz)
| Mega                 | 2 - 13, 44 - 46                 | 490 Hz (styki 4 i 13: 980 Hz)
| Leonardo, Micro, Yún | 3, 5, 6, 9, 10, 11, 13          | 490 Hz (styki 3 i 11: 980 Hz)
| Uno WiFi Rev.2       | 3, 5, 6, 9, 10                  | 976 Hz
| płytki MKR *         | 0 - 8, 10, A3 (18), A4 (19)     | 732 Hz
| MKR1000 WiFi *       | 0 - 8, 10, 11, A3 (18), A4 (19) | 732 Hz
| Zero *               | 3 - 13, A0 (14), A1 (15)        | 732 Hz
| Due **               | 2-13                            | 1000 Hz
| 101                  | 3, 5, 6, 9                      | styki 3 i 9: 490 Hz, styki 5 i 6: 980 Hz
|====================================================================================================
{empty}* Oprócz wyżej wymienionych możliwości styków PWM, karty MKR i Zero mają prawdziwe wyjście analogowe, gdy używa się `analogWrite()` na styku `DAC0` (`A0`). +
{empty}** Oprócz wyżej wymienionych możliwości styków PWM, Due ma prawdziwe wyjście analogowe, gdy używa się `analogWrite()` na stykach `DAC0` i` DAC1`.

[%hardbreaks]

Nie trzeba wywoływać `pinMode()`, aby ustawić styk jako wyjście przed wywołaniem `analogWrite()`.
Funkcja `analogWrite` nie ma nic wspólnego ze stykami analogowymi ani funkcją`analogRead`.
[%hardbreaks]


[float]
=== Składnia
`analogWrite(styk, wartość)`


[float]
=== Parametry
`styk`: styk Arduino do zapisu. Dozwolone typy danych: `int`. +
`wartość`: wypełnienie sygnału: pomiędzy 0 (zawsze wyłączone) a 255 (zawsze włączone). Dozwolone typy danych: `int`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Ustawia jasność diody świecącej proporcjonalną do wartości odczytanej z potencjometru.


[source,arduino]
----
int stykDiody = 9;      // dioda świecąca podłączona do cyfrowego styku nr 9
int stykAnalogowy = 3;  // potencjometr podłączony do analogowego styku nr 3
int wart = 0;           // zmienna przechowująca odczytaną wartość

void setup() {
  pinMode(ledPin, OUTPUT);  // sets the pin as output
}

void loop() {
  wart = analogRead(stykAnalogowy);  // odczytaj styk wejściowy
  analogWrite(stykDiody, wart / 4);  // wartości analogRead są z zakresu od 0 do 1023, wartości analogWrite od 0 do 255
}
----
[%hardbreaks]


[float]
=== Uwagi i ostrzeżenia
Sygnały PWM generowane na stykach 5 i 6 będą miały większe niż oczekiwano wypełnienie. Wynika to z interakcji z funkcjami `millis()` i `delay()`, które współużytkują ten sam wewnętrzny zegar używany do generowania na tych wyjściach fali PWM. Będzie to zauważalne głównie przy niskich ustawieniach wypełnienia (np. 0–10) i może spowodować, że wartość 0 nie wyłączy całkowicie wyjścia na pinach 5 i 6.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]

[role="definition"]
* #DEFINITION# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
