---
title: constrain()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---

= constrain(x, a, b) (ang. ograniczenie)

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Ogranicza liczbę do określonego zakresu.
[%hardbreaks]


[float]
=== Składnia
`constrain(x, a, b)`


[float]
=== Parametry
`x`: liczba do ograniczenia. Dozwolone typy danych: wszystkie typy danych. +
`a`: dolna granica Dozwolone typy danych: wszystkie typy danych. +
`b`: górna granica. Dozwolone typy danych: wszystkie typy danych.


[float]
=== Wartości zwracane
x: jeśli x jest pomiędzy a i b. +
a: jeśli x jest mniejsze niż a. +
b: jeśli x jest większe niż b.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program ogranicza wartości z czujników do wartości z przedziału od 10 do 150.

[source,arduino]
----
wartCzuj = constrain(wartCzuj, 10, 150);  // ogranicza wartość z czujnika do wartości z przedziału od 10 do 150.
----

[float]
=== Uwagi i ostrzeżenia
Ze względu na sposób implementacji funkcji `constrain()` unikaj używania innych funkcji wewnątrz nawiasów, bp może to prowadzić do niepoprawnych wyników.

Ten kod da nieprawidłowe wyniki:
[source,arduino]
----
int ograniczoneWejscie = constrain(Serial.parseInt(), wartoscMinimalna, wartoscMaksymalna);   // unikaj tego
----

Zamiast tego użyj:
[source,arduino]
----
int wejscie = Serial.parseInt();  // inne działania wykonuj poza funkcją ograniczającą
int ograniczoneWejscie = constrain(wejscie, wartoscMinimalna, wartoscMaksymalna);
----
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
