---
title: map()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---

= map(wartosc, odNiskie, odWysokie, doNiskie, doWysokie)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Przekształca liczbę z jednego zakresu na inny. Oznacza to, że wartość *odNiskie* zostanie przekształcona w *doNiskie*, wartość *odWysokie* w *doWysokie*, odpowiednio również wartości pomiędzy nimi.

Nie ogranicza to wartości do podanego zakresu, ponieważ przekroczenie zakresu może być czasem zamierzone i przydatne. Funkcja `constrain()` może być używana przed tą funkcją lub po niej, jeśli potrzebne będzie ograniczenie zakresu.

Zauważ, że "dolne granice" zakresu mogą być większe lub mniejsze niż "górne granice", więc funkcja `map()` może być użyta do odwrócenia zakresu liczb, na przykład

`y = map(x, 1, 50, 50, 1);`

Ta funkcja również radzi sobie z liczbami ujemnymi, zatem poniższy przykład

`y = map(x, 1, 50, 50, -100);`

jest prawidłowy i działa poprawnie.

Funkcja `map()` posługuje się liczbami całkowitymi, więc nie będzie zwracać w wyniku ułamków, gdy obliczenia będą wskazywać na to, że powinna to zrobić. Części ułamkowe będą obcinane a nie zaokrąglane czy uśredniane.
[%hardbreaks]

[float]
=== Składnia
`map(wartość, odNiskie, odWysokie, doNiskie, doWysokie)`


[float]
=== Parametry
`wartość`  : liczba do przekształcenia. +
`odNiskie` : dolna granica bieżącego zakresu wartości. +
`odWysokie`: górna granica bieżącego zakresu wartości. +
`doNiskie` : dolna granica zakresu docelowego wartości. +
`doWysokie`: górna granica zakresu docelowego wartości.

[float]
=== Wartości zwracane
Przekształcona wartość.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
/* Przekształć analogową wartość na liczbę ośmiobitową (z zakresu od 0 do 255) */
void setup() {}

void loop() {
  int wart = analogRead(0);
  wart = map(wart, 0, 1023, 0, 255);
  analogWrite(9, wart);
}
----
[%hardbreaks]

[float]
=== Dodatek

Oto cała funkcja - dla miłośników matematyki, 

[source,arduino]
----
long map(long x, long wej_min, long wej_max, long wyj_min, long wyj_max) {
  return (x - wej_min) * (wyj_max - wyj_min) / (wej_max - wej_min) + wyj_min;
}
----

[float]
=== Uwagi i ostrzeżenia

Jak wspomniano wcześniej, funkcja map() wykorzystuje obliczenia na liczbach całkowitych. Z tego powodu części ułamkowe liczb mogą zostać obcięte. Na przykład ułamki takie jak 3/2, 4/3, 5/4 funkcja map() zwróci jako 1, pomimo ich różnych rzeczywistych wartości. Jeśli więc twój projekt wymaga precyzyjnych obliczeń (np. napięcie z dokładnością do 3 miejsc po przecinku), wykonaj w programie niezbędne przekształcenia bez użycia funkcji map().

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
