---
title: max()
categories: [ "Funkcje" ]
subCategories: [ "Matematyka" ]
---

= max(x, y)

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Oblicza, która z dwóch liczb jest większa.
[%hardbreaks]


[float]
=== Składnia
`max(x, y)`

[float]
=== Parametry
`x`: pierwsza liczba. Dozwolone typy danych: dowolny typ danych. +
`y`: druga liczba. Dozwolone typy danych: dowolny typ danych.

[float]
=== Wartości zwracane
Większa z wartości dwóch parametrów.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program upewnia się, że wartCzujnika wynosi co najmniej 20.

[source,arduino]
----
wartCzujnika = max(wartCzujnika, 20); // przypisuje zmiennej wartCzujnika większą z dwóch wartości: wartCzujnika lub 20
                                      // (upewniamy się, że wartość jest co najmniej równa 20)
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Być może wbrew intuicji, `max()` jest często używane do ograniczenia dolnego końca zakresu zmiennej, podczas gdy `min()` jest używane do ograniczenia górnego końca zakresu.

Ze względu na sposób implementacji funkcji max() unikaj używania innych funkcji wewnątrz nawiasów, bo może to prowadzić do niepoprawnych wyników.
[source,arduino]
----
max(a--, 0);  // unikaj tego - daje nieprawidłowe wyniki

// zamiast tego użyj:
max(a, 0);
a--;          // inne działania wykonuj poza funkcją
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
