---
title: max()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= max(x, y)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Calculates the maximum of two numbers.
[%hardbreaks]


[float]
=== Składnia
`max(x, y)`


[float]
=== Parametry
`x`: the first number. Allowed data types: any data type. +
`y`: the second number. Allowed data types: any data type.


[float]
=== Wartości zwracane
The larger of the two parameter values.

--
// KONIEC SEKCJI OPISOWEJ




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code ensures that sensVal is at least 20.

[source,arduino]
----
sensVal = max(sensVal, 20); // assigns sensVal to the larger of sensVal or 20
                            // (effectively ensuring that it is at least 20)
----
[%hardbreaks]

[float]
=== Notes and Warnings
Perhaps counter-intuitively, `max()` is often used to constrain the lower end of a variable's range, while `min()` is used to constrain the upper end of the range.

Because of the way the `max()` function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results
[source,arduino]
----
max(a--, 0);  // avoid this - yields incorrect results

// use this instead:
max(a, 0);
a--;  // keep other math outside the function
----

--
// HOW TO USE SECTION ENDS


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== See also

--
// KONIEC SEKCJI ZOBACZ TAKŻE
