---
title: min()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---

= min(x, y)

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Oblicza, która z dwóch liczb jest mniejsza.
[%hardbreaks]


[float]
=== Składnia
`min(x, y)`


[float]
=== Parametry
`x`: pierwsza liczba. Dozwolone typy danych: dowolny typ danych. +
`y`: druga liczba. Dozwolone typy danych: dowolny typ danych.


[float]
=== Wartości zwracane
Mniejsza z wartości dwóch parametrów.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program zapewnia, że nigdy nie przekroczymy wartości 100.

[source,arduino]
----
wartCzujnika = min(wartCzujnika, 100);  // przypisuje zmiennej wartCzujnika mniejszą z dwóch wartości: wartCzujnika lub 100
                                        // (upewniamy się, że wartość nigdy nie będzie większa niż 100)
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Być może wbrew intuicji, `max()` jest często używane do ograniczenia dolnego końca zakresu zmiennej, podczas gdy `min()` jest używane do ograniczenia górnego końca zakresu.

Ze względu na sposób implementacji funkcji min() unikaj używania innych funkcji wewnątrz nawiasów, bo może to prowadzić do niepoprawnych wyników.
[source,arduino]
----
min(a++, 100);  // unikaj tego - daje nieprawidłowe wyniki

// zamiast tego użyj:
min(a, 100);
a++;            // inne działania wykonuj poza funkcją
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
