---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---

= pow(podstawa, wykładnik)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Oblicza wartość liczby podniesionej do potęgi. `pow()` może być użyte do podniesienia liczby do potęgi ułamkowej. Jest to przydatne do generowania wykładniczego odwzorowania wartości lub krzywych.
[%hardbreaks]


[float]
=== Składnia
`pow(podstawa, wykładnik)`


[float]
=== Parametry
`podstawa`: liczba. Dozwolone typy danych: `float`. +
`wykładnik`: potęga, do której podniesiona jest podstawa. Dozwolone typy danych: `float`.


[float]
=== Wartości zwracane
Wynik potęgowania. Typ danych: `double`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Obliczyć wartość x podniesioną do potęgi y:
[source,arduino]
----
z = pow(x, y);
----
Zobacz bardziej złożony przykład użycia `pow()` w szkicu (http://arduino.cc/playground/Main/Fscale[fscale]).
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="definition"]
* #DEFINICJA# link:../../../variables/data-types/float[float]
* #DEFENICJA# link:../../../variables/data-types/double[double]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
