---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= pow(base, exponent)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Calculates the value of a number raised to a power. `pow()` can be used to raise a number to a fractional power. This is useful for generating exponential mapping of values or curves.
[%hardbreaks]


[float]
=== Składnia
`pow(base, exponent)`


[float]
=== Parametry
`base`: the number. Allowed data types: `float`. +
`exponent`: the power to which the base is raised. Allowed data types: `float`.


[float]
=== Wartości zwracane
The result of the exponentiation. Data type: `double`.

--
// KONIEC SEKCJI OPISOWEJ


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Calculate the value of x raised to the power of y:
[source,arduino]
----
z = pow(x, y);
----
See the (http://arduino.cc/playground/Main/Fscale[fscale]) sketch for a more complex example of the use of `pow()`.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== See also

[role="definition"]
* #DEFINITION# link:../../../variables/data-types/float[float]
* #DEFENITION# link:../../../variables/data-types/double[double]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
