---
title: const
categories: [ "Variables" ]
subCategories: [ "Variable Scope & Qualifiers" ]
---





= słowo kluczowe const (stała)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Słowo kluczowe `const` oznacza stałą. Jest to _kwalifikator_ zmiennej, który modyfikuje zachowanie zmiennej, tworząc ją "_tylko-do-odczytu_". Oznacza to, że takiej zmiennej można używać tak samo, jak każdej innej zmiennej jej typu, ale jej wartości nie można zmienić. Jeśli spróbujesz przypisać wartość do zmiennej `const` to pojawi się błąd kompilatora.

Stałe zdefiniowane za pomocą słowa kluczowego `const` przestrzegają zasad, które określają link:../scope[zasięg zmiennych] jak w przypadku innych zmiennych. To i pułapki związane z używaniem `#define`, sprawiają, że słowo kluczowe `const` jest lepszą metodą definiowania stałych i jest preferowane niż użycie link:../../../structure/further-syntax/define[`#define`].
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
const float pi = 3.14;
float x;
// ....
x = pi * 2; // dobrze jest używać stałych w obliczeniach
pi = 7;     // nielegalne - nie możesz zapisać (modyfikować) stałej
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
*`#define` czy `const`*

Do tworzenia stałych liczbowych lub tekstowych można użyć albo `const` albo `#define`. Gdy definiujesz link:../../data-types/array[tablice], będziesz musiał użyć `const`. Ogólnie rzecz biorąc, do definiowania stałych preferowany jest `const` zamiast `#define`.


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
#JĘZYK# link:../../../structure/further-syntax/define[#define] +

--
// KONIEC SEKCJI ZOBACZ TAKŻE
