---
title: zasięg
categories: [ "Zmienne" ]
subCategories: [ "Zasięg zmiennych i kwalifikatory" ]
---





= Zasięg zmiennej


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Zmienne w języku programowania C++, którego używa Arduino, mają cechę nazywaną zasięgiem. Jest to przeciwieństwo do wczesnych wersji języków, takich jak BASIC, gdzie każda zmienna jest zmienną globalną.

Zmienna globalna to taka, która jest widoczna dla każdej funkcji w programie. Zmienne lokalne są widoczne tylko w funkcji, w której zostały zadeklarowane. W środowisku Arduino każda zmienna zadeklarowana poza funkcją (np. poza funkcjami Setup() czy loop() itd.) jest zmienną globalną.

Kiedy programy stają się coraz większe i bardziej złożone, zmienne lokalne są użytecznym sposobem na zapewnienie, że tylko jedna funkcja ma dostęp do własnych zmiennych. Zapobiega to błędom w programowaniu, gdy jedna funkcja nieumyślnie modyfikuje zmienne używane przez inną funkcję.

Czasami przydaje się także deklarowanie i inicjowanie zmiennej w pętli `for`. Tworzy to zmienną, do której można uzyskać dostęp tylko z wnętrza nawiasów (klamrowych) pętli for.
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
int gPWMval;  // każda funkcja zobaczy tę zmienną

void setup() {
  // ...
}

void loop() {
  int i;    // "i" jest "widoczne" tylko w "loop"
  float f;  // "f" jest "widoczne" tylko w "loop"
  // ...

  for (int j = 0; j < 100; j++) {
    // zmienna j jest dostępna tylko wewnątrz klamrowych nawiasów pętli
  }
}
----
[%hardbreaks]


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
