---
title: volatile
categories: [ "Zmienne" ]
subCategories: [ "Zasięg zmiennych i kwalifikatory" ]
---





= Słowo kluczowe volatile


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`volatile` (ulotne) jest słowem kluczowym znanym jako _kwalifikator_ zmiennej, zwykle jest używana przed typem zmiennej, aby zmodyfikować sposób, w jaki kompilator a następnie program potraktują zmienną.

Zadeklarowanie zmiennej `volatile` jest dyrektywą dla kompilatora. Kompilator to program, które tłumaczy kod C/C++ na kod maszynowy, który jest prawdziwymi instrukcjami dla układu Atmega w Arduino.

W tym przypadku instruuje to kompilator aby ładował zmiennej z pamięci RAM, a nie z rejestru, który jest tymczasową lokalizacją pamięci, w której zmienne programu są przechowywane i przetwarzane. W pewnych sytuacjach wartość zmiennej przechowywanej w rejestrach może być niedokładna.

Zmienną należy zadeklarować jako `volatile`, ilekroć jej wartość może zostać zmieniona przez coś poza kontrolą sekcji kodu, w której się pojawia, na przykład przez jednocześnie wykonywany wątek. W Arduino jedynym miejscem, w którym może się to zdarzyć, są sekcje kodu związane z przerwaniami, zwane procedurą obsługi przerwań.

[float]
=== zmienne volatile typu int lub long
Jeśli zmienna `ulotna` jest większa niż bajt (np. całkowita 16-bitowa lub długa 32-bitowa), wówczas mikrokontroler nie może odczytać jej w jednym kroku, ponieważ jest to 8-bitowy mikrokontroler. Oznacza to, że podczas gdy główna sekcja kodu (np. loop) odczytuje pierwsze 8 bitów zmiennej, przerwanie może już zmienić drugie 8 bitów. Spowoduje to wygenerowanie losowych wartości dla zmiennej.

Lekarstwo:

Podczas odczytywania zmiennej przerwania muszą być wyłączone, aby nie mogły zepsuć bitów podczas odczytu.
Można to zrobić na kilka sposobów:

1. #LANGUAGE# link:../../../functions/interrupts/nointerrupts[noInterrupts]

2. użyj makra ATOMIC_BLOCK. Operacje atomowe to pojedyncze operacje MCU - najmniejsza możliwa jednostka.


[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
// toggles LED when interrupt pin changes state

int pin = 13;
volatile byte state = LOW;

void setup() {
  pinMode(pin, OUTPUT);
  attachInterrupt(digitalPinToInterrupt(2), blink, CHANGE);
}

void loop() {
  digitalWrite(pin, state);
}

void blink() {
  state = !state;
}
----


[source,arduino]
----
#include <util/atomic.h> // this library includes the ATOMIC_BLOCK macro.
volatile int input_from_interrupt;

  ATOMIC_BLOCK(ATOMIC_RESTORESTATE) {
    // code with interrupts blocked (consecutive atomic operations will not get interrupted)
    int result = input_from_interrupt;
  }
----



--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../../functions/external-interrupts/attachinterrupt[attachInterrupt]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
