---
title: "isAlphaNumeric()"
categories: [ "Funkcje" ]
subCategories: [ "Znaki" ]
---





= isAlphaNumeric(thisChar)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Przeanalizuj, czy znak jest alfanumeryczny (czy jest literą lub cyfrą). Zwraca true, jeśli zmienna tenZnak zawiera albo cyfrę albo literę.
[%hardbreaks]


[float]
=== Składnia
`isAlphaNumeric(tenZnak)`


[float]
=== Parametry
`tenZnak`: zmienna. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
`true`: jeżeli tenZnak jest alfanumeryczny.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
if (isAlphaNumeric(mójZnak)) { // sprawdza, czy mójZnak jest literą lub cyfrą
  Serial.println("Znak jest alfanumeryczny");
}
else {
  Serial.println("Znak nie jest alfanumeryczny");
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK#  link:../../../variables/data-types/char[znak]
* #JĘZYK#  link:../../../structure/control-structure/if[if (instrukcje warunkowe)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (instrukcje warunkowe)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
