---
title: "isGraph()"
categories: [ "Funkcje" ]
subCategories: [ "Znaki" ]
---





= isGraph(tenZnak)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Analizuje czy znak jest drukowalny z jakąkolwiek zawartością (spacja jest drukowalna ale nie ma zawartości). Zwraca prawdę jeśli tenZnak jest drukowalny.
[%hardbreaks]


[float]
=== Składnia
`isGraph(tenZnak)`

[float]
=== Parametry
`tenZnak`: zmienna. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
`true`: jeśli tenZnak jest drukowalny.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
if (isGraph(mójZnak)) {  // sprawdza czy mójZnak jest znakiem drukowalnym ale nie pustą spacją.
  Serial.println("To jest znak drukowalny");
}
else {
  Serial.println("To nie jest znak drukowalny");
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (instrukcje sterujące)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (instrukcje sterujące)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
