---
title: "isHexadecimalDigit()"
categories: [ "Funkcje" ]
subCategories: [ "Znaki" ]
---





= isHexadecimalDigit(tenZnak)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Sprawdza czy znak jest cyfrą szesnastkową (A-F, 0-9). Zwraca true jeśli tenZnak zawiera cyfrę szesnastkową.
[%hardbreaks]


[float]
=== Składnia
`isHexadecimalDigit(tenZnak)`


[float]
=== Parametry
`tenZnak`: zmienna. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
`true`: jeśli tenZnak jest cyfrą szesnastkową.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
if (isHexadecimalDigit(mojZnak)) { // testuje czy mojZnak jest cyfrą szesnastkową
  Serial.println("Znak jest cyfrą szesnastkową");
}
else {
  Serial.println("Znak nie jest cyfrą szesnastkową");
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
