---
title: "isLowerCase()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isLowerCase(tenZnak)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Sprawdza czy znak jest małą literą (tylko ze zbioru ascii - nie wykryje np. małej litery ą). Zwraca true jeśli tenZnak zawiera małą literę.
[%hardbreaks]


[float]
=== Składnia
`isLowerCase(tenZnak)`


[float]
=== Parametry
`tenZnak`: zmienna. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
`true`: jeśli tenZnak jest małą literą.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
if (isLowerCase(mojZnak)) {  // sprawdza czy mojZnak jest małą literą
  Serial.println("Znak jest małą literą");
}
else {
  Serial.println("Znak nie jest małą literą");
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
