---
title: "isPunct()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isPunct(tenZnak)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Sprawdza czy znak jest znakiem interpunkcyjnym (przecinek, średnik, wykrzyknik itd). Zwraca true jeśli tenZnak jest znakiem interpunkcyjnym.
[%hardbreaks]


[float]
=== Składnia
`isPunct(tenZnak)`


[float]
=== Parametry
`tenZnak`: zmienna. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
`true`: jeśli tenZnak jest znakiem interpunkcyjnym.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
if (isPunct(mojZnak)) {  // sprawdza czy mojZnak jest znakiem interpunkcyjnym
  Serial.println("To jest znak interpunkcyjny");
}
else {
  Serial.println("To nie jest znak interpunkcyjny");
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
