---
title: "isSpace()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isSpace(tenZnak)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Sprawdza czy znak jest znakiem niedrukowalnym. Zwraca true jeśli argument to odstęp (spacja), wysuw strony (ang.form feed) (`'\f'`), nowa linia (`'\n'`), powrót do początku linii (`'\r'`), tabulator poziomy (`'\t'`), or tabulator pionowy (`'\v'`).
[%hardbreaks]


[float]
=== Składnia
`isSpace(tenZnak)`


[float]
=== Parametry
`tenZnak`: zmienna. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
`true`: jeśli tenZnak jest znakiem niedrukowalnym.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
if (isSpace(mojZnak)) {  // sprawdza czy mojZnak jest znakiem niedrukowalnym
  Serial.println("To jest znak niedrukowalny");
}
else {
  Serial.println("To nie jest znak niedrukowalny");
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
