---
title: "isUpperCase()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---

= isUpperCase(tenZnak)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Spradza czy znak jest wielką literą (tylko ze zbioru ascii - nie wykryje np. wielkiej litery Ą). Zwraca true jeśli tenZnak jest wielką literą. 
[%hardbreaks]


[float]
=== Składnia
`isUpperCase(tenZnak)`


[float]
=== Parametry
`tenZnak`: zmienna. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
`true`: jeśli tenZnak jest wielką literą.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
if (isUpperCase(mojZnak)) {  // sprawdza czy mojZnak jest wielką literą
  Serial.println("Znak jest wielką literą");
}
else {
  Serial.println("Znak nie jest wielką literą");
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
