---
title: "&"
title_expanded: operator pobrania adresu
categories: [ "Struktura" ]
subCategories: [ "Operatory wskaźnikowe" ]
---





= & Operator pobrania adresu


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Jednym ze sposobów użycia wskaźników jest adresowanie. Do tego celu stosuje się operator oznaczony znakiem ampersand `&`. Jeżeli `x` jest zmienną, to wtedy `&x` wyraża adres zmiennej `x`.
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
int *p;       // deklaruje wskaźnik do danych typu int
int i = 5;
int wynik = 0;
p = &i;       // teraz 'p' zawiera adres zmiennej 'i'
wynik = *p;   // 'wynik' pobiera wartość spod adresu wskazywanego przez 'p'
              // tzn. pobiera wartość 'i', która wynosi 5
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Wskaźniki są jednym z bardziej skomplikowanych tematów dla początkujących w nauce języka C i możliwe jest napisanie ogromnej większości szkiców dla Arduino bez wykorzystania wskaźników. Jednak do manipulowania pewnymi strukturami danych użycie wskaźników może uprościć kod, a znajomość manipulowania wskaźnikami może być przydatne.
[%hardbreaks]


--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]

[role="definition"]
* #DEFINICJA#  https://en.wikipedia.org/wiki/Pointer_%28computer_programming%29[Wskaźniki^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
