---
title: "^="
title_expanded: złożone bitowe ALBO
categories: [ "Struktura" ]
subCategories: [ "Operatory złożone" ]
---

= ^= Złożone bitowe ALBO


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Operator złożonego bitowego ALBO (ang. XOR) `^=` jest często używany do przełączania (odwracania) określonych bitów w zmiennej.
[%hardbreaks]

Działanie operatora bitowego ALBO `^`:

   0  0  1  1    argument1
   0  1  0  1    argument2
   ----------
   0  1  1  0    (argument1 ^ argument2) - zwracany wynik
[%hardbreaks]

[float]
=== Składnia
`x ^= y;         // odpowiednik wyrażenia x = x ^ y;`


[float]
=== Parametry
`x`: zmienna. Dozwolone typy danych: `char`, `int`, `long`. +
`y`: zmienna lub stała. Dozwolone typy danych: `char`, `int`, `long`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Bity, które są "odwracane bitowo" zerami pozostają niezmienione. więc jeśli mójBajt jest zmienną typu byte,
[source,arduino]
----
mójBajt ^ B00000000 = mójBajt;
----

Bity, które są "odwracane bitowo" jedynkami są przełączane w stan przeciwny:
[source,arduino]
----
mójBajt ^ B11111111 = ~mójBajt;
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Podczas operowania bitami - wygodnie jest korzystać z dwójkowego przedstawiania stałych. Liczby mają taką samą wartość jak w innych sposobach przestawienia ale są łatwiejsze do zrozumienia. Również B00000000 jest pokazane dla przejrzystości, ale zero w dowolnym formacie to nadal zero.
[%hardbreaks]

Więc aby w zmiennej odwrócić stan bitów 0 i 1, pozostawiając niezmienioną resztę bitów, użyj złożonego operatora bitowego ALBO (^=) ze stałą B00000011

   1  0  1  0  1  0  1  0    zmienna
   0  0  0  0  0  0  1  1    maska
   ----------------------
   1  0  1  0  1  0  0  1

    bity niezmienione
                     bity odwrócone


Tutaj przedstawione to samo z biltami zmiennej zastąpionymi symbolami x. ~x oznacza zaprzeczenie x (czyli "nie x").

   x  x  x  x  x  x  x  x    zmienna
   0  0  0  0  0  0  1  1    maska
   ----------------------
   x  x  x  x  x  x ~x ~x

    bity niezmienione
                     bity odwrócone

Inaczej:
[source,arduino]
----
mójBajt = B10101010;
mójBajt ^= B00000011 == B10101001;
----

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwisexor[^ bitowe ALBO]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
