---
title: "%="
title_expanded: reszta złożona
categories: [ "Structure" ]
subCategories: [ "Compound Operators" ]
---





= %= Reszta złożona


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Jest to wygodny skrót do obliczenia reszty, gdy jedna liczba całkowita jest podzielona przez inną i przypisana z powrotem do zmiennej, na której dokonano obliczenia.
[%hardbreaks]


[float]
=== Składnia
`x %= dzielnik;   // odpowiednik wyrażenia x = x % dzielnik;`


[float]
=== Parametry
`x`: zmienna. Dozwolone typy danych: `int`. +
`dzielnik`: *niezerowa* zmienna lub stała. Dozwolone typy danych: `int`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
int x = 7;
x %= 5;        // x przyjmie wartość 2
----
[%hardbreaks]

[float]
=== Uwagi i Ostrzeżenia
1. Złożony operator reszty nie działa na liczbach zmiennoprzecinkowych.

2. Jeżeli *pierwszy* argument jest ujemny to wynik będzie ujemny (lub zerowy).
Dlatego wynik działania `x %= 10` nie zawsze będzie wynosił od 0 do 9, bo `x` może być ujemne.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ



// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK#  link:../../arithmetic-operators/remainder[reszta]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
