---
title: "&="
title_expanded: złożone bitowe I
categories: [ "Struktura" ]
subCategories: [ "Operatory złożone" ]
---





= &= Złożone bitowe I


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Złożony operator bitowy I `&=` jest często używany do wymuszania poszczególnych bitów w zmiennej do stanu LOW (do 0). Jest to często określane w przewodnikach programowania jako "czyszczenie" lub "resetowanie" bitów.
[%hardbreaks]

Działanie operatora bitowego I `&`:

   0  0  1  1    argument1
   0  1  0  1    argument2
   ----------
   0  0  0  1    (argument1 & argument2) - zwracany wynik
[%hardbreaks]

[float]
=== Składnia
`x &= y;       // odpowiednik wyrażenia x = x & y;`


[float]
=== Parametry
`x`: zmienna. Dozwolone typy danych: `char`, `int`, `long`. +
`y`: zmienna lub stała. Dozwolone typy danych: `char`, `int`, `long`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Bity, które są "dodawane bitowo" do 0 są ustawiane na , jeśli mojBajt jest zmienną typu byte,

[source,arduino]
----
mojBajt & B00000000 = 0;
----

Bity, które są "dodawane bitowo" do 1 są niezmieniane,

[source,arduino]
----
mojBajt & B11111111 = mojBajt;
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Podczas operowania bitami - wygodnie jest korzystać z dwójkowego przedstawiania stałych. Liczby mają taką samą wartość jak w innych sposobach przestawienia ale są łatwiejsze do zrozumienia. Również B00000000 jest pokazane dla przejrzystości, ale zero w dowolnym formacie to nadal zero (hmmm czy to jakaś filozofia?)

Więc aby wyczyścić (ustawić na zero) w zmiennej bity 0 i 1, pozostawiając niezmienioną resztę bitów, użyj złożonego operatora bitowego I (&=) ze stałą B11111100

   1  0  1  0  1  0  1  0    zmienna
   1  1  1  1  1  1  0  0    maska
   ----------------------
   1  0  1  0  1  0  0  0

    bity niezmienione
                     bity wyczyszczone

Tutaj przedstawione to samo z biltami zmiennej zastąpionymi symbolami x

   x  x  x  x  x  x  x  x    zmienna
   1  1  1  1  1  1  0  0    maska
   ----------------------
   x  x  x  x  x  x  0  0

    bity niezmienione
                     bity wyczyszczone

Inaczej:

[source,arduino]
----
mojBajt = B10101010;
mojBajt &= B11111100;  // mojBajt przyjmie wartość B10101000
----

[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwiseand[& Bitwise AND]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
