---
title: "|="
title_expanded: złożone bitowe LUB
categories: [ "Structure" ]
subCategories: [ "Compound Operators" ]
---

= |= Złożone bitowe LUB


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Złożony operator bitowego LUB (ang.OR) `|=` jest często używany do "ustawiania" (nadania wartości 1) poszczególnych bitów w zmiennej.
[%hardbreaks]

Działanie operatora bitowego LUB `|`:

   0  0  1  1    argument1
   0  1  0  1    argument2
   ----------
   0  1  1  1    (argument1 | argument2) - zwracany wynik
[%hardbreaks]

[float]
=== Składnia
`x |= y;         // odpowiednik wyrażenia x = x | y;`


[float]
=== Parametry
`x`: zmienna. Dozwolone typy danych: `char`, `int`, `long`. +
`y`: zmienna lub stała. Dozwolone typy danych: `char`, `int`, `long`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Bity, które są "dodawane bitowo" do 0 pozostają niezmienione, więc jeśli mójBajt jest zmienną typy byte,
[source,arduino]
----
mójBajt | B00000000 = mójBajt;
----

Bity, które są "dodawane bitowo" do 1 są ustawiane na 1 więc:
[source,arduino]
----
mójBajt | B11111111 = B11111111;
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Podczas operowania bitami - wygodnie jest korzystać z dwójkowego przedstawiania stałych. Liczby mają taką samą wartość jak w innych sposobach przestawienia ale są łatwiejsze do zrozumienia. Również B00000000 jest pokazane dla przejrzystości, ale zero w dowolnym formacie to nadal zero.
[%hardbreaks]

Więc aby ustawić (zmienić na jeden) w zmiennej bity 0 i 1, pozostawiając niezmienioną resztę bitów, użyj złożonego operatora bitowego LUB (|=) ze stałą B00000011

   1  0  1  0  1  0  1  0    zmienna
   0  0  0  0  0  0  1  1    maska
   ----------------------
   1  0  1  0  1  0  1  1

    bity niezmienione
                     bity ustawione


Tutaj przedstawione to samo z biltami zmiennej zastąpionymi symbolami x

   x  x  x  x  x  x  x  x    zmienna
   0  0  0  0  0  0  1  1    maska
   ----------------------
   x  x  x  x  x  x  1  1

    bity niezmienione
                     bity ustawione

Inaczej:
[source,arduino]
----
mójBajt = B10101010;
mójBajt |= B00000011 == B10101011;
----

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwiseor[| bitowe LUB]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
