---
title: "^="
title_expanded: compound bitwise xor
categories: [ "Structure" ]
subCategories: [ "Compound Operators" ]
---

= ^= Compound Bitwise XOR


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
The compound bitwise XOR operator `^=` is often used with a variable and a constant to toggle (invert) particular bits in a variable.
[%hardbreaks]

A review of the Bitwise XOR `^` operator:

   0  0  1  1    operand1
   0  1  0  1    operand2
   ----------
   0  1  1  0    (operand1 ^ operand2) - returned result
[%hardbreaks]

[float]
=== Składnia
`x ^= y; // equivalent to x = x ^ y;`


[float]
=== Parameters
`x`: variable. Allowed data types: `char`, `int`, `long`. +
`y`: variable or constant. Allowed data types: `char`, `int`, `long`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Bits that are "bitwise XORed" with 0 are left unchanged. So if myByte is a byte variable,
[source,arduino]
----
myByte ^ B00000000 = myByte;
----

Bits that are "bitwise XORed" with 1 are toggled so:
[source,arduino]
----
myByte ^ B11111111 = ~myByte;
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Because we are dealing with bits in a bitwise operator - it is convenient to use the binary formatter with constants. The numbers are still the same value in other representations, they are just not as easy to understand. Also, B00000000 is shown for clarity, but zero in any number format is zero.
[%hardbreaks]

Consequently - to toggle bits 0 & 1 of a variable, while leaving the rest of the variable unchanged, use the compound bitwise XOR operator (^=) with the constant B00000011

   1  0  1  0  1  0  1  0    variable
   0  0  0  0  0  0  1  1    mask
   ----------------------
   1  0  1  0  1  0  0  1

    bits unchanged
                     bits toggled


Here is the same representation with the variables bits replaced with the symbol x. ~x represents the complement of x.

   x  x  x  x  x  x  x  x    variable
   0  0  0  0  0  0  1  1    mask
   ----------------------
   x  x  x  x  x  x ~x ~x

    bits unchanged
                     bits set

So if:
[source,arduino]
----
myByte = B10101010;
myByte ^= B00000011 == B10101001;
----

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwisexor[^ Bitwise XOR]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
