---
title: "&="
title_expanded: złożone bitowe I
categories: [ "Struktura" ]
subCategories: [ "operatory złożone" ]
---





= &= Złożone bitowe I


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Złożony operator bitowy I `&=` jest często używany do wymuszania poszczególnych bitów w zmiennej do stanu LOW (do 0). Jest to często określane w przewodnikach programowania jako "czyszczenie" lub "resetowanie" bitów.
[%hardbreaks]

Działanie operatora bitowego I `&`:

   0  0  1  1    argument1
   0  1  0  1    argument2
   ----------
   0  0  0  1    (argument1 & argument2) - zwracany wynik
[%hardbreaks]

[float]
=== Składnia
`x &= y;       // odpowiednik x = x & y;`


[float]
=== Parametry
`x`: zmienna. Allowed data types: `char`, `int`, `long`. +
`y`: variable or constant. Allowed data types: `char`, `int`, `long`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Bits that are "bitwise ANDed" with 0 are cleared to 0 so, if myByte is a byte variable,

[source,arduino]
----
myByte & B00000000 = 0;
----

Bits that are "bitwise ANDed" with 1 are unchanged so,

[source,arduino]
----
myByte & B11111111 = myByte;
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Because we are dealing with bits in a bitwise operator - it is convenient to use the binary formatter with constants. The numbers are still the same value in other representations, they are just not as easy to understand. Also, B00000000 is shown for clarity, but zero in any number format is zero (hmmm something philosophical there?)

Consequently - to clear (set to zero) bits 0 & 1 of a variable, while leaving the rest of the variable unchanged, use the compound bitwise AND operator (&=) with the constant B11111100

   1  0  1  0  1  0  1  0    variable
   1  1  1  1  1  1  0  0    mask
   ----------------------
   1  0  1  0  1  0  0  0

    bits unchanged
                     bits cleared

Here is the same representation with the variable's bits replaced with the symbol x

   x  x  x  x  x  x  x  x    variable
   1  1  1  1  1  1  0  0    mask
   ----------------------
   x  x  x  x  x  x  0  0

    bits unchanged
                     bits cleared

So if:

[source,arduino]
----
myByte = B10101010;
myByte &= B11111100;  // results in B10101000
----

[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwiseand[& Bitwise AND]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
