---
title: "^="
title_expanded: złożone bitowe ALBO
categories: [ "Struktura" ]
subCategories: [ "Operatory złożone" ]
---

= ^= Złożone bitowe ALBO


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Operator złożonego bitowego ALBO (ang. XOR) `^=` jest często używany ze zmienną i stałą do przełączania (odwracania) określonych bitów w zmiennej.
[%hardbreaks]

Jak działa operator bitowego ALBO `^`:

   0  0  1  1    argument1
   0  1  0  1    argument2
   ----------
   0  1  1  0    (argument1 ^ argument2) - zwracany wynik
[%hardbreaks]

[float]
=== Składnia
`x ^= y; // odpowiednik wyrażenia x = x ^ y;`


[float]
=== Parametry
`x`: zmienna. Allowed data types: `char`, `int`, `long`. +
`y`: zmienna lub stała. Allowed data types: `char`, `int`, `long`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Bits that are "bitwise XORed" with 0 are left unchanged. So if myByte is a byte variable,
[source,arduino]
----
myByte ^ B00000000 = myByte;
----

Bits that are "bitwise XORed" with 1 are toggled so:
[source,arduino]
----
myByte ^ B11111111 = ~myByte;
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Because we are dealing with bits in a bitwise operator - it is convenient to use the binary formatter with constants. The numbers are still the same value in other representations, they are just not as easy to understand. Also, B00000000 is shown for clarity, but zero in any number format is zero.
[%hardbreaks]

Consequently - to toggle bits 0 & 1 of a variable, while leaving the rest of the variable unchanged, use the compound bitwise XOR operator (^=) with the constant B00000011

   1  0  1  0  1  0  1  0    variable
   0  0  0  0  0  0  1  1    mask
   ----------------------
   1  0  1  0  1  0  0  1

    bits unchanged
                     bits toggled


Here is the same representation with the variables bits replaced with the symbol x. ~x represents the complement of x.

   x  x  x  x  x  x  x  x    variable
   0  0  0  0  0  0  1  1    mask
   ----------------------
   x  x  x  x  x  x ~x ~x

    bits unchanged
                     bits set

So if:
[source,arduino]
----
myByte = B10101010;
myByte ^= B00000011 == B10101001;
----

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwisexor[^ Bitwise XOR]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
