---
title: interrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---

= interrupts()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Ponownie włącza przerwania (po ich wyłączeniu przez link:../nointerrupts[nointerrupts()]. Przerwania pozwalają na wykonywanie niektórych ważnych zadań w tle i są domyślnie włączone. Niektóre funkcje nie będą działać, gdy przerwania są wyłączone, a komunikacja przychodząca może zostać zignorowana. Przerwania mogą jednak nieco zakłócać synchronizację kodu i mogą być wyłączone dla szczególnie krytycznych sekcji kodu.
[%hardbreaks]


[float]
=== Składnia
`interrupts()`


[float]
=== Parametry
Brak


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Zezwolenie na przerwania.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // tutaj instrukcje zależne od upływu czasu
  interrupts();
  // pozostałe instrukcje
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
#JĘZYK# link:../../external-interrupts/attachinterrupt[attachInterrupts()] +
#JĘZYK# link:../../external-interrupts/detachinterrupt[detachInterrupts()] +

--
// KONIEC SEKCJI ZOBACZ TAKŻE
