---
title: noInterrupts()
categories: [ "Funkcje" ]
subCategories: [ "Przerwania" ]
---

= noInterrupts()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wyłącza przerwania (możesz je ponownie włączyć za pomocą `interrupts()`). Przerwania pozwalają na wykonywanie niektórych ważnych zadań w tle i są domyślnie włączone. Niektóre funkcje nie będą działać, gdy przerwania są wyłączone, a komunikacja przychodząca może zostać zignorowana. Przerwania mogą jednak nieco zakłócać synchronizację kodu i mogą być wyłączone dla szczególnie krytycznych sekcji kodu.
[%hardbreaks]


[float]
=== Składnia
`noInterrupts()`


[float]
=== Parametry
Nic


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program pokazuje jak zabronić przerwań a następnie zezwolić na przerwania.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // tutaj instrukcje zależne od upływu czasu
  interrupts();
  // pozostałe instrukcje
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
