---
title: random()
categories: [ "Funkcje" ]
subCategories: [ "Liczby losowe" ]
---





= random()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Funkcja losowa generuje liczby pseudolosowe.
[%hardbreaks]


[float]
=== Składnia
`random(max)` +
`random(min, max)`


[float]
=== Parametry
`min`: dolna granica wartości losowej, włącznie (opcjonalnie). +
`max`: górna granica wartości losowej, wyłącznie.


[float]
=== Wartości zwracane
Liczba losowa pomiędzy min a max-1. Typ danych: `long`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program generuje liczby losowe i je wyświetla.

[source,arduino]
----
long liczbaLosowa;

void setup() {
  Serial.begin(9600);

  // jeżeli analogowe wejście nr 0 nie będzie podłączone,
  // losowy szum spowoduje, że wywołanie randomSeed()
  // wygeneruje różne liczby 'zarodków generatora' za każdym razem, gdy szkic zostanie uruchomiony.
  // Następnie randomSeed() przetasuje funkcję losową.
  randomSeed(analogRead(0));
}

void loop() {
  // drukuje liczbę losową z zakresu 0 do 299
  liczbaLosowa = random(300);
  Serial.println(liczbaLosowa);

  // drukuje liczbę losową z zakresu 10 do 19
  liczbaLosowa = random(10, 20);
  Serial.println(liczbaLosowa);

  delay(50);
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Jeśli ważne jest, aby sekwencja wartości generowanych przez `random()` różniła się, przy kolejnych wykonaniach szkicu użyj randomSeed(), aby zainicjować generator liczb losowych za pomocą dość losowego wejścia, takiego jak `analogRead()` na niepodłączonym styku.

I odwrotnie, czasami przydatne może być użycie pseudolosowych sekwencji, które dokładnie się powtarzają. Można to osiągnąć przez wywołanie `randomSeed()` z konkretną liczbą, przed rozpoczęciem losowej sekwencji.

Parametr `max` należy wybrać zgodnie z typem danych zmiennej, w której będzie przechowywana wylosowana wartość. W każdym razie bezwzględne maksimum jest związane z `długą` naturą generowanej wartości (32 bity - 2 147 483 647). Ustawienie wyższej wartości `max` nie spowoduje błędu podczas kompilacji, ale podczas wykonywania szkicu wygenerowane liczby nie będą zgodne z oczekiwaniami.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
