---
title: randomSeed()
categories: [ "Functions" ]
subCategories: [ "Random Numbers" ]
---





= randomSeed(seed)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`randomSeed()` inicjuje generator liczb pseudolosowych, powodując, że zaczyna się w dowolnym punkcie swojej losowej sekwencji. Ta sekwencja, choć bardzo długa i losowa, jest zawsze taka sama.

Jeśli ważne jest, aby sekwencja wartości generowanych przez `random()` różniła się, przy kolejnych wykonaniach szkicu użyj randomSeed(), aby zainicjować generator liczb losowych za pomocą dość losowego wejścia, takiego jak `analogRead()` na niepodłączonym styku.

I odwrotnie, czasami przydatne może być użycie pseudolosowych sekwencji, które dokładnie się powtarzają. Można to osiągnąć przez wywołanie `randomSeed()` z konkretną liczbą, przed rozpoczęciem losowej sekwencji.
[%hardbreaks]


[float]
=== Składnia
`randomSeed(ziarno)`


[float]
=== Parametry
`ziarno`: liczba inicjująca sekwencję pseudolosową. Dozwolone typy danych: `unsigned long`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program generuje liczbę pseudolosową i wysyła ją do portu szeregowego.

[source,arduino]
----
long liczbaLosowa;

void setup() {
  Serial.begin(9600);
  randomSeed(analogRead(0));
}

void loop() {
  liczbaLosowa = random(300);
  Serial.println(liczbaLosowa);
  delay(50);
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
