---
title: "c_str()"
categories: [ "Typy danych" ]
subCategories: [ "Funkcja objektu String" ]
---





= c_str()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Konwertuje zawartość ciągu na format w stylu języka C, zakończonego znakiem o kodzie 0. Zauważ, że daje to bezpośredni dostęp do wewnętrznego bufora String i należy tego używać ostrożnie. W szczególności nigdy nie należy modyfikować ciągu poprzez zwracany wskaźnik. Po zmodyfikowaniu obiektu String lub po jego zniszczeniu dowolny wskaźnik poprzednio zwrócony przez c_str () staje się nieprawidłowy i nie powinien być dłużej używany.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.c_str()`


[float]
=== Parametry
`mójŁańcuch`: zmienna typu `String`.


[float]
=== Wartości zwracane
Wskaźnik odwołania się do łańcucha w stylu języka C.

--
// KONIEC SEKCJI OPISOWEJ



// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
