---
title: "compareTo()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= compareTo()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Porównuje dwa ciągi, sprawdzając, czy jeden występuje przed, czy po drugim, czy też są równe. Ciągi znaków są porównywane znak po znaku, przy użyciu wartości ASCII znaków. Oznacza to na przykład, że 'a' występuje przed 'b', ale po 'A'. Liczby pojawiają się przed literami.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.compareTo(mójŁańcuch2)`


[float]
=== Parametry
`mójŁańcuch`: zmienna typu `String`. +
`mójŁańcuch2`: inna zmienna typu `String`.


[float]
=== Wartości zwracane
`liczba ujemna`: jeśli mójŁańcuch jest przed mójŁańcuch2. +
`0`: jeśli mójŁańcuch jest równy mójŁańcuch2. +
`liczba dodatnia`: jeśli mójŁańcuch jest za mójŁańcuch2.

--

// KONIEC SEKCJI OPISOWEJ



// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
