---
title: "lastIndexOf()"
categories: [ "Typy danych" ]
subCategories: [ "Funkcja objektu String" ]
---





= lastIndexOf()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Lokalizuje znak lub ciąg w innym ciągu. Domyślnie wyszukiwanie zaczyna się od końca ciągu, ale mogą również działać od podanego miejsca wstecz, umożliwiając zlokalizowanie wszystkich wystąpień znaku lub ciągu.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.lastIndexOf(wart)` +
`mójŁańcuch.lastIndexOf(wart, od)`


[float]
=== Parametry
`mójŁańcuch`: zmienna typu `String`. +
`wart`: poszukiwana wartość. Dozwolone typy danych: `char`, `String`. +
`od`: miejsce od którego rozpocznie się wyszukiwanie wstecz.


[float]
=== Wartości zwracane
Pozycja w ciągu na której znaleziona została wartość, lub -1 jeśli jej nie znaleziono.

--
// KONIEC SEKCJI OPISOWEJ



// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
