---
title: "remove()"
categories: [ "Typy danych" ]
subCategories: [ "Funkcja objektu String" ]
---





= remove()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Modify in place a String removing chars from the provided index to the end of the String or from the provided index to index plus count.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.remove(index)` +
`mójŁańcuch.remove(index, count)`


[float]
=== Parametry
`mójŁańcuch`: a variable of type `String`. +
`index`: The position at which to start the remove process (zero indexed). Allowed data types: `unsigned int`. +
`count`: The number of characters to remove. Allowed data types: `unsigned int`.


[float]
=== Wartości zwracane
Nothing

--
// KONIEC SEKCJI OPISOWEJ


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[source,arduino]
----
String greeting = "hello";
greeting.remove(2, 2);  // greeting now contains "heo"
----
[%hardbreaks]
--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
