---
title: "substring()"
categories: [ "Typy danych" ]
subCategories: [ "Funkcja objektu String" ]
---





= substring()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Get a substring of a String. The starting index is inclusive (the corresponding character is included in the substring), but the optional ending index is exclusive (the corresponding character is not included in the substring). If the ending index is omitted, the substring continues to the end of the String.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.substring(from)` +
`mójŁańcuch.substring(from, to)`


[float]
=== Parametry
`mójŁańcuch`: a variable of type `String`. +
`from`: the index to start the substring at. +
`to` (optional): the index to end the substring before.


[float]
=== Wartości zwracane
The substring.

--
// KONIEC SEKCJI OPISOWEJ



// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
