---
title: "substring()"
categories: [ "Typy danych" ]
subCategories: [ "Funkcja obiektu String" ]
---





= substring()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Pobiera fragment ciągu. Znak z pozycji początkowej jest pobierany do ciągu, a znak z opcjonalej końcowej pozycji już nie. Jeśli nie zostanie podana pozycja końcowa fragment będzie pobrany aż do końca ciągu.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.substring(początek)` +
`mójŁańcuch.substring(początek, koniec)`


[float]
=== Parametry
`mójŁańcuch`: zmienna tyou `String`. +
`początek`: pozycja początkowa fragmentu. +
`koniec` (opcjonalny): pozycja, przed którą kończy się fragment.


[float]
=== Wartości zwracane
Fragment ciągu.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
[source,arduino]
----

// kod
// kod

----
[%hardbreaks]
--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
