---
title: "toFloat()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= toFloat()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Konwertuje prawidłowy ciąg znaków na liczbę zmiennoprzecinkową. Łańcuch wejściowy powinien zaczynać się cyfrą. Jeśli ciąg zawiera znaki inne niż cyfry, funkcja przerywa w tym miejscu wykonywanie konwersji. Na przykład ciągi "123.45", "123" i "123fish" są konwertowane odpowiednio na 123,45, 123,00 i 123,00. Pamiętaj, że "123.456" jest przybliżane do 123.46. Zauważ też, że precyzja liczb zmiennoprzecinkowych to tylko 6-7 cyfr i że dłuższe łańcuchy mogą zostać obcięte.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.toFloat()`


[float]
=== Parametry
`mójŁańcuch`: zmienna typu `String`.


[float]
=== Wartości zwracane
Jeśli nie można wykonać prawidłowej konwersji, ponieważ ciąg nie zaczyna się od cyfry, zwracane jest zero. Typ danych: `float`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
[source,arduino]
----

// kod
// kod

----
[%hardbreaks]
--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
