---
title: "toInt()"
categories: [ "Typy danych" ]
subCategories: [ "Funkcja objektu String" ]
---





= toInt()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Konwertuje prawidłowy ciąg znaków na liczbę całkowitą. Łańcuch wejściowy powinien zaczynać się od liczby całkowitej. Jeśli ciąg nie zawiera liczby całkowitej, funkcja przestanie wykonywać konwersję.

[%hardbreaks]


[float]
=== Składnia
`mójŁańcuch.toInt()`


[float]
=== Parametry
`mójŁańcuch`: zmienna typu `String`.


[float]
=== Wartości zwracane
Jeśli nie można wykonać prawidłowej konwersji, ponieważ ciąg nie zaczyna się od liczby całkowitej, zwracane jest zero. Typ danych: `long`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Poniżej dodaj przykładowy kod i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
[source,arduino]
----

// kod
// kod

----
[%hardbreaks]
--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// KONIEC SEKCJI ZOBACZ TAKŻE
