---
title: Keyboard.write()
---




= Keyboard.write()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wysyła naciśnięcie klawisza do podłączonego komputera. Jest to podobne do naciskania i zwalniania klawisza na klawiaturze. Możesz wysłać kilka znaków ASCII lub dodatkowe link:../keyboardmodifiers[klawisze modyfikujące i specjalne].

Obsługiwane są tylko znaki ASCII, które znajdują się na klawiaturze. Na przykład ASCII 8 (backspace) zadziała, ale ASCII 26 (podstawienie) nie. Podczas wysyłania wielkich liter, `Keyboard.write()` wysyła klawisz shift plus żądany znak, tak jak przy pisaniu na klawiaturze. Gdy wysyłany jest typ numeryczny, wysyła go jako znak ASCII (np. Keyboard.write(97) wyśle 'a').

Aby uzyskać pełną listę znaków ASCII, zobacz http://www.asciitable.com/[ASCIITable.com].
[%hardbreaks]


[float]
=== Składnia
`Keyboard.write(znak)`


[float]
=== Parametry
`znak`: char lub liczba całkowita do wysłania do komputera. Można wysłać w dowolnej notacji, która jest akceptowalna dla znaku. Na przykład wszystkie poniższe są dopuszczalne i wysyłają tę samą wartość, 65 lub ASCII A:
[source,arduino]
----
Keyboard.write(65);         // przesyła wartość ASCII 65, lub A
Keyboard.write('A');        // to samo, co znak w cudzysłowie
Keyboard.write(0x41);       // to samo szesnastkowo
Keyboard.write(0b01000001); // to samo dwójkowo (dziwny wybór, ale działa)
----


[float]
=== Wartości zwracane
Liczba przesłanych bajtów. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
#include <Keyboard.h>

void setup() {
  // ustaw styk 2 jako wejście i włącz
  // rezystor podciągający do stanu wysokiego, chyba
  // że jest podłączony do masy:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  // jeśli przycisk jest wciśnięty
  if (digitalRead(2) == LOW) {
    // Wysyła znak ASCII 'A',
    Keyboard.write(65);
  }
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Kiedy używasz polecenia `Keyboard.write()`, Arduino przejmuje twoją klawiaturę! Upewnij się, że masz nad tym kontrolę, zanim użyjesz tego polecenia. Może być przydatny klawisz przełączający kontrolę nad klawiaturą.

--
// KONIEC SEKCJI JAK UŻYWAĆ
