---
title: Keyboard.press()
---




= Keyboard.press()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Po wywołaniu, `Keyboard.press()` działa tak, jakby klawisz na klawiaturze został wciśnięty i przytrzymany. Przydatne podczas używania link:../keyboardmodifiers[klawiszy modyfikujących]. Aby zakończyć naciśnięcie klawisza, użyj link:../keyboardrelease[Keyboard.release()] lub link:../keyboardreleaseall[Keyboard.releaseAll()].

Przed użyciem `press()` konieczne jest wywołanie link:../keyboardbegin[Keyboard.begin()].
[%hardbreaks]


[float]
=== Składnia
`Keyboard.press(klawisz)`


[float]
=== Parametry
`klawisz`: klawisz do naciśnięcia. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
Liczba wysłanych naciśnięć klawiszy. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
#include <Keyboard.h>

// użyj tej opcji dla OSX:
//char ctrlKey = KEY_LEFT_GUI;
// użyj tej opcji dla Windows i Linux:
char ctrlKey = KEY_LEFT_CTRL;

void setup() {
  // ustaw styk 2 jako wejście i włącz
  // rezystor podciągający do stanu wysokiego, chyba
  // że jest podłączony do masy:
  pinMode(2, INPUT_PULLUP);
  // zainicjuj kontrolę nad klawiaturą:
  Keyboard.begin();
}

void loop() {
  while (digitalRead(2) == HIGH) {
    // nic nie rób, dopóki styk 2 nie będzie w stanie niskim
    delay(500);
  }
  delay(1000);
  // nowy dokument:
  Keyboard.press(ctrlKey);
  Keyboard.press('n');
  delay(100);
  Keyboard.releaseAll();
  // poczekaj na otwarcie nowego okna:
  delay(1000);
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ
