---
title: Keyboard.println()
---




= Keyboard.println()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wysyła do podłączonego komputera naciśnięcie klawisza, po którym następuje znak nowej linii i powrót karetki.

`Keyboard.println()` musi być wywołany po zainicjowaniu link:../keyboardbegin[Keyboard.begin()].
[%hardbreaks]


[float]
=== Składnia
`Keyboard.println()` +
`Keyboard.println(znak)`+
`Keyboard.println(znaki)`


[float]
=== Parametry
`znak`: znak lub liczba całkowita do wysłania do komputera jako naciśnięcie klawisza, a następnie znak nowej linii i powrót karetki. +
`znaki`: ciąg, który ma zostać wysłany do komputera jako naciśnięcie klawisza, po którym następuje znak nowej linii i powrót karetki.


[float]
=== Wartości zwracane
Liczba przesłanych bajtów. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
#include <Keyboard.h>

void setup() {
  // ustaw styk 2 jako wejście i włącz
  // rezystor podciągający do stanu wysokiego, chyba
  // że jest podłączony do masy:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  // jeśli przycisk jest wciśnięty
  if (digitalRead(2) == LOW) {
    // Wyślij komunikat
    Keyboard.println("Serwus!");
  }
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Kiedy używasz polecenia `Keyboard.println()`, Arduino przejmuje twoją klawiaturę! Upewnij się, że masz nad tym kontrolę, zanim użyjesz tego polecenia. Może być przydatny klawisz przełączający kontrolę nad klawiaturą.

--
// KONIEC SEKCJI JAK UŻYWAĆ
