---
title: attachInterrupt()
categories: [ "Functions" ]
subCategories: [ "External Interrupts" ]
---

= attachInterrupt()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
*Styki cyfrowe obsługujące przerwania*

Pierwszy parametr funkcji `attachInterrupt()` to numer przerwania. Zwykle powinieneś użyć `digitalPinToInterrupt (pin)`, aby przetłumaczyć rzeczywisty styk cyfrowy na konkretny numer przerwania. Na przykład, jeśli podłączasz się do styku 3, użyj `digitalPinToInterrupt (3)` jako pierwszego parametru do `attachInterrupt ()`.

[options="header"]
|===================================================
|Płytka                              |Styki cyfrowe używane do obsługi przerwań
|Uno, Nano, Mini, inne oparte o 328  |2, 3
|Uno WiFi Rev.2                      |wszystkie styki cyfrowe
|Mega, Mega2560, MegaADK             |2, 3, 18, 19, 20, 21
|Micro, Leonardo, inne oparte o 32u4 |0, 1, 2, 3, 7
|Zero                                |wszystkie cyfrowe styki, oprócz 4
|rodzina płytek MKR                  |0, 1, 4, 5, 6, 7, 8, 9, A1, A2
|Due                                 |wszystkie styki cyfrowe
|101                                 |wszystkie styki cyfrowe (z *CHANGE* działają tylko styki 2, 5, 7, 8, 10, 11, 12, 13)
|===================================================

[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia

*Uwaga* +
Wewnątrz podłączonej funkcji `delay()` nie będzie działać, a wartość zwrócona przez `millis()` nie zwiększy się. Dane seryjne odebrane podczas korzystania z funkcji mogą zostać utracone. Wszystkie zmienne, które modyfikujesz wewnątrz takiej funkcji powinieneś zadeklarować jako `volatile` (ulotne). Aby uzyskać więcej informacji, zobacz poniżej sekcję o procedurach obsługi przerwań.
[%hardbreaks]

[float]
== Używanie przerwań
Przerwania są przydatne do tego, aby pewne rzeczy działały automatycznie w programach mikrokontrolerów i mogą pomóc rozwiązać problemy z zależnościami czasowymi. Dobrym zastosowaniem przerwania może być odczyt enkodera obrotowego lub monitorowanie danych wejściowych użytkownika.

Jeśli chciałbyś się upewnić, że program zawsze wychwyci impulsy z enkodera obrotowego, aby nigdy nie przegapił impulsu, bardzo trudno byłoby napisać program, który zrobiłby jeszcze cokolwiek innego, ponieważ program musiałby stale sondować czujnik linii do enkodera, aby wychwytywać impulsy, gdyby wystąpiły. Z innymi czujnikami może być podobnie. Na przykład próbując odczytać czujnik dźwięku, którym chcesz zarejestrować kliknięcie, lub czujnik szczelinowy na podczerwień (foto-przerywacz) aby zarejestrować wrzucenie monety. We wszystkich tych sytuacjach użycie przerwania może pozwolić mikrokontrolerowi wykonywać inne czynności bez utraty danych wejściowych.

[float]
== Informacje o procedurach obsługi przerwań
Procedury obsługi przerwań to specjalne rodzaje funkcji, które mają pewne unikalne ograniczenia, których większość innych funkcji nie ma. Procedury te nie mogą mieć żadnych parametrów i nie powinny niczego zwracać.

Zasadniczo procedury obsługi przerwań powininny być tak krótkie i szybkie, jak to tylko możliwe. Jeśli szkic używa wielu takich procedur, tylko jedna może być uruchomiona w tym samym czasie, inne przerwania zostaną obsłużone po zakończeniu bieżącego w kolejności zależnej od ich priorytetu. Działanie `millis()` polega na liczeniu przerwań, więc nigdy nie zwiększy się w procedurze obsługi przerwania. Ponieważ `delay()` wymaga przerwań do działania, nie zadziała, jeśli zostanie wywołany wewnątrz procedury obsługi przerwania. `micros()` początkowo zadziała, ale zacznie zachowywać się nieprawidłowo po 1-2 ms. `delayMicroseconds()` nie używa żadnego licznika, więc będzie działać normalnie.

Zazwyczaj do przekazywania danych między procedurami obsługi przerwań a programem głównym używa się zmiennych globalnych. Aby upewnić się, że zmienne współdzielone między tymi procedurami a programem głównym są poprawnie aktualizowane, zadeklaruj je jako `volatile`.

Aby uzyskać więcej informacji na temat przerwań, przeczytaj http://gammon.com.au/interrupts[notatki Nicka Gammona].

[float]
=== Składnia
`attachInterrupt(digitalPinToInterrupt(styk), PoP, tryb)` (zalecana) +
`attachInterrupt(przerwanie, PoP, tryb)` (nie zalecana) +
`attachInterrupt(styk, PoP, tryb)` (Nie zalecana. Ponadto ta składnia działa tylko na płytach Arduino SAMD, Uno WiFi Rev2, Due i 101.)


[float]
=== Parametry
`przerwanie`: numer przerwania. Dozwolone typy danych: `int`. +
`styk`: numer styku Arduino. +
`PoP`: Procedure obsługi przerwania, którą wywołać, gdy nastąpi przerwanie; ta funkcja nie może przyjmować żadnych parametrów i niczego nie zwracać. +
`tryb`: określa, kiedy ma zostać obsłużone przerwanie. Zdefiniowane są cztery stałe jako prawidłowe wartości: +

* *LOW* spowodowanie przerwania, kiedy styk będzie w stanie niskim, +
* *CHANGE* spowodowanie przerwania, kiedy styk zmieni stan +
* *RISING* spowodowanie przerwania, kiedy styk przejdzie ze stanu niskiego do wysokiego, +
* *FALLING* kiedy styk zmieni stan z wysokiego na niski. +

Dla płytek Due, Zero i MKR1000 możliwe jest również: +

* *HIGH* spowodowanie przerwania, kiedy styk jest w stanie wysokim.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ

// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
const byte stykDiody = 13;
const byte stykPrzerwania = 2;
volatile byte stan = LOW;

void setup() {
  pinMode(stykDiody, OUTPUT);
  pinMode(stykPrzerwania, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(stykPrzerwania), mruga, CHANGE);
}

void loop() {
  digitalWrite(stykDiody, stan);
}

void mruga() {
  stan = !stan;
}
----

[float]
=== Numery przerwań
Zwykle powinieneś używać `digitalPinToInterrupt(styk)`, zamiast umieszczać numer przerwania bezpośrednio w swoim szkicu. Poszczególne styki z przerwaniami i ich mapowanie na numery przerwań różnią się w zależności od rodzaju płytki. Bezpośrednie użycie numerów przerwań może wydawać się proste, ale może powodować problemy ze zgodnością, gdy szkic zostanie uruchomiony na innej płytce.

Jednak starsze szkice często używają bezpośrednich numerów przerwań. Często używano numeru 0 (dla cyfrowego styku 2) lub numeru 1 (dla cyfrowego styku 3). Poniższa tabela pokazuje dostępne styki z obsługą przerwań na różnych płytkach.

Zauważ, że w poniższej tabeli numery przerwań odnoszą się do numeru, który zostanie przekazany do `attachInterrupt()`. Ze względów historycznych ta numeracja nie zawsze odpowiada bezpośrednio numeracji przerwań w układzie ATmega (np. int.0 odpowiada INT4 w układzie ATmega2560).

[options="header"]
|===================================================
|Płytka                               | int.0 | int.1 | int.2 | int.3 | int.4 | int.5
|Uno, Ethernet                        | 2 | 3 | | | |
|Mega2560                             | 2 | 3 | 21 | 20 | 19 | 18
|Oparte na 32u4 (np. Leonardo, Micro) | 3 | 2 | 0 | 1 | 7 |
|===================================================
W przypadku płytek Uno WiFiRev.2, Due, Zero, MKR Family i 101 *numer przerwania = numer styku*.


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
