---
title: delayMicroseconds()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---





= delayMicroseconds()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wstrzymuje program na określony czas podany jako parametr (w mikrosekundach). Milisekunda ma tysiąc mikrosekund, a sekunda milion mikrosekund.

Obecnie największa wartość, która spowoduje dokładne opóźnienie, to 16383. Może się to zmienić w przyszłych wersjach Arduino. W przypadku opóźnień dłuższych niż kilka tysięcy mikrosekund należy zamiast tego użyć funkcji `delay()`.
[%hardbreaks]


[float]
=== Składnia
`delayMicroseconds(us)`


[float]
=== Parametry
`us`: liczba mikrosekund. Dozwolone typy danych: `unsigned int`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program konfiguruje styk numer 8 aby pracował jako wyjście. Wysyła ciąg impulsów w okresie około 100 mikrosekund. Przybliżenie wynika z wykonania w programie również innych instrukcji.

[source,arduino]
----
int outPin = 8;               // styk cyfrowy numer 8

void setup() {
  pinMode(outPin, OUTPUT);    // ustaw styk cyfrowy jako wyjście
}

void loop() {
  digitalWrite(outPin, HIGH); // włącz styk
  delayMicroseconds(50);      // przerwa na 50 mikrosekund
  digitalWrite(outPin, LOW);  // wyłącz styk
  delayMicroseconds(50);      // przerwa na 50 mikrosekund
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Ta funkcja działa bardzo dokładnie w zakresie 3 mikrosekund i więcej. Nie możemy jednak zapewnić, że delayMicroseconds będzie działać dokładnie dla mniejszych czasów opóźnienia.

Od Arduino 0018 funkcja delayMicroseconds() nie wyłącza już przerwań.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
