---
title: delay()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---


= delay()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wstrzymuje program na czas określony przez parametr (wyrażony w milisekundach). (Sekunda to 1000 milisekund).
[%hardbreaks]


[float]
=== Składnia
`delay(ms)`


[float]
=== Parametry
`ms`: liczba millisekund do wstrzymania. Dozwolone typy danych: `unsigned long`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Kod wstrzymuje program na sekundę przed przełączeniem stanu styku wyjściowego.

[source,arduino]
----
int stykDiody = 13;              // dioda świecąca podłączona do styku 13

void setup() {
  pinMode(stykDiody, OUTPUT);    // ustawienie styku cyfrowego jako wyjście
}

void loop() {
  digitalWrite(stykDiody, HIGH); // włącz diodę
  delay(1000);                   // czekaj sekundę
  digitalWrite(stykDiody, LOW);  // wyłącz diodę
  delay(1000);                   // czekaj sekundę
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Chociaż łatwo jest uzyskać migającą diodę za pomocą funkcji `delay()`, a wiele szkiców używa krótkich czasów opóźnień w przypadku takich zadań, jak likwidacja drgań styków, to użycie `delay()` w szkicu ma znaczące wady. Podczas trwania funkcji opóźniającej nie może działać żadne odczytywanie czujników, obliczenia matematycznych lub manipulowanie stykami, więc w efekcie zatrzymuje się większość czynności. Aby zapoznać się z alternatywnym podejściem do sterowania czasem, zobacz szkid link:http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink Without Delay], który odpytuje w pętli funkcję link:../ millis[millis ()] aż do określonego czasu. Bardziej doświadczeni programiści zwykle unikają użycia `delay()` do pomiaru czasu zdarzeń dłuższych niż 10 milisekund, chyba że szkic Arduino jest bardzo prosty.

Pewne rzeczy dzieją się, gdy funkcja delay() kontroluje układ Atmega, ponieważ funkcja opóźnienia nie wyłącza przerwań. Rejestrowana jest komunikacja szeregowa pojawiająca się na styku RX, wartości PWM i stany styków są zachowywane (link:../../ analog-io/analogwrite[analogWrite]), a link:../../external-interrupts/attachinterrupt[interrupts] będzie działało tak, jak powininno.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink bez Delay^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
