---
title: micros()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---





= micros()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Zwraca liczbę mikrosekund od momentu, gdy płyta Arduino rozpoczęła wykonywanie bieżącego programu. Ta liczba przepełni (wróci do zera) po około 70 minutach. Na płytach Arduino 16 MHz (np. Uno i Nano) funkcja ta ma rozdzielczość czterech mikrosekund (czyli zwracana wartość jest zawsze wielokrotnością czterech). Na płytach Arduino 8 MHz (np. LilyPad) funkcja ta ma rozdzielczość ośmiu mikrosekund.
[%hardbreaks]


[float]
=== Składnia
`czas = micros()`


[float]
=== Parametry
Nic


[float]
=== Wartości zwracane
Zwraca liczbę mikrosekund od momentu, gdy płyta Arduino rozpoczęła wykonywanie bieżącego programu. Typ danych: `unsigned long`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Program zwraca liczbę mikrosekund od momentu uruchomienia płyty Arduino.

[source,arduino]
----
unsigned long czas;

void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.print("Czas: ");
  czas = micros();

  Serial.println(czas); // wypisuje czas od uruchomienia programu
  delay(1000);          // poczekaj sekundę, aby nie wysyłać ogromnych ilości danych
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Milisekunda ma 1.000 mikrosekund, a sekunda 1.000.000 mikrosekund.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
