---
title: millis()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---

= millis()

// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Zwraca liczbę milisekund, które minęły od momentu, gdy płyta Arduino rozpoczęła wykonywanie bieżącego programu. Ta liczba się przepełni (wróci do zera) po około 50 dniach.
[%hardbreaks]


[float]
=== Składnia
`czas = millis()`


[float]
=== Parametry
Nic


[float]
=== Wartości zwracane
Liczba milisekund, które minęły od uruchomienia programu. Typ danych: `unsigned long`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Ten przykładowy program drukuje na porcie szeregowym liczbę milisekund, które minęły od momentu, gdy płyta Arduino rozpoczęła wykonywać program.

[source,arduino]
----
unsigned long czas;

void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.print("Czas: ");
  czas = millis();

  Serial.println(czas); // wypisuje czas od uruchomienia programu
  delay(1000);          // poczekaj sekundę, aby nie wysyłać ogromnych ilości danych
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Zwróć uwagę, że wartość zwracana przez funkcję millis() jest typu `unsigned long`, mogą wystąpić błędy logiczne, jeśli programista spróbuje wykonać działania arytmetyczne na mniejszych typach danych, takich jak `int`. Nawet w przypadku `long` ze znakiem można napotkać błędy, ponieważ jego maksymalna wartość jest o połowę mniejsza niż jego odpowiednik bez znaku.

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink bez Delay^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
