---
title: Stream.readBytesUntil()
---




= readBytesUntil()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`readBytesUntil()` odczytuje znaki ze strumienia do bufora. Funkcja kończy działanie po wykryciu znaku kończącego, odczytaniu określonej długości lub przekroczeniu limitu czasu (patrz link:../streamsettimeout[setTimeout()]). Funkcja zwraca znaki do ostatniego znaku przed podanym znakiem kończącym. Znak kończący nie jest zwracany w buforze. 

`readBytesUntil()` zwraca liczbę bajtów umieszczonych w buforze. 0 oznacza, że nie znaleziono prawidłowych danych. 

Ta funkcja jest częścią klasy Stream i może być wywołana przez każdą klasę, która po niej dziedziczy (Wire, Serial itp.). Zobacz link:../../stream[stream class] aby uzyskać więcej informacji.
[%hardbreaks]


[float]
=== Składnia
`stream.readBytesUntil(znak, bufor, długość)`


[float]
=== Parametry
`stream`: instancja klasy, która dziedziczy po Stream. +
`znak`: poszukiwany znak. Dozwolone typy danych: `char`. +
`bufor`: bufor do przechowywania bajtów. Dozwolone typy danych: tablica typów `char` lub `byte`. +
`długość`: liczba bajtów do odczytania. Dozwolone typy danych: `int`.


[float]
=== Wartości zwracane
Liczba bajtów umieszczonych w buforze.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i ostrzeżenia
Znak kończący jest usuwany ze strumienia.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ
