---
title: Stream.readStringUntil()
---




= readStringUntil()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`readStringUntil()` odczytuje znaki ze strumienia do ciągu. Funkcja kończy działanie, jeśli zostanie wykryty znak kończący lub upłynie limit czasu (zobacz link:../streamsettimeout[setTimeout()]). 

Ta funkcja jest częścią klasy Stream i może być wywołana przez każdą klasę, która po niej dziedziczy (Wire, Serial itp.). Zobacz link:../../stream[stream class] aby uzyskać więcej informacji.
[%hardbreaks]


[float]
=== Składnia
`strumień.readString(koniec)`


[float]
=== Parametry
`strumień`: instancja klasy, która dziedziczy po Stream. +
`koniec`: poszukiwany znak kończący ciąg. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
Cały ciąg odczytany ze strumienia, aż do znaku kończącego 

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i ostrzeżenia
Znak kończący jest usuwany ze strumienia.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ
