---
title: Stream.parseFloat()
---




= parseFloat()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`parseFloat()` zwraca pierwszą poprawną liczbę zmiennoprzecinkową od bieżącej pozycji. `parseFloat()` zakończy pierwszy znak, który nie jest liczbą zmiennoprzecinkową. Funkcja kończy działanie, jeśli upłynie limit czasu (patrz link:../streamsettimeout[Stream.setTimeout()]). 

Ta funkcja jest częścią klasy Stream i może być wywołana przez każdą klasę, która po niej dziedziczy (Wire, Serial itp.). Zobacz link:../../stream[stream class] aby uzyskać więcej informacji.
[%hardbreaks]


[float]
=== Składnia
`stream.parseFloat()` +
`stream.parseFloat(poszukiwany)` +
`stream.parseFloat(poszukiwany, ignorowany)`


[float]
=== Parametry
`stream` : instancja klasy, która dziedziczy po Stream. +
`poszukiwany`: tryb poszukiwania liczby zmiennoprzecinkowej w strumieniu. Dozwolone typy danych: `LookaheadMode`. Dozwolone wartości parametru `poszukiwany`:

* `SKIP_ALL`: wszystkie znaki inne niż znak minus, kropka dziesiętna lub cyfry są ignorowane podczas analizowania strumienia w poszukiwaniu liczby zmiennoprzecinkowej. To jest domyślny sposób działania.
* `SKIP_NONE`: Nic nie jest pomijane, a strumień nie jest pobierany, chyba że pierwszy oczekujący znak jest prawidłowy.
* `SKIP_WHITESPACE`: Pomijane są tylko znaki tabulatora, odstępu, nowego wiersza i powrotu karetki.

`ignorowany`: używany do pominięcia wskazanego znaku w wyszukiwaniu. Na przykład do pominięcia separatora grup trzycyfrowych (tysięcy). Dozwolone typy danych: `char`


[float]
=== Wartości zwracane
Typ danych: `float`.

--
// KONIEC SEKCJI OPISOWEJ
