---
title: Stream.readBytes()
---




= readBytes()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`readBytes()` odczytuje znaki ze strumienia do bufora. Funkcja kończy działanie po odczytaniu określonej długości lub po przekroczeniu limitu czasu (patrz link:../streamsettimeout[setTimeout()]).

`readBytes()` zwraca liczbę bajtów umieszczonych w buforze. 0 oznacza, że nie znaleziono prawidłowych danych. 

Ta funkcja jest częścią klasy Stream i może być wywołana przez każdą klasę, która po niej dziedziczy (Wire, Serial itp.). Zobacz link:../../stream[stream class] aby uzyskać więcej informacji.
[%hardbreaks]


[float]
=== Składnia
`stream.readBytes(bufor, długość)`


[float]
=== Parametry
`stream` : instancja klasy, która dziedziczy po Stream. +
`bufor`  : bufor do przechowywania bajtów. Dozwolone typy danych: tablica typów `char` lub `byte`. +
`długość`: liczba bajtów do odczytania. Dozwolone typy danych: `int`.


[float]
=== Wartości zwracane
Liczba bajtów umieszczonych w buforze. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ
