---
title: Stream.parseInt()
---




= parseInt()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`parseInt()` zwraca pierwszą prawidłową (długą) liczbę całkowitą znalezioną od bieżącej pozycji w strumieniu

W szczególności:

* Przetwarzanie zatrzymuje się, gdy żadne znaki nie zostały odczytane w skonfigurowanym limicie czasu lub odczytywane zostały dane niecyfrowe; +
* Jeśli w momencie przekroczenia limitu czasu nie odczytano żadnych prawidłowych cyfr (zobacz link:../streamsettimeout[Stream.setTimeout()]), zwracane jest 0;

Ta funkcja jest częścią klasy Stream i może być wywołana przez każdą klasę, która po niej dziedziczy (Wire, Serial itp.). Zobacz link:../../stream[stream class] aby uzyskać więcej informacji.
[%hardbreaks]


[float]
=== Składnia
`strumień.parseInt()` +
`strumień.parseInt(oczekiwany)` +
`strumień.parseInt(oczekiwany, ignorowany)`


[float]
=== Parametry
`strumień` : instancja klasy, która dziedziczy po Stream. +
`oczekiwany`: sposób wyszukiwania liczby całkowitej w strumieniu. Dozwolone typy danych: `LookaheadMode`. Dozwolone wartości parametru `oczekiwany`:

* `SKIP_ALL`: wszystkie znaki inne niż znak minus, kropka dziesiętna lub cyfry są ignorowane podczas analizowania strumienia w poszukiwaniu liczby całkowitej. To jest domyślny sposób działania.
* `SKIP_NONE`: Nic nie jest pomijane, a strumień nie jest pobierany, chyba że pierwszy oczekujący znak jest prawidłowy.
* `SKIP_WHITESPACE`: Pomijane są tylko znaki tabulatora, odstępu, nowego wiersza i powrotu karetki.

`ignorowany`: używany do pominięcia wskazanego znaku w wyszukiwaniu. Na przykład pominięcie separatora grup trzycyfrowych (tysięcy). Dozwolone typy danych: `char`


[float]
=== Wartości zwracane
Typ danych: `long`.

--
// KONIEC SEKCJI OPISOWEJ
