---
title: Stream.parseFloat()
---




= parseFloat()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`parseFloat()` zwraca pierwszą poprawną liczbę zmiennoprzecinkową od bieżącej pozycji. `parseFloat()` zakończy pierwszy znak, który nie jest liczbą zmiennoprzecinkową. Funkcja kończy działanie, jeśli upłynie limit czasu (patrz link:../streamsettimeout[Stream.setTimeout()]). 

Ta funkcja jest częścią klasy Stream i może być wywołana przez każdą klasę, która po niej dziedziczy (Wire, Serial itp.). Zobacz link:../../stream[stream class] aby uzyskać więcej informacji.
[%hardbreaks]


[float]
=== Składnia
`stream.parseFloat()` +
`stream.parseFloat(lookahead)` +
`stream.parseFloat(lookahead, ignore)`


[float]
=== Parametry
`stream` : instancja klasy, która dziedziczy po Stream. +
`poszukiwany`: the mode used to look ahead in the stream for a floating point number. Dozwolone typy danych: `LookaheadMode`. Dozwolone wartości `poszukiwany`:

* `SKIP_ALL`: all characters other than a minus sign, decimal point, or digits are ignored when scanning the stream for a floating point number. This is the default mode.
* `SKIP_NONE`: Nothing is skipped, and the stream is not touched unless the first waiting character is valid.
* `SKIP_WHITESPACE`: Only tabs, spaces, line feeds, and carriage returns are skipped.

`ignore`: used to skip the indicated char in the search. Used for example to skip thousands divider. Dozwolone typy danych: `char`


[float]
=== Wartości zwracane
Typ danych: `float`.

--
// KONIEC SEKCJI OPISOWEJ
