---
title: Stream.setTimeout()
---




= setTimeout()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`setTimeout()` ustawia maksymalną liczbę milisekund oczekiwania na dane strumieniowe, domyślnie jest to 1000 milisekund. Ta funkcja jest częścią klasy Stream i może być wywołana przez każdą klasę, która po niej dziedziczy (Wire, Serial itp.). Zobacz link:../../stream[stream class] aby uzyskać więcej informacji.
[%hardbreaks]


[float]
=== Składnia
`stream.setTimeout(czas)`


[float]
=== Parametry
`stream`: instancja klasy, która dziedziczy po Stream. +
`czas` : limit czasu w milisekundach. Dozwolone typy danych : `long`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i ostrzeżenia
Funkcje strumieniowe, które używają wartości limitu czasu ustawionej przez `setTimeout()`:

* `find()`
* `findUntil()`
* `parseInt()`
* `parseFloat()`
* `readBytes()`
* `readBytesUntil()`
* `readString()`
* `readStringUntil()`

[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ
