---
title: "/* */"
title_expanded: komentarz 
categories: [ "Structure" ]
subCategories: [ "Further Syntax" ]
---





= /* */ Komentarz blokowy


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
*Komentarze* to linie w programie, które służą do informowania siebie lub innych o sposobie działania programu. Są one ignorowane przez kompilator i nie są przesyłane do procesora, więc nie zajmują miejsca w pamięci mikrokontrolera. Jedynym celem stosowania komentarzy jest pomoc w zrozumieniu (lub zapamiętaniu) albo poinformowaniu innych o tym, jak działa Twój program.
[%hardbreaks]

*Komentarz blokowy* lub *komentarz wielolinijkowy* rozpoczyna się symbolem `/\*`, a kończy symbolem `*/`.Ten typ komentarza jest tak nazywany, ponieważ może on rozciągać się na więcej niż jedną linię; po odczytaniu symbolu `/\*` kompilator ignoruje to, co po nim następuje, aż do napotkania  `*/`.

// UWAGA DLA REDAKTORA: Znak '\' przed '*' w niektórych miejscach jest umieszczony po to zapobiec zinterpretowaniu '*' jako pogrubienia tekstu.
// W miejscach, w których znak „/” nie jest używany przed „*”, nie jest wymagana taka operacja.
--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
[source,arduino]
----
/* To jest poprawny komentarz */

/*
  Blink
  Włącza cyklicznie diodę świecącą na sekundę, a następnie wyłącza ją na sekundę.

  Ten przykładowy kod jest własnością publiczną.
  (Inny przykład poprawnego komentarza)
*/

/*
  if (gwb == 0) { // komentarz jednolinijkowy jest dopuszczalny wewnątrz komentarza blokowego
    x = 3;          /* ale nie wewnątrz innego komentarza blokowego - to jest niepoprawne */
  }
// nie zapomnij "zamknąć" komentarza - muszą być sparowane!
*/
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Podczas eksperymentowania z kodem "zakomentowanie" części programu jest wygodnym sposobem na usunięcie linii, które mogą być błędne. Linie zostają w kodzie programu, ale zmieniaja się w komentarze, więc kompilator po prostu je ignoruje. Może to być szczególnie przydatne podczas próby zlokalizowania problemu lub gdy program odmawia kompilacji, a błąd kompilatora jest tajemniczy lub nieużyteczny.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także
[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
