---
title: "{}"
title_expanded: nawiasy klamrowe
categories: [ "Struktura" ]
subCategories: [ "Składnia" ]
---




= {} Nawiasy klamrowe


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Nawiasy klamrowe (określane również jako "klamry") stanowią główną część języka programowania C++. Są one używane w kilku różnych konstrukcjach, opisanych poniżej i mogą czasami być mylące dla początkujących. +
Po otwierającym nawiasie klamrowym `{` musi zawsze następować nawias zamykający `}`. To oznacza, że liczba nawiasów klamrowych w programie musi być zrównoważona (równa liczba otwierających i zamykających). Zintegrowane środowisko programistyczne Arduino (IDE - Integrated Development Environment) zawiera wygodną funkcję sprawdzania równowagi nawiasów klamrowych. Wystarczy zaznaczyć klamrę, a nawet kliknąć miejsce bezpośrednio po nawiasie klamrowym, a jego logiczny towarzysz zostanie podświetlony.
[%hardbreaks]
Początkujący programiści i programiści przenoszący się na C++ z języka BASIC często uważają używanie nawiasów klamrowych za mylące lub zniechęcające. Ale przecież nawiasy klamrowe zastępują instrukcję RETURN w podprogramie (funkcji), słowo kluczowe ENDIF w instrukcji warunkowej oraz NEXT w pętli FOR.
[%hardbreaks]
Niesymetryczne nawiasy klamrowe mogą często prowadzić do tajemniczych, niezrozumiałych błędów kompilatora, które czasami mogą być trudne do wyśledzenia w dużym programie. Ze względu na ich zróżnicowane zastosowania, nawiasy klamrowe są również niezwykle ważne dla składni programu i przesunięcie klamry o jedną lub dwie linie często znacznie wpłynie na sens programu.
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Główne zastosowania nawiasów klamrowych wymienione są w poniższych przykładach.


[float]
==== Funkcje

[source,arduino]
----
void mojafunkcja(typdanych argument) {
  // dowolne instrukcje
}
----
[%hardbreaks]


[float]
==== Pętle

[source,arduino]
----
while (wyrażenie logiczne) {
  // dowolne instrukcje
}

do {
  // dowolne instrukcje
} while (wyrażenie logiczne);

for (nadanie wartości początkowej; warunek zakończenia; wyrażenie aktualizujące) {
  // dowolne instrukcje
}
----
[%hardbreaks]




[float]
==== Instrukcje warunkowe

[source,arduino]
----
if (wyrażenie logiczne) {
  // dowolne instrukcje
}

else if (wyrażenie logiczne) {
  // dowolne instrukcje
}
else {
  // dowolne instrukcje
}
----
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ



// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także
[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
