---
title: "#define"
title_expanded: definicja
categories: [ "Structure" ]
subCategories: [ "Further Syntax" ]
---





= #define


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`#define` jest użytecznym składnikiem C++, który pozwala programiście przypisać nazwę do stałej wartości przed skompilowaniem programu. Stałe zdefiniowane w arduino nie zajmują miejsca w pamięci programu mikrokontrolera. W trakcie kompilacji stałe zostaną zastąpione przez kompilator zdefiniowanymi wartościami.
[%hardbreaks]

Może to mieć jednak pewne niepożądane efekty uboczne, jeśli na przykład definicja stałej jest zawarta w nazwie innej stałej lub zmiennej. W takim przypadku tekst zostanie zastąpiony przez zdefiniowaną liczbę (lub napis).
[%hardbreaks]

Ogólnie rzecz biorąc, słowo kluczowe link:../../../variables/variable-scope\--qualifiers/const[const] bardziej nadaje się do definiowania stałych i powinno być używane zamiast #define.
[%hardbreaks]

[float]
=== Składnia
`#define nazwaStałej wartość`


[float]
=== Parametry
`nazwaStałej`: nazwa do zdefiniowania. +
`wartość`: wartość do przypisania.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
#define stykDiody 3
// W trakcie kompilacji każde wystąpienie napisu stykDiody kompilator zastąpi wartością 3.
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Po instrukcji #define nie ma średnika. Jeśli jakiś dołączysz to kompilator może zgłosić tajemnicze błędy gdzieś dalej na stronie.

[source,arduino]
----
#define stykDiody 3; // to jest błędne
----

Podobnie umieszczenie znaku równości po instrukcji #define spowoduje wygenerowanie tajemniczego błędu kompilatora w dalszej części strony.

[source,arduino]
----
#define stykDiody  = 3 // to również jest błędne
----
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../../variables/variable-scope\--qualifiers/const[const]
* #JĘZYK# link:../../../variables/constants/constants[Stałe]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
