---
title: "#include"
title_expanded: dołącz
categories: [ "Struktura" ]
subCategories: [ "Składnia" ]
---





= #include


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`#include` służy do dołączania do szkicu zewnętrznych bibliotek. Daje to programistom dostęp do dużej grupy standardowych bibliotek C (grup gotowych funkcji), a także bibliotek napisanych specjalnie dla Arduino.
[%hardbreaks]

Główna strona dokumentacji dla bibliotek AVR C (AVR jest oznaczeniem dla układów Atmel, na których opiera się Arduino) znajduje się http://www.nongnu.org/avr-libc/user-manual/modules.html[tutaj^]
[%hardbreaks]

Zauważ, że `#include`, podobnie jak link:../define[`#define`], nie ma na końcu średnika, więc kiedy go tam postawisz to kompilator wygeneruje tajemnicze komunikaty o błędach.
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
W tym przykładzie dołączona zostaje biblioteka Servo, dzięki czemu jej funkcje mogą być używane do sterowania serwomechanizmem.


[source,arduino]
----
#include <Servo.h>

Servo mojeserwo;        // tworzenie objektu do kontroli serwomechanizmu

void setup() {
  mojeserwo.attach(9);  // serwomechanizm podłączony do styku 9 będzie powiązany z obiektem typu Servo
}

void loop() {
  for (int poz = 0; poz <= 180; poz += 1) { // od 0 do 180 stopni
                                            // w krokach co 1 stopień
    mojeserwo.write(poz);                   // powiedz serwomechanizmowi, aby usyawił się na pozycji 'poz'
    delay(15);                              // czekaj 15ms, aż serwomechanizm osiągnie pozycję
  }
  for (int poz = 180; poz >= 0; poz -= 1) { // od 180 do 0 stopni
    mojeserwo.write(poz);                   // powiedz serwomechanizmowi, aby usyawił się na pozycji 'poz'
    delay(15);                              // czekaj 15ms, aż serwomechanizm osiągnie pozycję
  }
}
----


--
// KONIEC SEKCJI JAK UŻYWAĆ



// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]


--
// KONIEC SEKCJI ZOBACZ TAKŻE
