---
title: "//"
title_expanded: komentarz jednolinijkowy
categories: [ "Structure" ]
subCategories: [ "Further Syntax" ]
---





= // Komentarz jednolinijkowy


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
*Komentarze* to linie w programie, które służą do informowania siebie lub innych o sposobie działania programu. Są one ignorowane przez kompilator i nie są przesyłane do procesora, więc nie zajmują miejsca w pamięci mikrokontrolera. Jedynym celem stosowania komentarzy jest pomoc w zrozumieniu (lub zapamiętaniu) albo poinformowaniu innych o tym, jak działa Twój program.
[%hardbreaks]

*Komentarz jednolinijkowy* zaczyna się od `//` (dwóch sąsiadujących ukośników), a kończy się automatycznie na końcu linii. Wszystko co wystąpi po `//`, aż do końca linii, zostanie zignorowany przez kompilator.
--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
Istnieją dwa sposoby oznaczania linii jako komentarz:

[source,arduino]
----
// styk 13 jest połączony z diodą świecącą na większości płytek Arduino.
// nadaj mu nazwę:
int dioda = 13;
digitalWrite(dioda, HIGH);  // włącz diodę świecącą (HIGH to wysoki poziom napięcia)
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Podczas eksperymentowania z kodem "zakomentowanie" części programu jest wygodnym sposobem na usunięcie linii, które mogą być błędne. Linie zostają w kodzie programu, ale zmieniaja się w komentarze, więc kompilator po prostu je ignoruje. Może to być szczególnie przydatne podczas próby zlokalizowania problemu lub gdy program odmawia kompilacji, a błąd kompilatora jest tajemniczy lub nieużyteczny.
[%hardbreaks]


--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
