---
title: "<<"
title_expanded: przesunięcie bitowe w lewo
categories: [ "Struktura" ]
subCategories: [ "Operatory bitowe" ]
---





= << Przesunięcie bitowe w lewo


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Operator przesunięcia w lewo `<<` powoduje przesunięcie bitów lewego argumentu *w lewo* o liczbę pozycji określonych przez prawy argument.
[%hardbreaks]


[float]
=== Składnia
`zmienna << liczba_bitów;`


[float]
=== Parametry
`zmienna`: Dozwolone typy danych: `byte`, `int`, `long`. +
`liczba_bitów`: liczba, która jest < = 32. Dozwolone typy danych: `int`.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
int a = 5;           // dwójkowo: 0000000000000101
int b = a << 3;      // dwójkowo: 0000000000101000, lub 40 dziesiętnie
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Kiedy przesuniesz wartość x o y bitów (x << y), y lewych bitów w liczbie x będzie utracone, dosłownie wysunięte na bok:

[source,arduino]
----
int x = 5;           // dwójkowo: 0000000000000101
int y = 14;
int wynik = x << y;  // dwójkowo: 0100000000000000 - pierwsza jedynka w 101 zostanie odrzucona
----

Jeśli wiesz, że nie stracisz żadnej ważnej informacji w trakcie przesuwania, łatwo możesz wyobrazić sobie operator przesunięcia w lewo jako, mnożenie lewego argumentu przez 2 podniesione do potęgi prawego argumentu. Na przykład, aby wygenerować potęgi liczby 2, można zastosować następujące wyrażenia:

[source,arduino]
----
   Operacja   Wynik
   ---------  ------
    1 <<  0      1
    1 <<  1      2
    1 <<  2      4
    1 <<  3      8
    ...
    1 <<  8    256
    1 <<  9    512
    1 << 10   1024
    ...
----

Poniższy przykład może być użyty do wydrukowania na monitorze szeregowym wartości odebranego bajtu, przy użyciu operatora przesunięcia w lewo. Aby wydrukować dwójkową reprezentację bajtu, analiza rozpoczyna się od najmniej znaczącego bitu (LSB) do najbardziej znaczącego bitu (MSB):

[source,arduino]
----
void drukujBitowo(int c) {                // Drukuje wartość bajtu dwójkowo (zerami i jedynkami)
  for (int bity = 7; bity > -1; bity--) {
    if (c & (1 << bity)) {                // porównuje bity od 7 do 0 z podanym bajtem
      Serial.print("1");                  // jeżeli wynik porównania bitu jest różny od 0
    }
    else {
      Serial.print("0"); 
    }
  }
}
----
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




//POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]

[role="example"]
* #PRZYKŁAD# https://www.arduino.cc/playground/Code/BitMath[Przewodnik po arytmetyce bitowej^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE

