---
title: "|"
title_expanded: bitwowe lub
categories: [ "Struktura" ]
subCategories: [ "Operatory bitowe" ]
---





= | Bitowe LUB


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
W języku C++ operator bitowego LUB oznacza się symbolem pionowej kreski |. Podobnie jak operator &, również | działa niezależnie dla każdego bitu z dwóch otaczających wyrażeń całkowitych, ale robi to (oczywiście) inaczej. Bitowe LUB dwóch bitów wynosi 1, jeśli jeden lub oba bity wejściowe mają wartość 1, w przeciwnym razie wynikiem jest 0.
[%hardbreaks]

Innymi słowy:

    0  0  1  1    argument1
    0  1  0  1    argument2
    ----------
    0  1  1  1    (argument1 | argument2) - zwracany wynik
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
int a =  92;    // dwójkowo: 0000000001011100
int b = 101;    // dwójkowo: 0000000001100101
int c = a | b;  // wynik:    0000000001111101, lub dziesiętnie 125.
----
[%hardbreaks]

Jednym z najczęstszych zastosowań bitowego LUB jest ustawienie wielu bitów jednocześnie w liczbie wielobitowej.

[source,arduino]
----
// Uwaga: ten kod jest specyficzny dla architektury AVR
// jednoczesne ustawienie bitów dla styków od 2 do 7, pozostawiając niezmienione PD0 i PD1 (xx | 00 == xx)
// tak samo jak pinMode(styk, OUTPUT) dla styków od 2 do 7 dla płytek Uno lub Nano
DDRD = DDRD | B11111100;
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także


[role="language"]
* #JĘZYK# link:../../boolean-operators/logicalor[|| Logiczne LUB]

[role="example"]
* #PRZYKŁAD# https://www.arduino.cc/playground/Code/BitMath[Przewodnik po arytmetyce bitowej^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
