---
title: "&"
title_expanded: bitwowe I
categories: [ "Struktura" ]
subCategories: [ "Operatory bitowe" ]
---





= & Bitowe I


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
W języku C++ operator bitowego I oznacza się pojedynczym znakiem ampersand `&`. Umieszcza się go pomiędzy dwoma wyrażeniami całkowitymi. Bitowe I działa niezależnie na każdy bit otaczających je wyrażeń, zgodnie z następującymi regułami: jeśli oba bity wejściowe wynoszą 1, to wynik na wyjściu wynosi 1, w przeciwnym razie wynik wynosi 0.
[%hardbreaks]

Można to przedstawić również w ten sposób:

    0  0  1  1    argument1
    0  1  0  1    argument2
    ----------
    0  0  0  1    (argument1 & argument2) - zwracany wynik
[%hardbreaks]

W Arduino typ int jest wartością 16-bitową, więc użycie & pomiędzy dwoma wyrażeniami int spowoduje 16 jednoczesnych operacji bitowego I.
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
W poniższym fragmencie kodu:

[source,arduino]
----
int a =  92;    // dwójkowo: 0000000001011100
int b = 101;    // dwójkowo: 0000000001100101
int c = a & b;  // wynik:    0000000001000100, lub dziesiętnie 68.
----
każdy z 16 bitów zmiennych a i b będzie przetwarzany przy użyciu bitowego I. Wszystkie 16 bitów wynikowych będzie przechowane w zmiennej c, co da wartość 01000100 w postaci dwójkowej, czyli 68 w postaci dziesiętnej.
[%hardbreaks]

Jednym z najczęstszych zastosowań bitowych I jest wybranie konkretnego bitu (lub bitów) z wartości całkowitej, często nazywanej maskowaniem. Zobacz poniższy przykład (specyficzny dla architektury AVR).

[source,arduino]
----
PORTD = PORTD & B00000011;  // wyczyść bity 2 - 7, pozostaw niezmienione styki PD0 i PD1 (xx & 11 == xx)
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także


[role="language"]
* #JĘZYK# link:../../boolean-operators/logicaland[&& Logiczne I]

[role="example"]
* #PRZYKŁAD# https://www.arduino.cc/playground/Code/BitMath[Przewodnik po arytmetyce bitowej^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
