---
title: "^"
title_expanded: bitowe ALBO
categories: [ "Struktura" ]
subCategories: [ "Operatory bitowe" ]
---





= ^ Bitowe ALBO


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
W języku C ++ istnieje niezwykły operator zwany bitowym ALBO, nazywany również bitową różnicą symetryczną. (W języku angielskim zwany XOR) Bitowy operator ALBO jest zapisywany za pomocą symbolu daszka `^`. Ta operacja daje w wyniku 1 tylko wtedy, gdy bity wejściowe są różne, w przeciwnym razie daje 0. Innymi słowy wynik bedzie 1 jeżeli jedna ALBO druga wartość będzie 1.
[%hardbreaks]

Dokładnie działa to tak:

    0  0  1  1    argument1
    0  1  0  1    argument2
    ----------
    0  1  1  0    (argument1 ^ argument2) - wynik
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
int x = 12;     // dwójkowo: 1100
int y = 10;     // dwójkowo: 1010 (tzw. maska)
int z = x ^ y;  // dwójkowo: 0110, lub dziesiętnie 6
----
[%hardbreaks]

Operator ^ jest często używany do przełączania (tj. zmiany z 0 na 1, a 1 na 0) niektórych bitów w wyrażeniu całkowitym. W bitowej operacji ALBO, jeśli w bicie maski znajduje się 1, bit ten jest odwrócony; jeśli jest 0, bit nie jest odwrócony i pozostaje taki sam.

[source,arduino]
----
// Uwaga: Ten kod wykorzystuje rejestry specyficzne dla mikrokontrolerów AVR (Uno, Nano, Leonardo, Mega itp.)
// Nie będzie kompilował się dla innych architektur
void setup() {
  DDRB = DDRB | B00100000;  // ustaw PB5 (styk 13 na Uno/Nano, styk 9 na Leonardo/Micro, styk 11 na Mega) jako wyjście (OUTPUT)
  Serial.begin(9600);
}

void loop() {
  PORTB = PORTB ^ B00100000;  // odwróć PB5, pozostałe pozostaw niezmienione
  delay(100);
}
----


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #PRZYKŁAD# https://www.arduino.cc/playground/Code/BitMath[Przewodnik po arytmetyce bitowej^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
