---
title: "^"
title_expanded: bitowe xor
categories: [ "Struktura" ]
subCategories: [ "Operatory bitowe" ]
---





= ^ Bitowe XOR


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
There is a somewhat unusual operator in C++ called bitwise EXCLUSIVE OR, also known as bitwise XOR. (In English this is usually pronounced "eks-or".) The bitwise XOR operator is written using the caret symbol `^`. A bitwise XOR operation results in a 1 only if the input bits are different, else it results in a 0.
[%hardbreaks]

Dokładnie działa to tak:

    0  0  1  1    argument1
    0  1  0  1    argument2
    ----------
    0  1  1  0    (argument1 ^ argument2) - wynik
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod

[source,arduino]
----
int x = 12;     // dwójkowo: 1100
int y = 10;     // dwójkowo: 1010
int z = x ^ y;  // dwójkowo: 0110, lub dziesiętnie 6
----
[%hardbreaks]

The ^ operator is often used to toggle (i.e. change from 0 to 1, or 1 to 0) some of the bits in an integer expression. In a bitwise XOR operation if there is a 1 in the mask bit, that bit is inverted; if there is a 0, the bit is not inverted and stays the same.

[source,arduino]
----
// Note: This code uses registers specific to AVR microcontrollers (Uno, Nano, Leonardo, Mega, etc.)
// it will not compile for other architectures
void setup() {
  DDRB = DDRB | B00100000;  // set PB5 (pin 13 on Uno/Nano, pin 9 on Leonardo/Micro, pin 11 on Mega) as OUTPUT
  Serial.begin(9600);
}

void loop() {
  PORTB = PORTB ^ B00100000;  // invert PB5, leave others untouched
  delay(100);
}
----


--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #PRZYKŁAD# https://www.arduino.cc/playground/Code/BitMath[BitMath Tutorial^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
