---
title: constants
categories: [ "Zmienne" ]
subCategories: [ "Stałe" ]
---

= Stałe


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
== Opis
Stałe to wstępnie zdefiniowane wyrażenia w języku Arduino. Dzięki nim program może być łatwiejszy do czytania. Wyróżniamy następujące grupy

[float]
== Definiowanie poziomów logicznych: prawda (ang.true) i fałsz (ang.false) (stałe logiczne)
Istnieją dwie stałe reprezentujące prawdę i fałsz w języku Arduino: `true` i `false`.

[float]
=== false
Z dwóch powyższych `false` jest łatwiejszy do zdefiniowania. zdefiniowany jest jako 0 (zero).
[%hardbreaks]

[float]
=== true
`true` jest często określana jako 1, co jest poprawne, ale ma szerszą definicję. Dowolna niezerowa liczba całkowita onzacza prawdę w sensie logicznym. Więc -1, 2 i -200 również oznaczają prawdę w sensie logicznym.
[%hardbreaks]

Zauważ, że stałe `true` i `false` pisane są małymi literami w przeciwnieństwie do `HIGH`, `LOW`, `INPUT`, i `OUTPUT`.
[%hardbreaks]

[float]
== Definiowanie poziomów logicznych na stykach: HIGH i LOW
Podczas odczytu lub zapisu na styku cyfrowym są tylko dwie możliwe wartości, które styk może przyjąć/być ustawiony: `HIGH` (wysoki) i `LOW` (niski).

[float]
=== HIGH
Znaczenie stanu wysokiego `HIGH` (w odniesieniu do styku) jest nieco inne, w zależności od tego czy styk jest ustawiony jako wejście (`INPUT`) lub wyjście (`OUTPUT`). Jeżeli styk ustawione jest jako wejście `INPUT` przy pomocy link:../../../functions/digital-io/pinmode[pinMode()], i odczytywany poprzez link:../../../functions/digital-io/digitalread[digitalRead()], Arduino (ATmega) zgłasza stan wysoki(`HIGH`) jeśli:

  - na styku występuje napięcie większe niż 3.0V (płytki zasilane napięciem 5V)
  - na styku występuje napięcie większe niż 2.0V (płytki 3.3V)
[%hardbreaks]

Styk można również skonfigurować jako wejście (INPUT) przy pomocy `pinMode()`, a następnie ustawiony w stan wysoki przy pomocy link:../../../functions/digital-io/digitalwrite[digitalWrite()]. Zostaną włączone wewnętrzne rezystory podciągające (20k), które _podciągną_ styk wejściowy aby odczytywał stan wysoki, chyba, że zostanie sprowadzony w stan niski przez układ zewnętrzny. Można to też zrobić inaczej, podając argument `INPUT_PULLUP` w funkcji `pinMode()`, as explained in more detail in the section "Defining Digital Pins modes: INPUT, INPUT_PULLUP, and OUTPUT" further below.
[%hardbreaks]

When a pin is configured to OUTPUT with `pinMode()`, and set to `HIGH` with `digitalWrite()`, the pin is at:

  - 5 woltów (płytki 5V)
  - 3,3 woltów (płytki 3,3V)

In this state it can source current, e.g. light an LED that is connected through a series resistor to ground.
[%hardbreaks]

[float]
=== LOW
The meaning of `LOW` also has a different meaning depending on whether a pin is set to `INPUT` or `OUTPUT`. When a pin is configured as an `INPUT` with `pinMode()`, and read with `digitalRead()`, the Arduino (ATmega) will report LOW if:

  - a voltage less than 1.5V is present at the pin (5V boards)
  - a voltage less than 1.0V (Approx) is present at the pin (3.3V boards)

When a pin is configured to `OUTPUT` with `pinMode()`, and set to `LOW` with `digitalWrite()`, the pin is at 0 volts (both 5V and 3.3V boards). In this state it can sink current, e.g. light an LED that is connected through a series resistor to +5 volts (or +3.3 volts).
[%hardbreaks]

[float]
== Defining Digital Pins modes: INPUT, INPUT_PULLUP, and OUTPUT
Digital pins can be used as `INPUT`, `INPUT_PULLUP`, or `OUTPUT`. Changing a pin with `pinMode()` changes the electrical behavior of the pin.

[float]
=== Pins Configured as INPUT
Arduino (ATmega) pins configured as `INPUT` with `pinMode()` are said to be in a _high-impedance_ state. Pins configured as `INPUT` make extremely small demands on the circuit that they are sampling, equivalent to a series resistor of 100 Megohms in front of the pin. This makes them useful for reading a sensor.
[%hardbreaks]

If you have your pin configured as an `INPUT`, and are reading a switch, when the switch is in the open state the input pin will be "floating", resulting in unpredictable results. In order to assure a proper reading when the switch is open, a pull-up or pull-down resistor must be used. The purpose of this resistor is to pull the pin to a known state when the switch is open. A 10 K ohm resistor is usually chosen, as it is a low enough value to reliably prevent a floating input, and at the same time a high enough value to not not draw too much current when the switch is closed. See the http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^] tutorial for more information.
[%hardbreaks]

If a pull-down resistor is used, the input pin will be `LOW` when the switch is open and `HIGH` when the switch is closed.
[%hardbreaks]

If a pull-up resistor is used, the input pin will be `HIGH` when the switch is open and `LOW` when the switch is closed.
[%hardbreaks]

[float]
=== Pins Configured as INPUT_PULLUP
The ATmega microcontroller on the Arduino has internal pull-up resistors (resistors that connect to power internally) that you can access. If you prefer to use these instead of external pull-up resistors, you can use the `INPUT_PULLUP` argument in `pinMode()`.
[%hardbreaks]

See the http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^] tutorial for an example of this in use.
[%hardbreaks]

Pins configured as inputs with either `INPUT` or `INPUT_PULLUP` can be damaged or destroyed if they are connected to voltages below ground (negative voltages) or above the positive power rail (5V or 3V).
[%hardbreaks]

[float]
=== Pins Configured as OUTPUT
Pins configured as `OUTPUT` with `pinMode()` are said to be in a _low-impedance_ state. This means that they can provide a substantial amount of current to other circuits. ATmega pins can source (provide current) or sink (absorb current) up to 40 mA (milliamps) of current to other devices/circuits. This makes them useful for powering LEDs because LEDs typically use less than 40 mA. Loads greater than 40 mA (e.g. motors) will require a transistor or other interface circuitry.
[%hardbreaks]

Pins configured as outputs can be damaged or destroyed if they are connected to either the ground or positive power rails.
[%hardbreaks]

[float]
== Defining built-ins: LED_BUILTIN
Most Arduino boards have a pin connected to an on-board LED in series with a resistor. The constant `LED_BUILTIN` is the number of the pin to which the on-board LED is connected. Most boards have this LED connected to digital pin 13.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

--
// HOW TO USE SECTION ENDS

// SEE ALSO  SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
