---
title: stałe
categories: [ "Zmienne" ]
subCategories: [ "Stałe" ]
---

= Stałe


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
== Opis
Stałe to wstępnie zdefiniowane wyrażenia w języku Arduino. Dzięki nim program może być łatwiejszy do czytania. Wyróżniamy następujące grupy

[float]
== Definiowanie poziomów logicznych: prawda (ang.true) i fałsz (ang.false) (stałe logiczne)
Istnieją dwie stałe reprezentujące prawdę i fałsz w języku Arduino: `true` i `false`.

[float]
=== false
Z dwóch powyższych `false` jest łatwiejszy do zdefiniowania. zdefiniowany jest jako 0 (zero).
[%hardbreaks]

[float]
=== true
`true` jest często określana jako 1, co jest poprawne, ale ma szerszą definicję. Dowolna niezerowa liczba całkowita onzacza prawdę w sensie logicznym. Więc -1, 2 i -200 również oznaczają prawdę w sensie logicznym.
[%hardbreaks]

Zauważ, że stałe `true` i `false` pisane są małymi literami w przeciwnieństwie do `HIGH`, `LOW`, `INPUT`, i `OUTPUT`.
[%hardbreaks]

[float]
== Definiowanie poziomów logicznych na stykach: HIGH i LOW
Podczas odczytu lub zapisu na styku cyfrowym są tylko dwie możliwe wartości, które styk może przyjąć/być ustawiony: `HIGH` (wysoki) i `LOW` (niski).

[float]
=== HIGH
Znaczenie stanu wysokiego `HIGH` (w odniesieniu do styku) jest nieco inne, w zależności od tego czy styk jest ustawiony jako wejście (`INPUT`) lub wyjście (`OUTPUT`). Jeżeli styk ustawione jest jako wejście `INPUT` przy pomocy link:../../../functions/digital-io/pinmode[pinMode()], i odczytywany poprzez link:../../../functions/digital-io/digitalread[digitalRead()], Arduino (ATmega) zgłasza stan wysoki(`HIGH`) jeśli:

  - na styku występuje napięcie większe niż 3.0V (płytki zasilane napięciem 5V)
  - na styku występuje napięcie większe niż 2.0V (płytki 3.3V)
[%hardbreaks]

Styk można również skonfigurować jako wejście (INPUT) przy pomocy `pinMode()`, a następnie ustawiony w stan wysoki przy pomocy link:../../../functions/digital-io/digitalwrite[digitalWrite()]. Zostaną włączone wewnętrzne rezystory podciągające (20k), które _podciągną_ styk wejściowy aby odczytywał stan wysoki, chyba, że zostanie sprowadzony w stan niski przez układ zewnętrzny. Można to też zrobić inaczej, podając argument `INPUT_PULLUP` w funkcji `pinMode()`, as explained in more detail in the section "Defining Digital Pins modes: INPUT, INPUT_PULLUP, and OUTPUT" further below.
[%hardbreaks]

Kiedy styk zostanie skonfigurowany jako wyjście (OUTPUT) poprzez `pinMode()`, i ustawiony w stan wysoki (`HIGH`) poprzez `digitalWrite()`, na styku pojawi się napięcie:

  - 5 woltów (płytki 5V)
  - 3,3 wolta (płytki 3,3V)

W tym stanie może być źródłem prądu np. może zapalić diodę świecącą podłączoną poprzez szeregowy rezystor do masy (`minusa` zasilania).
[%hardbreaks]

[float]
=== LOW
Znaczenie stanu `LOW` jest różne w zależności od tego czy styk był ustawiony jako wejściowy (`INPUT`) czy wyjściowy (`OUTPUT`). W przypadku gdy styk jest zdefiniowany jako wejściowy (`INPUT`) przy pomocy `pinMode()`, to odczyt za pomocą `digitalRead()`, na Arduino (ATmega) zgłosi stan niski (LOW) jeżeli:

  - na styku obecne będzie napięcie niższe niż 1,5V (płytki 5V)
  - na styku obecne będzie napięcie niższe niż 1,0V (około) (płytki 3,3V)

Skonfigurowanie styku jako wyjściowego (`OUTPUT`) poprzez `pinMode()` i ustawienie w stan niski (`LOW`) poprzez `digitalWrite()`, spowoduje ustawienie na styku napięcia 0 wolt (zarówno płytki 5V jak i 3,3V). W tym stanie może pobierać prąd tzn. np. zapalić diodę świecącą podłączoną poprzez szeregowy rezystor do +5 woltów (lub +3,3 wolta).
[%hardbreaks]

[float]
== Definiowanie trybów pracy styków cyfrowych: INPUT, INPUT_PULLUP, i OUTPUT
Styki cyfrowe mogą być używane jako wejście (`INPUT`), wejście z podciągnięciem (`INPUT_PULLUP`), lub wyjście (`OUTPUT`). Zmiana trybu pracy styku poprzez `pinMode()` zmienia jego zachowanie elektryczne.

[float]
=== Styki skonfigurowane jako wejście
Styki Arduino (ATmega) skonfigurowane jako wejście (`INPUT`) za pomocą `pinMode()` są w tak zwanym stanie _wysokiej impedancji_. Styki skonfigurowane jako wejście (`INPUT`) stanowią niezwykle małe obciążenie dla układu do którego są podłączone, porównywalne z szeregowo podłączonym rezystorem 100-megaomowym. Jest to przydatne do odczytywania czujnika.
[%hardbreaks]

Jeśli masz styk skonfigurowany jako wejście, a do niego podłączony przełącznik, którego stan chcesz odczytać i jeżeli przełącznik będzie w stanie wyłączonym, to styk wejściowy będzie "pływający" czyli będzie dostarczał nieprzewidywalnych wyników. Aby zapewnić w takiej sytuacji prawidłowy odczyt należy zastosować rezystor podciągający w górę lub w dół. Zadaniem tego rezystora będzie podciągnięcie styku do znanego stanu w przypadku przełącznika w stanie otwartym. Zwykle stosuje się rezystor 10 kiloomów, ponieważ jest to wystarczająco niska wartość, aby skutecznie zapobiegać pływającemu wejściu, a jednocześnie wystarczająco wysoka wartość, aby nie pobierać zbyt dużego prądu, gdy przełącznik jest zamknięty. Dalsze informacje znajdziesz w przewodniku http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^].
[%hardbreaks]

Jeśli użyty będzie rezystor podciągający w dół, styk wejściowy przyjmie wartość `LOW`, gdy przełącznik będzie otwarty, i `HIGH`, gdy przełącznik będzie zamknięty.
[%hardbreaks]

Jeśli użyty będzie rezystor podciągający w górę, styk wejściowy przyjmie wartość `HIGH`, gdy przełącznik będzie otwarty, i `LOW`, gdy przełącznik będzie zamknięty.
[%hardbreaks]

[float]
=== Styki skonfigurowane jako podciągnięte w górę
Mikrokontroler ATmega w Arduino ma wewnętrzne rezystory podciągające w górę (rezystory łączące się wewnętrznie z plusem zasilania), do których można uzyskać dostęp. Jeśli wolisz używać ich zamiast zewnętrznych rezystorów podciągających, możesz użyć argumentu `INPUT_PULLUP` w poleceniu `pinMode ()`.
[%hardbreaks]

Przykład zastosowania znajdziesz w przewodniku http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^].
[%hardbreaks]

Podłączenie ujemnego napięcia lub o większej wartości niż napięcie zasilania (5V lub 3V) do styków skonfigurowanych jako wejścia za pomocą „INPUT” lub „INPUT_PULLUP” może spowodować ich uszkodzenie lub zniszczenie.
[%hardbreaks]

[float]
=== Styki skonfigurowane jako wyjście
Styki skonfigurowane jako  wyjście (`OUTPUT`) przy pomocy `pinMode()` są w tak zwanym stanie _niskiej impedancji_. Oznacza to, że mogą one dostarczać znaczną ilość prądu do innych obwodów. Styki ATmega mogą dostarczać (być źródłem) lub odbierać (być odbiornikiem) do 40 mA (miliamperów) prądu do/z innych urządzeń/obwodów. To czyni je przydatnymi do zasilania diod świecących (LED), ponieważ te diody zwykle zużywają poniżej 40 mA. Obciążenia większe niż 40 mA (np. silniki) będą wymagały tranzystora lub innego obwodu pośredniczącego.
[%hardbreaks]

Styki skonfigurowane jako wyjścia mogą zostać uszkodzone lub zniszczone, jeśli zostaną podłączone do plusa lub minusa zasilania.
[%hardbreaks]

[float]
== Definicja wbudowanych: LED_BUILTIN
Większość płytek Arduino posiada styk, który poprzez rezystor szeregowy połączony jest z diodą świecącą znajdującą się na płytce. Stała `LED_BUILTIN` to numer styku, do którego podłączona jest ta dioda świecąca. Większość płytek ma tę diodę podłączoną do cyfrowego styku nr 13.

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

--
// KONIEC SEKCJI JAK UŻYWAĆ

// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
