---
title: Stałe całkowite
categories: [ "Variables" ]
subCategories: [ "Constants" ]
---





= Stałe całkowite


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Stałe całkowite to po prostu używane w szkicu liczby (jak np. 123). Domyślnie te liczby traktowane są jako link:../../data-types/int[int] (całkowite) ale możesz to zmienić za pomocą modyfikatorów U i L (patrz poniżej).
[%hardbreaks]

Zwykle stałe całkowite są traktowane jako liczby całkowite o podstawie 10 (dziesiętne), ale w celu użycia liczb o innych podstawach należy użyć specjalnej notacji (znaków formatujących).
[%hardbreaks]

|===
|Podstawa |Przykład |Znak formatu |Komentarz

|10 (dziesiętna)
|123
|nic
|

|2 (dwójkowa)
|B1111011
|przedrostek 'B'
|działa tylko z wartościami 8-bitowymi (od 0 do 255)   dopuszczalne znaki to 0 i 1

|8 (ósemkowa)
|0173
|przedrostek "0"
|dopuszczalne znaki: 0-7

|16 (szesnastkowa)
|0x7B
|przedrostek "0x"
|dopuszczalne znaki: 0-9, A-F, a-f
|===
[%hardbreaks]

--
// KONIEC SEKCJI OPISOWEJ



// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--
[float]
== Dziesiętne (o podstawie 10)
Jest to podstawowy, znany ci system liczbowy. Zakłada się, że stałe bez przedrostków są w formacie dziesiętnym.

[float]
=== Przykładowy kod:
[source,arduino]
----
n = 101;  // dziesiętne 101 ((1 * 10^2) + (0 * 10^1) + 1)
----
[%hardbreaks]

[float]
== Dwójkowe (o podstawie 2)
Dopuszczalne są tylko znaki 0 i 1.

[float]
=== Przykładowy kod:
[source,arduino]
----
n = B101; // dziesiętnie 5 ((1 * 2^2) + (0 * 2^1) + 1)
----

Zapis dwójkowy działa tylko dla bajtów (liczb 8-bitowych) od 0 (B0) do 255 (B11111111). Jeśli potrzebujesz wprowadzić liczbę całkowitą (16 bitową) w formacie dwójkowym możesz to zrobić następująco:
[source,arduino]
----
mojaCalkowita = (B11001100 * 256) + B10101010;  // B11001100 to bardziej znaczący bajt`
----
[%hardbreaks]

[float]
== Ósemkowe (o podstawie 8)
Dopuszczalne są tylko znaki od 0 do 7. Wartości ósemkowe są oznaczane przedstostkiem "0" (zero).

[float]
=== Przykładowy kod:
[source,arduino]
----
n = 0101; // dziesiętnie 65 ((1 * 8^2) + (0 * 8^1) + 1)
----
Możliwe jest wygenerowanie trudnego do znalezienia błędu poprzez (niezamierzone) umieszczenie zera przed stałą i tym samym zmuszienie kompilatora do interpretacji stałej jako ósemkowej.
[%hardbreaks]

[float]
== Szesnastkowe (o podstawie 16)
Dopuszczalne znaki to cyfry od 0 do 9 i litery od A do F; A ma wartość 10, B wartość 11, oż do F, które ma wartość 15. Wartości szesnastkowe oznaczane są przedrostkiem "0x". Zauważ, że litery A-F mogą być wielkie (A-F) jak i małe (a-f).

[float]
=== Przykładowy kod
[source,arduino]
----
n = 0x101;  // dziesiętnie 257 ((1 * 16^2) + (0 * 16^1) + 1)
----
[%hardbreaks]


[float]
=== Uwagi i ostrzeżenia
*Znaki formatujące U i L:*

Domyślnie stała całkowita traktowana jest jak każda liczba całkowita z określonymi ograniczeniami. Aby określić inny format danych dla stałej całkowitej zrób to za pomocą:

  - 'u' lub 'U' aby wymusić zapis stałej w formacie bez znaku. Przykład: 33u
  - 'l' lub 'L' aby wymusic zapis stałej w formacie długim. Przykład: 100000L
  - 'ul' lub 'UL' aby wymusić zapis stałej w formacie długim bez znaku. Przykład: 32767ul

[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ




// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
