---
title: Serial.available()
---

= available()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Pobiera liczbę bajtów (znaków) dostępnych do odczytu z portu szeregowego. Są to dane, które już dotarły i są przechowywane w buforze odbioru szeregowego (który zawiera 64 bajty). 

`Serial.available()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.available()`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial].


[float]
=== Wartości zwracane
Liczba bajtów dostępnych do odczytania.

--
// KONIEC SEKCJI OPISOWEJ

// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--
[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Poniższy program zwraca znak odebrany przez port szeregowy

[source,arduino]
----
int przychBajt = 0; // dla przychodzących danych szeregowych

void setup() {
  Serial.begin(9600); // otwiera port szeregowy, ustawia szybkość transmisji danych na 9600 bitów na sekundę
}

void loop() {
  // odpowiadaj tylko, gdy otrzymasz dane:
  if (Serial.available() > 0) {
    // odczytaj przychodzący bajt:
    przychBajt = Serial.read();

    // powiedz, co masz:
    Serial.print("Odebrane: ");
    Serial.println(przychBajt, DEC);
  }
}
----
[%hardbreaks]

*przykład dla Arduino Mega:*
Ten program przesyła dane otrzymane z jednego portu szeregowego Arduino Mega do innego. Można to wykorzystać np. do podłączenia urządzenia szeregowego do komputera poprzez płytkę Arduino. 

[source,arduino]
----
void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);
}

void loop() {
  // odczytaj z portu 0, wysyłaj do portu 1:
  if (Serial.available()) {
    int przychBajt = Serial.read();
    Serial1.print(przychBajt, DEC);
  }
  // odczytaj z portu 1, wysyłaj do portu 0:
  if (Serial1.available()) {
    int przychBajt = Serial1.read();
    Serial.print(przychBajt, DEC);
  }
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../begin[begin()] +
* #JĘZYK# link:../end[end()] +
* #JĘZYK# link:../read[read()] +
* #JĘZYK# link:../peek[peek()] +
* #JĘZYK# link:../flush[flush()] +
* #JĘZYK# link:../print[print()] +
* #JĘZYK# link:../println[println()] +
* #JĘZYK# link:../write[write()] +
* #JĘZYK# link:../serialevent[SerialEvent()] +
* #JĘZYK# link:../../stream/streamavailable[Stream.available()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
