---
title: Serial.begin()
---




= begin()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Ustawia szybkość transmisji danych w bitach na sekundę (bodach) dla szeregowej transmisji danych. Aby komunikować się z monitorem portu szeregowego, upewnij się, że używasz jednej z szybkości transmisji wymienionych w menu w prawym dolnym rogu jego ekranu. Możesz jednak określić inne szybkości - na przykład, aby komunikować się przez styki 0 i 1 z elementem wymagającym określonej szybkości transmisji. 

Opcjonalny drugi parametr konfiguruje dane, parzystość i bity stopu. Wartość domyślna to 8 bitów danych, bez parzystości, jeden bit stopu. 
[%hardbreaks]


[float]
=== Składnia
`_Serial_.begin(szybkość)` +
`_Serial_.begin(szybkość, konfiguracja)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`szybkość`: w bitach na sekundę (bodach). Dozwolone typy danych: `long`. +
`konfiguracja`: bity danych, parzystość i bity stopu. Poprawne wartości to: +
`SERIAL_5N1` +
`SERIAL_6N1` +
`SERIAL_7N1` +
`SERIAL_8N1` (domyślnie) +
`SERIAL_5N2` +
`SERIAL_6N2` +
`SERIAL_7N2` +
`SERIAL_8N2` +
`SERIAL_5E1` +
`SERIAL_6E1` +
`SERIAL_7E1` +
`SERIAL_8E1` +
`SERIAL_5E2` +
`SERIAL_6E2` +
`SERIAL_7E2` +
`SERIAL_8E2` +
`SERIAL_5O1` +
`SERIAL_6O1` +
`SERIAL_7O1` +
`SERIAL_8O1` +
`SERIAL_5O2` +
`SERIAL_6O2` +
`SERIAL_7O2` +
`SERIAL_8O2`


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
void setup() {
    Serial.begin(9600); // otwiera port szeregowy, ustawia szybkość transmisji danych na 9600 bitów na sekundę
}

void loop() {}
----
[%hardbreaks]

*przykład dla Arduino Mega:*
[source,arduino]
----
// Arduino Mega przy użyciu wszystkich czterech portów szeregowych 
// (Serial, Serial1, Serial2, Serial3),
// z różnymi szybkościami transmisji:

void setup() {
  Serial.begin(9600);
  Serial1.begin(38400);
  Serial2.begin(19200);
  Serial3.begin(4800);

  Serial.println("Serwus Komputer");
  Serial1.println("Serwus Serial 1");
  Serial2.println("Serwus Serial 2");
  Serial3.println("Serwus Serial 3");
}
void loop() {}
----
[%hardbreaks]
Podziękowania dla Jeffa Graya za przykład dla Mega


[float]
=== Uwagi i ostrzeżenia
Dla portów szeregowych w urządzeniach klasy USB (np. `Serial` na płycie Leonardo), `Serial.begin()` nie ma znaczenia. Do komunikacji szeregowej z tymi portami można użyć dowolnej szybkości transmisji w dowolnej konfiguracji. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial].
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ
