---
title: Serial.findUntil()
---




= Serial.findUntil()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`Serial.findUntil()` odczytuje dane z bufora szeregowego do momentu znalezienia ciągu docelowego o określonej długości lub ciągu kończącego.

Funkcja zwraca wartość `true`, jeśli zostanie znaleziony ciąg docelowy, lub `false`, jeśli upłynie limit czasu.

`Serial.findUntil()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.findUntil(cel, koniec)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`cel`: poszukiwany ciąg. Dozwolone typy danych: `char`. +
`koniec`: ciąg kończący wyszukiwanie. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
Typ danych: `bool`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../stream[stream] +
* #JĘZYK# link:../../stream/streamfinduntil[stream.findUntil()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
