---
title: Serial.find()
---




= Serial.find()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Serial.find() odczytuje dane z bufora szeregowego do momentu znalezienia celu. Funkcja zwraca wartość `true`, jeśli cel zostanie znaleziony, `false`, jeśli upłynie limit czasu. 

Serial.find() dziedziczy po klasie link:../../stream[stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.find(cel)` +
`_Serial_.find(cel, długość)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`cel`: poszukiwany ciąg. Dozwolone typy danych: `char`. +
`długość`: długość celu. Dozwolone typy danych: `size_t`.


[float]
=== Wartości zwracane
Typ danych: `bool`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../stream[stream] +
* #JĘZYK# link:../../stream/streamfind[stream.find()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
