---
title: if(Serial)
---




= if (Serial)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Indicates if the specified Serial port is ready.

On the boards with native USB, `if (Serial)` (or `if(SerialUSB)` on the Due) indicates whether or not the USB CDC serial connection is open. For all other boards, and the non-USB CDC ports, this will always return true.

This was introduced in Arduino IDE 1.0.1.
[%hardbreaks]


[float]
=== Składnia
`if (Serial)`


[float]
=== Parametry
None


[float]
=== Wartości zwracane
Zwraca wartość `true`, jeśli określony port szeregowy jest dostępny. Zwróci `false`, jeśli zapytasz o połączenie szeregowe urządzenie USB płyty Leonardo, zanim będzie gotowe. Typ danych: „bool”. 

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
void setup() {
  // Zainicjuj port szeregowy i poczekaj na jego otwarcie:
  Serial.begin(9600);
  while (!Serial) {
    ; // poczekaj na połączenie portu szeregowego. Potrzebny do macierzystego portu USB 
  }
}

void loop() {
  // normalne działanie
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ
