---
title: if(Serial)
---




= if (Serial)


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wskazuje, czy określony port szeregowy jest gotowy.

Na płytach z macierzystym USB, `if (Serial)` (lub `if(SerialUSB)` w Due) wskazuje, czy połączenie szeregowe urządzenia klasy USB jest otwarte. W przypadku wszystkich innych płyt i portów innych klas niż USB zawsze zwróci `true` 

Zostało to wprowadzone w Arduino IDE 1.0.1.
[%hardbreaks]


[float]
=== Składnia
`if (Serial)`


[float]
=== Parametry
Brak


[float]
=== Wartości zwracane
Zwraca wartość `true`, jeśli określony port szeregowy jest dostępny. Zwróci `false`, jeśli zapytasz o połączenie szeregowe urządzenie USB płyty Leonardo, zanim będzie gotowe. Typ danych: `bool`. 

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
void setup() {
  // Zainicjuj port szeregowy i poczekaj na jego otwarcie:
  Serial.begin(9600);
  while (!Serial) {
    ; // poczekaj na połączenie portu szeregowego. Potrzebny do macierzystego portu USB 
  }
}

void loop() {
  // normalne działanie
}
----

--
// KONIEC SEKCJI JAK UŻYWAĆ
