---
title: Serial.parseInt()
---




= parseInt()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Szuka następnej prawidłowej liczby całkowitej w przychodzącej transmisji szeregowej. Funkcja kończy działanie, jeśli upłynie limit czasu (zobacz link:../settimeout[Serial.setTimeout()]).

`Serial.parseInt()` dziedziczy po klasie link:../../stream[Stream].


W szczególności:

* Analiza zatrzymuje się, gdy żadne znaki nie zostały odczytane w konfigurowanym limicie czasu lub odczytywana została wartość niecyfrowa; +
* Jeśli w momencie przekroczenia limitu czasu (patrz Serial.setTimeout ()) nie zostały odczytane żadne prawidłowe cyfry, zwracane jest 0;
[%hardbreaks]


[float]
=== Składnia
`_Serial_.parseInt()` +
`_Serial_.parseInt(oczekiwany)` +
`_Serial_.parseInt(oczekiwany, ignorowany)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na stronie głównej klasy link:../../serial[Serial]. +
`oczekiwany`: sposób wyszukiwania liczby całkowitej. Dozwolone typy danych: `LookaheadMode`. Dozwolone wartości parametru `oczekiwany`:

* `SKIP_ALL`: wszystkie znaki inne niż cyfry lub znak minus są ignorowane podczas skanowania strumienia w poszukiwaniu liczby całkowitej. To jest tryb domyślny.
* `SKIP_NONE`: Nic nie jest pomijane, a strumień nie jest pobierany, chyba że pierwszy oczekujący znak jest prawidłowy.
* `SKIP_WHITESPACE`: Pomijane są tylko znaki tabulatora, odstępu, nowego wiersza i powrotu karetki.

`ignorowany`: używany do pominięcia wskazanego znaku w wyszukiwaniu. Na przykład do pominięcia separatora grup trzycyfrowych (tysięcy). Dozwolone typy danych: `char`


[float]
=== Wartości zwracane
Następna prawidłowa liczba całkowita. Typ danych: `long`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../begin[begin()] +
* #JĘZYK# link:../end[end()] +
* #JĘZYK# link:../available[available()] +
* #JĘZYK# link:../read[read()] +
* #JĘZYK# link:../peek[peek()] +
* #JĘZYK# link:../flush[flush()] +
* #JĘZYK# link:../print[print()] +
* #JĘZYK# link:../println[println()] +
* #JĘZYK# link:../write[write()] +
* #JĘZYK# link:../serialevent[SerialEvent()] +
* #JĘZYK# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
