---
title: Serial.parseFloat()
---




= Serial.parseFloat()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`Serial.parseFloat()` zwraca pierwszą poprawną liczbę zmiennoprzecinkową z bufora transmisji szeregowej. `parseFloat()` zakończy pierwszy znak, który nie jest liczbą zmiennoprzecinkową. Funkcja kończy działanie, jeśli upłynie limit czasu (zobacz link:../settimeout[Serial.setTimeout()]).

`Serial.parseFloat()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.parseFloat()` +
`_Serial_.parseFloat(oczekiwany)` +
`_Serial_.parseFloat(oczekiwany, ignorowany)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`oczekiwany`: sposób wyszukiwania liczby zmiennoprzecinkowej. Dozwolone typy danych: `LookaheadMode`. Dozwolone wartości parametru `oczekiwany`:

* `SKIP_ALL`: wszystkie znaki inne niż znak minus, kropka dziesiętna lub cyfry są ignorowane podczas analizowania strumienia w poszukiwaniu liczby zmiennoprzecinkowej. To jest domyślny sposób działania.
* `SKIP_NONE`: Nic nie jest pomijane, a strumień nie jest pobierany, chyba że pierwszy oczekujący znak jest prawidłowy.
* `SKIP_WHITESPACE`: Pomijane są tylko znaki tabulatora, odstępu, nowego wiersza i powrotu karetki.

`ignorowany`: używany do pominięcia wskazanego znaku w wyszukiwaniu. Na przykład do pominięcia separatora grup trzycyfrowych (tysięcy). Dozwolone typy danych: `char`


[float]
=== Wartości zwracane
Typ danych: `float`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../stream[stream()]
* #JĘZYK# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
