---
title: Serial.parseInt()
---




= parseInt()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Szuka następnej prawidłowej liczby całkowitej w przychodzącej transmisji szeregowej. Funkcja kończy się, jeśli upłynie limit czasu (zobacz link:../settimeout[Serial.setTimeout()]).

`Serial.parseInt()` dziedziczy po klasie link:../../stream[Stream].


W szczególności:

* Analiza zatrzymuje się, gdy żadne znaki nie zostały odczytane w konfigurowanym limicie czasu lub odczytywana została wartość niecyfrowa; +
* Jeśli w momencie przekroczenia limitu czasu (patrz Serial.setTimeout ()) nie zostały odczytane żadne prawidłowe cyfry, zwracane jest 0;
[%hardbreaks]


[float]
=== Składnia
`_Serial_.parseInt()` +
`_Serial_.parseInt(oczekiwany)` +
`_Serial_.parseInt(oczekiwany, ignorowany)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej karty na stronie głównej link:../../serial[Serial]. +
`lookahead`: the mode used to look ahead in the stream for an integer. Allowed data types: `LookaheadMode`. Allowed `lookahead` values:

* `SKIP_ALL`: all characters other than digits or a minus sign are ignored when scanning the stream for an integer. This is the default mode.
* `SKIP_NONE`: Nothing is skipped, and the stream is not touched unless the first waiting character is valid.
* `SKIP_WHITESPACE`: Only tabs, spaces, line feeds, and carriage returns are skipped.

`ignore`: used to skip the indicated char in the search. Used for example to skip thousands divider. Allowed data types: `char`


[float]
=== Wartości zwracane
The next valid integer. Data type: `long`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../begin[begin()] +
* #JĘZYK# link:../end[end()] +
* #JĘZYK# link:../available[available()] +
* #JĘZYK# link:../read[read()] +
* #JĘZYK# link:../peek[peek()] +
* #JĘZYK# link:../flush[flush()] +
* #JĘZYK# link:../print[print()] +
* #JĘZYK# link:../println[println()] +
* #JĘZYK# link:../write[write()] +
* #JĘZYK# link:../serialevent[SerialEvent()] +
* #JĘZYK# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
