---
title: Serial.peek()
---




= peek()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Zwraca następny bajt (znak) w przychodzących danych szeregowych bez usuwania ich z wewnętrznego bufora szeregowego. Oznacza to, że kolejne wywołania funkcji `peek()` zwrócą ten sam znak, podobnie jak następne wywołanie metody `read()`.

`Serial.peek()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.peek()`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial].


[float]
=== Wartości zwracane
Pierwszy dostępny bajt w przychodzących danych szeregowych (lub -1, jeśli żadne dane nie są dostępne). Typ danych: `int`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../begin[begin()] +
* #JĘZYK# link:../end[end()] +
* #JĘZYK# link:../available[available()] +
* #JĘZYK# link:../read[read()] +
* #JĘZYK# link:../peek[peek()] +
* #JĘZYK# link:../flush[flush()] +
* #JĘZYK# link:../print[print()] +
* #JĘZYK# link:../println[println()] +
* #JĘZYK# link:../write[write()] +
* #JĘZYK# link:../serialevent[SerialEvent()] +
* #JĘZYK# link:../../stream/streampeek[Stream.peek()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
