---
title: Serial.println()
---




= println()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Drukuje dane do portu szeregowego jako czytelny dla człowieka tekst ASCII zakończony znakiem powrotu karetki (ASCII 13, lub '\r') oraz znakiem nowej linii (ASCII 10, lub '\n'). To polecenie ma taką samą postać jak link:../print[Serial.print()].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.println(wart)` +
`_Serial_.println(wart, format)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`wart`: wartość do wydrukowania. Dozwolone typy danych: dowolny typ danych. +
`format`: określa podstawę liczb (dla całkowitych typów danych) lub liczbę miejsc po przecinku (dla typów zmiennoprzecinkowych).


[float]
=== Wartości zwracane
`println()` zwraca liczbę zapisanych bajtów, chociaż odczyt tej liczby jest opcjonalny. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
/*
 Odczytywane jest wejście analogowe na styku numer 0 i drukowana jest ta wartość.
 dnia 24 marca 2006
 stworzył Tom Igoe
 */

int wartAnalogowa = 0;    // zmienna do przechowywania wartości analogowej

void setup() {
  // otwórz port szeregowy przy prędkości 9600 bps:
  Serial.begin(9600);
}

void loop() {
  // odczytaj wejście analogowe na styku 0:
  wartAnalogowa = analogRead(0);

  // drukowanie w wielu formatach:
  Serial.println(wartAnalogowa);       // drukuj jako liczbę dziesiętną zakodowaną w ASCII
  Serial.println(wartAnalogowa, DEC);  // drukuj jako liczbę dziesiętną zakodowaną w ASCII
  Serial.println(wartAnalogowa, HEX);  // drukuj jako liczbę szesnastkową zakodowaną w ASCII
  Serial.println(wartAnalogowa, OCT);  // drukuj jako liczbę ósemkową zakodowaną w ASCII
  Serial.println(wartAnalogowa, BIN);  // drukuj jako liczbę dwójkową zakodowaną w ASCII

  // opóźnienie 10 milisekund przed następnym odczytem:
  delay(10);
}
----
[%hardbreaks]

[float]
=== Uwagi i Ostrzeżenia
Informacje na temat asynchroniczności `Serial.println()`, można znaleźć w sekcji Uwagi i ostrzeżenia link:../write#howtouse[strony dokumentacji Serial.write()].

--
// KONIEC SEKCJI JAK UŻYWAĆ
