---
title: Serial.readBytes()
---




= Serial.readBytes()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`Serial.readBytes()` odczytuje znaki z portu szeregowego do bufora. Funkcja kończy działanie po odczytaniu określonej długości lub po przekroczeniu limitu czasu (zobacz link:../settimeout[Serial.setTimeout()]).

`Serial.readBytes()` zwraca liczbę znaków umieszczonych w buforze. 0 oznacza, że nie znaleziono prawidłowych danych.

`Serial.readBytes()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.readBytes(bufor, ile)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`bufor`: bufor do przechowywania bajtów. Dozwolone typy danych: tablica typów `char` lub `byte`. +
`ile`: liczba bajtów do odczytania. Dozwolone typy danych: `int`.


[float]
=== Wartości zwracane
Liczba bajtów umieszczonych w buforze. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../stream[stream]
* #JĘZYK# link:../../stream/streamreadbytes[stream.readBytes()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
