---
title: Serial.readStringUntil()
---




= readStringUntil()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`readStringUntil()` odczytuje znaki z bufora szeregowego i umieszcza w ciągu znaków. Funkcja kończy się, jeśli upłynie limit czasu (zobacz link:../settimeout[setTimeout()]).

`Serial.readStringUntil()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.readStringUntil(koniec)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`koniec`: znak do wyszukania. Dozwolone typy danych: `char`.


[float]
=== Wartości zwracane
Cały ciąg odczytywany jest z bufora szeregowego, do znaku kończącego.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i Ostrzeżenia
Znak kończący jest usuwany z bufora szeregowego.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../serial[Serial]
* #JĘZYK# link:../begin[begin()]
* #JĘZYK# link:../end[end()]
* #JĘZYK# link:../available[available()]
* #JĘZYK# link:../read[read()]
* #JĘZYK# link:../peek[peek()]
* #JĘZYK# link:../flush[flush()]
* #JĘZYK# link:../print[print()]
* #JĘZYK# link:../println[println()]
* #JĘZYK# link:../write[write()]
* #JĘZYK# link:../serialevent[SerialEvent()]
* #JĘZYK# link:../../stream/streamparsefloat[stream.parseFloat()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
