---
title: Serial.readBytesUntil()
---




= Serial.readBytesUntil()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Serial.readBytesUntil() reads characters from the serial buffer into an array. The function terminates if the terminator character is detected, the determined length has been read, or it times out (see link:../settimeout[Serial.setTimeout()]). The function returns the characters up to the last character before the supplied terminator. The terminator itself is not returned in the buffer.

`Serial.readBytesUntil()` returns the number of characters read into the buffer. A 0 means no valid data was found.

`Serial.readBytesUntil()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Składnia
`_Serial_.readBytesUntil(character, buffer, length)`


[float]
=== Parametry
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:../../serial[Serial main page]. +
`character`: the character to search for. Allowed data types: `char`. +
`buffer`: the buffer to store the bytes in. Allowed data types: array of `char` or `byte`s. +
`length`: the number of bytes to read. Allowed data types: `int`.


[float]
=== Wartości zwracane
Data type: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i Ostrzeżenia
Znak końca jest usuwany z bufora szeregowego.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../stream[Stream]
* #JĘZYK# link:../../stream/streamreadbytesuntil[Stream.readBytesUntil()]

--
// SEE ALSO SECTION ENDS
