---
title: Serial.readBytesUntil()
---




= Serial.readBytesUntil()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Serial.readBytesUntil() wczytuje do tablicy znaki z bufora szeregowego. Funkcja kończy działanie po wykryciu znaku kończącego, odczytaniu określonej długości lub przekroczeniu limitu czasu (zobacz link:../settimeout[Serial.setTimeout()]). Funkcja zwraca znaki do ostatniego znaku przed podanym znakiem kończącym. Sam zna kończący nie jest zwracany w buforze.

`Serial.readBytesUntil()` zwraca liczbę znaków odczytanych do bufora. 0 oznacza, że nie znaleziono prawidłowych danych.

`Serial.readBytesUntil()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.readBytesUntil(character, buffer, length)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`znak`: znak do wyszukania. Dozwolone typy danych: `char`. +
`bufor`: bufor do przechowywania bajtów. Dozwolone typy danych: tablica typów `char` lub `byte`. +
`ile`: liczba bajtów do odczytania. Dozwolone typy danych: `int`.


[float]
=== Wartości zwracane
Typ Danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i Ostrzeżenia
Znak końca jest usuwany z bufora szeregowego.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../stream[Stream]
* #JĘZYK# link:../../stream/streamreadbytesuntil[Stream.readBytesUntil()]

--
// SEE ALSO SECTION ENDS
