---
title: serialEvent()
---




= serialEvent()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wywoływane, gdy dostępne są dane. Użyj `Serial.read()` aby przechwycić te dane.
[%hardbreaks]


[float]
=== Składnia

[source,arduino]
----
void serialEvent() {
  // polecenia
}
----
Dla płytek z dodatkowymi portami szeregowymi (zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]):
[source,arduino]
----
void serialEvent1() {
  // polecenia
}

void serialEvent2() {
  // polecenia
}

void serialEvent3() {
  // polecenia
}
----


[float]
=== Parametry
`polecenia`: wszelkie prawidłowe polecenia


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i Ostrzeżenia
`serialEvent()` nie działa na Leonardo, Micro i Yún.

`serialEvent()` i `serialEvent1()` nie działa na płytkach Arduino SAMD

`serialEvent()`, `serialEvent1()``serialEvent2()`, i `serialEvent3()`  nie działa na Arduino Due.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="example"]
* #PRZYKŁAD# http://arduino.cc/en/Tutorial/SerialEvent[Serial Event^]

[role="language"]
* #JĘZYK# link:../begin[begin()]
* #JĘZYK# link:../end[end()]
* #JĘZYK# link:../available[available()]
* #JĘZYK# link:../read[read()]
* #JĘZYK# link:../peek[peek()]
* #JĘZYK# link:../flush[flush()]
* #JĘZYK# link:../print[print()]
* #JĘZYK# link:../println[println()]
* #JĘZYK# link:../write[write()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
