---
title: Serial.setTimeout()
---




= Serial.setTimeout()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`Serial.setTimeout()` ustawia maksymalną ilość milisekund oczekiwania na dane szeregowe. Domyślnie jest to 1000 milisekund.

`Serial.setTimeout()` dziedziczy po klasie link:../../stream[Stream].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.setTimeout(czas)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`czas`: limit czasu w milisekundach. Dozwolone typy danych: `long`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i Ostrzeżenia
Funkcje szeregowe, które używają wartości limitu czasu ustawionej przez `_Serial_.setTimeout()`:

* `_Serial_.find()`
* `_Serial_.findUntil()`
* `_Serial_.parseInt()`
* `_Serial_.parseFloat()`
* `_Serial_.readBytes()`
* `_Serial_.readBytesUntil()`
* `_Serial_.readString()`
* `_Serial_.readStringUntil()`

[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #JĘZYK# link:../../stream[stream]
* #JĘZYK# link:../../stream/streamsettimeout[stream.setTimeout()]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
