---
title: Serial.write()
---

= write()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Zapisuje dane binarne do portu szeregowego. Te dane są wysyłane jako bajt lub seria bajtów; aby wysłać znaki reprezentujące poszczególne cyfry z liczby, zamiast tego użyj funkcji link:../print[print()].
[%hardbreaks]


[float]
=== Składnia
`_Serial_.write(wart)` +
`_Serial_.write(napis)` +
`_Serial_.write(buf, dlug)`


[float]
=== Parametry
`_Serial_`: obiekt portu szeregowego. Zobacz listę dostępnych portów szeregowych dla każdej płytki na link:../../serial[stronie głównej klasy Serial]. +
`wart` : wartość do wysłania jako pojedynczy bajt. +
`napis`: ciąg do wysłania jako seria bajtów. +
`buf`  : tablica do wysłania jako seria bajtów. +
`dlug` : liczba bajtów tablicy do wysłania.


[float]
=== Wartości zwracane
`write()` zwróci liczbę zapisanych bajtów, chociaż odczyt tej liczby jest opcjonalny. Typ danych: `size_t`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--
[float]
=== Program przykładowy
// Poniżej dodaj przykładowy program i opisz jego działanie   ►►►►► TA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄


[source,arduino]
----
void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.write(45); // wyślij bajt o wartości 45

  int bajtowWyslanych = Serial.write(“hello”);  // wyślij ciąg "hello" i zwróć długość łańcucha.
}
----
[%hardbreaks]

[float]
=== Uwagi i Ostrzeżenia
Od Arduino IDE 1.0 transmisja szeregowa jest asynchroniczna. 
Jeśli w buforze transmisji jest wystarczająco dużo wolnego miejsca, to `Serial.write()` powróci przed wysłaniem jakichkolwiek znaków przez łącze szeregowe. 
Jeśli bufor transmisji jest pełny, wówczas `Serial.write()` będzie zablokowane, dopóki w buforze nie będzie wystarczającej ilości miejsca. Aby uniknąć blokowania wywołań `Serial.write()`, możesz najpierw sprawdzić ilość wolnego miejsca w buforze transmisji za pomocą  link:../availableforwrite[availableForWrite()].

--
// KONIEC SEKCJI JAK UŻYWAĆ
