---
title: pulseInLong()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= pulseInLong()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
`pulseInLong()` jest alternatywą do link:../pulsein[pulseIn()], która lepiej radzi sobie w przypadku długich impulsów i podczas przerwań..

Odczytuje impuls (wysoki `HIGH` lub niski `LOW`) pojawiający sie na styku. Na przykład, jeśli `wartość` jest `HIGH`, `pulseInLong()` oczekuje na zmianę stanu styku z niskiego (`LOW`) na wysoki (`HIGH`), rozpoczyna mierzyć czas, następnie czeka aż stan styku zmieni się na  niski (`LOW`) i zatrzymuje odmierzanie czasu. Zwraca długość impulsu w mikrosekondach albo 0 jeżeli nie został odebrany kompletny impuls w ciągu wyznaczonego czasu.

Odliczanie czasu przez tą funkcję zostało ustalone doświadczalnie i prawdopodobnie będzie wykazywać błędy przy krótszych impulsach. Works on pulses from 10 microseconds to 3 minutes in length (not over 3 minutes? check in source). Z tej procedury można korzystać tylko wtedy, gdy aktywowane są przerwania. Ponadto najwyższą rozdzielczość uzyskuje się w dużych odstępach czasu.
[%hardbreaks]


[float]
=== Składnia
`pulseInLong(styk, wartość)` +
`pulseInLong(styk, wartość, czas)`


[float]
=== Parametry
`styk`: numer styku Arduino, z którego chcesz odczytać impuls. Dozwolony typ danych: `int`. +
`wartość`: rodzaj impulsu do odczytania: link:../../../variables/constants/constants/[HIGH] lub link:../../../variables/constants/constants/[LOW]. Dozwolone typy danych: `int`. +
`czas` (opcjonalny): liczba mikrosekund oczekiwania na rozpoczęcie impulsu; domyślnie jedna sekunda. Dozwolony typ danych: `unsigned long`.


[float]
=== Wartości zwracane
Długość impulsu (w mikrosekundach) lub 0 jeśli w wyznaczonym czasie nie rozpoczął się żaden impuls. Typ danych: `unsigned long`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Opisz, na czym polega przykładowy kod i dodaj odpowiedni kod ►►►►► NINIEJSZA SEKCJA JEST OBOWIĄZKOWA ◄◄◄◄◄
Przykład drukuje czas trwania impulsu na styku 7.

[source,arduino]
----
int styk = 7;
unsigned long trwanie;

void setup() {
  Serial.begin(9600);
  pinMode(styk, INPUT);
}

void loop() {
  trwanie = pulseInLong(styk, HIGH);
  Serial.println(trwanie);
}
----
[%hardbreaks]

[float]
=== Uwagi i ostrzeżenia
Ta funkcja korzysta z micros(), więc nie można jej użyć w kontekście link:../../interrupts/nointerrupts[noInterrupts()] .

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
