---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= pulseIn()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Reads a pulse (either `HIGH` or `LOW`) on a pin. For example, if `value` is `HIGH`, `pulseIn()` waits for the pin to go from `LOW` to `HIGH`, starts timing, then waits for the pin to go `LOW` and stops timing. Returns the length of the pulse in microseconds or gives up and returns 0 if no complete pulse was received within the timeout.

The timing of this function has been determined empirically and will probably show errors in longer pulses. Works on pulses from 10 microseconds to 3 minutes in length.
[%hardbreaks]


[float]
=== Składnia
`pulseIn(pin, value)` +
`pulseIn(pin, value, timeout)`


[float]
=== Parametry
`pin`: the number of the Arduino pin on which you want to read the pulse. Allowed data types: `int`. +
`value`: type of pulse to read: either link:../../../variables/constants/constants/[HIGH] or link:../../../variables/constants/constants/[LOW]. Allowed data types: `int`. +
`timeout` (optional): the number of microseconds to wait for the pulse to start; default is one second. Allowed data types: `unsigned long`.


[float]
=== Wartości zwracane
The length of the pulse (in microseconds) or 0 if no pulse started before the timeout. Data type: `unsigned long`.

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Przykładowy kod
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The example prints the time duration of a pulse on pin 7.

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup() {
  Serial.begin(9600);
  pinMode(pin, INPUT);
}

void loop() {
  duration = pulseIn(pin, HIGH);
  Serial.println(duration);
}
----
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
