---
title: shiftIn()
categories: [ "Funkcje" ]
subCategories: [ "Zaawansowane We/Wy" ]
---





= shiftIn()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Wczytuje bajt danych bit po bicie. Zaczyna od najbardziej znaczącego (tj. najbardziej po lewej) lub najmniej (najbardziej po prawej) znaczącego bitu. Dla każdego bitu styk zegarowy jest podciągany do góry, następny bit jest odczytywany z linii danych, a następnie styk zegarowy jest sprowadzany w stan niski.

Jeśli łączysz się z urządzeniem, które jest taktowane zboczami narastającymi, musisz upewnić się, że styk zegarowy jest niski przed pierwszym wywołaniem `shiftIn()`, np. w połączeniu z `digitalWrite (stykZegarowy, LOW)`.

Uwaga: to jest implementacja programowa; Arduino zapewnia również link: https://www.arduino.cc/en/Reference/SPI [bibliotekę SPI], która korzysta z implementacji sprzętowej, która jest szybsza, ale działa tylko na określonych stykach.

[%hardbreaks]


[float]
=== Składnia
`byte wchodzący = shiftIn(stykDanych, stykZegarowy, kolejnośćBitów)`


[float]
=== Parametry
`stykDanych`: styk, z którego należy wprowadzić każdy bit. Dozwolone typy danych: `int`. +
`stykZegarowy`: styk sygnalizujący odczyt z *dataPin*. +
`kolejnośćBitów`: kolejność przesuwania bitów; *MSBFIRST* lub *LSBFIRST*. (Most Significant Bit First - pierwszy bit najbardziej znaczący, lub, Least Significant Bit First - pierwszy bit najmniej znaczący).


[float]
=== Wartości zwracane
Odczytana wartość. Typ danych: `byte`.

--
// KONIEC SEKCJI OPISOWEJ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

--
// KONIEC SEKCJI ZOBACZ TAKŻE
