---
title: tone()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= tone()


// POCZĄTEK SEKCJI OPISOWEJ
[#overview]
--

[float]
=== Opis
Generuje na styku falę prostokątną o określonej częstotliwości (i wypełnieniu 50%). Można określić czas trwania, w przeciwnym razie fala będzie kontynuowana do momentu wywołania link:../noTone[noTone()]. Aby odtwarzać dźwięki styk można podłączyć do brzęczyka piezoelektrycznego lub innego głośnika.

Jednorazowo można wygenerować tylko jeden dźwięk. Jeśli dźwięk jest już odtwarzany na innym styku, wywołanie tone() nie przyniesie żadnego efektu. Jeśli dźwięk był odtwarzany na tym samym styku, ustawi nową częstotliwość.

Użycie funkcji `tone()` zakłóci wyjście PWM na pinach 3 i 11 (na płytkach innych niż Mega).

Nie jest możliwe generowanie tonów niższych niż 31 Hz. Aby uzyskać szczegółowe informacje techniczne, patrz https://github.com/bhagman/Tone#ugly-details[Notatki Bretta Hagmana].
[%hardbreaks]


[float]
=== Składnia
`tone(styk, częstotliwość)` +
`tone(styk, częstotliwość, długość)`


[float]
=== Parametry
`styk`: pin Arduino, na którym ma być generowany dźwięk. +
`częstotliwość`: częstotliwość tonu w hercach. Dozwolone typy danych: `unsigned int`. +
`długość`: czas trwania tonu w milisekundach (opcjonalnie). Dozwolone typy danych: `unsigned long`.


[float]
=== Wartości zwracane
Nic

--
// KONIEC SEKCJI OPISOWEJ




// POCZĄTEK SEKCJI JAK UŻYWAĆ
[#howtouse]
--

[float]
=== Uwagi i ostrzeżenia
Jeśli chcesz odtwarzać różne dźwięki na wielu stykach, musisz najpierw zatrzymać dźwięk za pomocą noTone() na jednym styku, a następnie wygenerować nowy dźwięk za pomocą tone() na innym styku.
[%hardbreaks]

--
// KONIEC SEKCJI JAK UŻYWAĆ


// POCZĄTEK SEKCJI ZOBACZ TAKŻE
[#see_also]
--

[float]
=== Zobacz także

[role="language"]
* #LANGUAGE# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]

* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Melodia^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/tonePitchFollower[Ton śledzący^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone3[Klawiatura dźwiękowa^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone4[Wiele dźwięków^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// KONIEC SEKCJI ZOBACZ TAKŻE
